### ISSUE TITLE
Pending test spec

### ISSUE THREAD

**Issue by Gheoan** [aurelia/dialog#100]
On [this](https://github.com/aurelia/dialog/blob/e9d164f592a5409785ef94b9590ae689c3115485/test/unit/dialog-renderer.spec.js#L58) line the test spec is pending (`xit()` instead of `it()`). The spec fails if it is run. Is this behaviour intended?

**Comment by EisenbergEffect** [comment]
@PWKad Can you comment on this?

**Comment by PWKad** [comment]
I think the controller needs to be mocked better for that test to pass.  `xit` is a pending spec meaning `I wrote this spec and it should pass but it doesn't yet and I'm lazy and haven't finished it to get it green`.

I'll see if we can get this up and running.

**Comment by Gheoan** [comment]
@PWKad Should this issue be closed or do you plan to add the spec back after 169908509dddf405bebb18ca7c3e61a9e5bf5078?
