### ISSUE TITLE
`settings` property of `DialogController` not exposed in TypeScript typings

### ISSUE THREAD

**Issue by Jaans** [aurelia/dialog#108]
We recently migrated to `TypeScript` for our `Aurelia` projects - with great benefit I might add!

One of the issues we are running into is that the `aurelia-dialog.d.ts` typings file (included with JSPM) lacks the `settings` property.

```
  export class DialogController {
    constructor(renderer: DialogRenderer, settings: any, resolve: Function, reject: Function);
    ok(result: DialogResult): any;
    cancel(result: DialogResult): any;
    error(message: any): any;
    close(ok: boolean, result: DialogResult): any;
  }
```

We need access to the settings property so we can call `this.dialogController.settings.lock = true`, without which our dialogs don't work (button clicks do not dismiss dialog). 

Unfortunately the export for `DialogController` is a `class` and not an `interface`, so we cannot ["merge" a custom TypeScript interface declaration for it](http://www.typescriptlang.org/Handbook#declaration-merging-merging-interfaces) and "duck-type" it to work. So at the moment we manually add (and re-add) the property to the JSPM version.

Admittedly, I'm not exactly sure about the inner mechanics of the dialog controller and our implementation is based off samples from the web, so please excuse this issue if we are "doing it wrong" and accessing the settings property was intended to be private.

**Comment by Gheoan** [comment]
I think this was fixed in https://github.com/aurelia/dialog/pull/97.

**Comment by Jaans** [comment]
Thanks for the quick reply!
It looks like it as the default scope for TS properties are public - so that would be great news! 

Is that change something that has made it way through to JSPM yet?

**Comment by Gheoan** [comment]
@Jaans A new release is needed for the typings to update.

**Comment by PWKad** [comment]
Released.
