### ISSUE TITLE
Margin would be better than padding

### ISSUE THREAD

**Issue by jeff-h** [aurelia/dialog#113]
At present there's 16px padding on `ai-dialog-header` and `ai-dialog-body`. If it were margin instead, it would collapse with any top margin on a contained element.

Imagine that the header contains an H1 element. The H1 element likely has quite a bit of top margin (20px in Safari). This currently results in a very large gap, being 16px padding + 20px h1 top margin = 36px.

Ideally, it would be just 20px (16px collapsed against 20px), which would be achieved by switching the default styling to margin.

Of course I do realise I can override this, but I think what I'm proposing would be a better starting point.

**Comment by PWKad** [comment]
@jeff-h PR is welcome on this, I'm timid about switching the styles at the moment unless someone is willing to do some exhaustive cross-browser/platform testing because all of these tweaks in the past have had snow ball effects :)

**Comment by Alexander-Taran** [comment]
Stale since 2016

**Comment by Alexander-Taran** [comment]
@bigopon can be closed
