### ISSUE TITLE
startingZIndex only works as global setting

### ISSUE THREAD

**Issue by jeff-h** [aurelia/dialog#114]
For me at least, setting the `startingZIndex` only takes effect if it's done in the global settings e.g. in my `main.js`:

```js
  aurelia.use.plugin('aurelia-dialog', (settings) => {
    settings.startingZIndex = 1032; // Go above Bootstrap navigation.
  });
```

Setting it in my specific `DialogController` doesn't work, although other settings such as `settings.lock` do work in that location.

If this is not a bug could you adjust the docs slightly to point this out?

**Comment by PWKad** [comment]
Hmm I'm not 100% sure which is better.  Basically right now we stack everything on the starting globalSetting and just increment after that.  Might be best to document it for now.

**Comment by jeff-h** [comment]
Thanks!
