### ISSUE TITLE
Reduce coupling by introducing dialog component

### ISSUE THREAD

**Issue by stalniy** [aurelia/dialog#116]
I believe that I have a great idea of how modal/dialogs could be implemented using custom element. This will allow to reduce coupling between parent view and modal dialog, so in future it will be much easier to add changes/improvements to the codebase.

**Proposition**:
```html
// grid.html
<table>
   <tr repeat.for="item of products"> 
     <td>${ item.name }</td>
     <td><a href click.bind="selectProduct(item)">edit</a></td>
   </tr>
</table>

<dialog if.bind="!selectedProduct" on-close="resetSelected()" title="Edit ${selectedProduct.name}">
   <dialog-body>
    <product-form product.bind="selectedProduct"></product-form>
  </dialog-body>
</dialog>
```
Then lets imagine the future:
we don't want to use modal windows anymore and instead, want to show table and edited product side by side (e.g., using floats or flexbox). Then What we need is just to change HTML code and it will be like this:
```html
// grid.html
<table class="pull-left">
   <tr repeat.for="item of products"> 
     <td>${ item.name }</td>
     <td><a href click.bind="selectProduct(item)">edit</a></td>
   </tr>
</table>

<product-form if.bind="!selectedProduct" product.bind="selectedProduct" class="pull-right"></product-form>
```
So, no odd dependencies on dialog inside `grid` component. Is it great?

If you think it is, I'd like to see such component as part of this library.

CC: @EisenbergEffect

**Comment by PWKad** [comment]
This should all work currently as-is could you give me an idea of what is not working?

**Comment by stalniy** [comment]
Ah, ok. I didn't find this in examples. Everything uses `dialogService` which creates coupling between modal window components and host component (which injects service)

In the provided example there is no such coupling. 

So, if this library allows to do what I wrote in the example, the issue may be closed. 

Probably, it'd be useful to provide this example in the doc, so people won't do same mistakes as in Angular 1.x

**Comment by PWKad** [comment]
PR welcome to add directions on how to do this without using the DialogService - I would first use your example in a skeleton to verify the code is correct and then simply PR it and we can merge it in.
