### ISSUE TITLE
Problem to load dialog plugin

### ISSUE THREAD

**Issue by timvr01** [aurelia/dialog#117]
I've installed the aurelia-dialog trough 'jspm install aurelia-dialog'.
After i put the plugin in my main.js file like this:

```
import 'bootstrap';
import 'fetch';
import {I18N} from 'aurelia-i18n'; // src="https://github.com/aurelia/i18n"
import {config} from './authConfig';

export function configure(aurelia) {
    aurelia.use
      .standardConfiguration()
      .developmentLogging()
        //dialog plugin
      .plugin('aurelia-dialog')
        //modal plugin
      .plugin('aurelia-bs-modal')
        //material plugin
      .plugin('redpelicans/aurelia-material')
        //translate plugin
      .plugin('aurelia-i18n', (instance) => {
          instance.setup({
              resGetPath : 'locale/__lng__/__ns__.json',
              lng : 'en',
              attributes : ['t','i18n'],
              getAsync : true,
              sendMissing : false,
              fallbackLng : 'en',
              debug : false
          });
      })
        //validation plugin
      .plugin('aurelia-validation')
        //auth plugin
      .plugin('aurelia-auth', (baseConfig) => {
          baseConfig.configure(config);
      });

  aurelia.start().then(() => aurelia.setRoot());
}
```

I keep getting this error no matter what i do or reinstall.
![screenshot 2016-03-15 13 23 50](https://cloud.githubusercontent.com/assets/10833461/13777699/f410cafc-eab1-11e5-9f8e-326795971469.png)

The dialog plugin is in my jspm packages
![screenshot 2016-03-15 13 29 57](https://cloud.githubusercontent.com/assets/10833461/13777828/a298a860-eab2-11e5-9ca4-4a4afb8ece0d.png)

**Comment by arnevdv** [comment]
I got exactly the same error in my apache cordova project

**Comment by SamuelCaudenberg** [comment]
I get a very similar 404 error
![image](https://cloud.githubusercontent.com/assets/10906724/13777940/48e20392-eab3-11e5-8da0-265e2384672f.png)

**Comment by EisenbergEffect** [comment]
Make sure you guys have everything up to date, including the loader.

To update libs `jspm update`
To update the loader `jspm dl-loader --latest`

**Comment by SamuelCaudenberg** [comment]
Thanks Rob, you must have a magic touch or something

**Comment by timvr01** [comment]
The first time i did that, it did not helped but now i did, thank you mr. hero!
