### ISSUE TITLE
Dialog cannot be dragged

### ISSUE THREAD

**Issue by rborosak** [aurelia/dialog#118]
How can I make the dialog draggable?

**Comment by alvarezmario** [comment]
@rborosak I think the faster way will be a PR :smile:

**Comment by EisenbergEffect** [comment]
I'm not sure if we want to build that in or not. I think it would likely be accomplished by using a custom attribute on ai-aialog to add that behavior though. That's how I would start experimenting with it.

**Comment by PWKad** [comment]
Agreed I don't think we want to add this to the base dialogs as we want to keep it as basic as possible to allow customization.

If you use your own modal styles you can have them be draggable which may be easier.
