### ISSUE TITLE
Refactor dialog-controller and dialog-renderer for better separation of concerns

### ISSUE THREAD

**Issue by jedd-ahyoung** [aurelia/dialog#119]
I think that the `aurelia-dialog` plugin should be able to support multiple renderers. This would mean that the dialog plugin would function as a controller-style backend for any modal dialog implementation.

The problem right now is that there is some functionality wrapped in the `dialog-renderer` module, specifically in `createDialogHost` that I believe should be factored into `dialog-controller` or another module. If we can create the viewSlot outside of the renderer and pass it in, then we can easily swap in different modal implementations. Additionally, if we create a base interface for the renderer component, we can remove specific calls in the controller (like destroyDialogHost) and replace them with interface equivalents.

Even if there are other solutions down the line, this may lower the barrier to entry for people who want to use Aurelia viewmodels with different modal plugins; they can create their own renderer (or choose one that already exists) and get working quickly. Any thoughts?

**Comment by EisenbergEffect** [comment]
Sounds interesting. I'd love to see a PR based on this idea.
