### ISSUE TITLE
Determine if dialog is open

### ISSUE THREAD

**Issue by cehoffman** [aurelia/dialog#121]
It would be nice if the dialog service had a property or method that would signal if there is a dialog open through the service. In my application I have routes which open various dialogs depending on user action, but in a completely separate part of the application I need to prevent any progress from occurring if there is an active modal.

I could see it being useful to retrieve the active modal instance from the dialog service, but I don't have such a need.

Right now I'm searching the DOM for indications that a dialog is open, but it doesn't feel right to do that.

**Comment by EisenbergEffect** [comment]
Great idea! @jedd-ahyoung Any interest in working on this?

**Comment by jedd-ahyoung** [comment]
@EisenbergEffect I think this can be done by moving the responsibility of handling the controller collection from `dialog-renderer` to `dialog-service`. I think this would be a better separation of concerns and I think it would distill the renderer somewhat.

I may be able to put time into this, but note that I owe you a lot of stuff - router issues and Angular documentation being part of that. I can take this on - let me know how you'd like me to prioritize this.

**Comment by EisenbergEffect** [comment]
How much time do you think it would take to add this? If not much, then I'd say go ahead and knock it out. If it's more involved, then I'd say work on the router issues instead. Let me know.

**Comment by jedd-ahyoung** [comment]
I think I can knock this out in a night (tonight), unless there are any
unforeseen issues.

2016-03-21 9:31 GMT-04:00 Rob Eisenberg <notifications@github.com>:

**Comment by EisenbergEffect** [comment]
That sounds good. I'd say, go for it. Ping me when it's ready and I'll get it merged in. Thanks!
