### ISSUE TITLE
Upgrading from `0.5.8` to `0.5.9` doesn't work (unclear why).

### ISSUE THREAD

**Issue by Zoltu** [aurelia/dialog#124]
I'm not sure what happened, but `0.5.8` works fine for me and `0.5.9` doesn't work at all.

Plugin application: https://github.com/Zoltu/RepoCreator-Client/blob/1a7c0f9d0d115edf579f8a431b8388d6d37a2467/dist/source/main.ts#L6
Dependency injection: https://github.com/Zoltu/RepoCreator-Client/blob/1a7c0f9d0d115edf579f8a431b8388d6d37a2467/dist/source/repo-creator/repository-chooser.ts#L23

When I put a breakpoint in the `RepositoryChooser` constructor and then navigate to that part of my UI chrome debugger shows `this.dialogService === {}`.  The other 3 dependency injected services are of the correct type.

**Comment by EisenbergEffect** [comment]
@jedd-ahyoung If you get a chance, can you look at this. There may be something wrong somewhere.

**Comment by EisenbergEffect** [comment]
@Zoltu I'm upgrading one of my own projects that uses dialog tomorrow. So if @jedd-ahyoung doesn't get to this first, I'll address it as part of that process.

**Comment by cehoffman** [comment]
Yep, just throwing out there a confirmation that DialogService is undefined with imported in 0.5.9.

**Comment by heruan** [comment]
I confirm this: imported `DialogService` results `undefined`.

**Comment by AdamWillden** [comment]
:-( Yep confirm same

**Comment by jedd-ahyoung** [comment]
@EisenbergEffect The issue is here:
https://github.com/aurelia/dialog/commit/397c64a78360aeed072d84b1e55803ece0897ff2#diff-1fdf421c05c1140f6d71444ea2b27638L2

It looks as though the default exports got altered somehow during the
release process. Reverting the index.js file and issuing a patch release
should fix this.

2016-03-23 6:38 GMT-04:00 Adam Willden <notifications@github.com>:

**Comment by EisenbergEffect** [comment]
Ok, I've updated the build and pushed out a release. Let me know if this solves the problems.
