### ISSUE TITLE
Dialog doesn't close on click out

### ISSUE THREAD

**Issue by iveetoo** [aurelia/dialog#125]
Hi, according to the docs (and the source), if `setting.lock = false` and the user clicks outside of the dialog, it will close it and resolve it with cancel. But, when I click outside - nothing happens.

The event handler, for closing the dialog, is set on the overlay layer (https://github.com/aurelia/dialog/blob/master/src/renderers/dialog-renderer.js#L76) and is never called, because `ai-dialog-overlay` has css style `pointer-events:none`, which prevents all clicks on this element. 

I found this issue #74, which describes the same problem about closing the dialog, but the problem were that the container was on top of the overlay and it was fixed with disabling pointer events on the `ai-dialog-container` to enable click events on `ai-dialog-overlay` #79

When I remove `pointer-events:none`; from `ai-dialog-overlay` and set it on `ai-dialog-container` the event handler is called and the dialog is closed correctly.

**Comment by Tarpsvo** [comment]
Thanks mate, saved me a lot of trial-and-error.

Looking forward to an official fix.

Till then:

```
ai-dialog-overlay {
    pointer-events: all !important;
}

ai-dialog-container {
    pointer-events: none !important;
}
```

**Comment by heruan** [comment]
I think it would be nice also this:
```css
ai-dialog-container > * {
    pointer-events: auto;
}
```
so that any custom direct child of `ai-dialog-container` will behave correctly without the need of setting the property like in `ai-dialog`.

**Comment by EisenbergEffect** [comment]
@jedd-ahyoung I can't remember who added the pointer events styling. However, we probably need to seek out an alternate approach in general. That style capability does not work in all versions of IE that we need to support. We need to support IE9 and above.

**Comment by jedd-ahyoung** [comment]
@EisenbergEffect There's an easy way to do this. Basically, the CSS styles that are in use for the dialog are problematic in general. If we revamp the CSS, this problem will disappear naturally. (Essentially, the overlay can exist under the container, which doesn't need to stretch to fill the entire screen.) This should be a simple style fix.

**Comment by EisenbergEffect** [comment]
@jedd-ahyoung Yes please :) Do you have some availability to do this soon?

**Comment by EisenbergEffect** [comment]
Also, we may want to not load the css in the html, but instead do it through an import statement. There are some ongoing issues with webpack that this might help fix. It's a separate issue. We can investigate that after the CSS revamp itself.

**Comment by jedd-ahyoung** [comment]
When do you need it? I still owe you a bunch of router stuff (haven't
forgotten about it) and I've got a lot of writing tasks to do. If it's
something you need right away I can knock it out before Sunday.

2016-04-21 14:10 GMT-04:00 Rob Eisenberg <notifications@github.com>:

**Comment by EisenbergEffect** [comment]
Sure, go ahead and do this first, since there's a lot of activity around this issue, then circle back around to the other items.
