### ISSUE TITLE
aurelia-dialog won't work with webpack

### ISSUE THREAD

**Issue by mib4fun** [aurelia/dialog#126]
hi guys !

I'm a beta webpack + aurelia user ! :dancer: 

I'm having trouble making work aurelia-dialog withwebpack.
It's loading fine but can't open the dialog. 
I got this error 

![error](https://cloud.githubusercontent.com/assets/3010867/14046160/4d5bc66a-f297-11e5-8265-0dc60ab7ab5f.jpg)

**Comment by DiknT** [comment]
How did you even get it to load?
Following the example setup I end up with module not found:
```
Unhandled rejection Error: Cannot find module './aurelia-dialog/resources/ai-dialog'.
```

**Comment by mib4fun** [comment]
You have to modify your webpack.config.js
My current config here 
 https://gist.github.com/mib4fun/9247adffdb08959e9a18

**Comment by EisenbergEffect** [comment]
@mib4fun Would you be interested to make a PR to the readme file in the skeleton that explains how to configure aurelia plugins for webpack? That could be very meaninful for the community.

**Comment by mib4fun** [comment]
@EisenbergEffect , yeah you right. i'll do it !
But i have to resolve this issue first.

the aurelia-dialog plugin is loading well with my config.
But i can't open a dialog with thte dialogservice. I have this error :arrow_up: 
I have narrowed the issue to that function
https://github.com/aurelia/dialog/blob/master/src/dialog-service.js#L80

it's returning
<pre>
Object {moduleId: undefined, moduleMember: undefined}
</pre>

I taught @PWKad might help on this

**Comment by jww2000** [comment]
@mib4fun it looks like something here 
```code
var instruction = {
        viewModel:  _settings.viewModel,
        container: _this.container,
        childContainer: childContainer,
        model: _settings.model
      };
I changed it to 
var instruction = {
        viewModel: Object.assign({}, _settings.viewModel),
        container: _this.container,
        childContainer: childContainer,
        model: _settings.model
      };

```
but now I have another error

**Comment by EisenbergEffect** [comment]
@mib4fun That is a different issue than what is reported here. Can you open up a new issue for that and then attach a simple reproduction so we can see the problem and try to figure it out? If you can recreate it on top of the webpack skeleton that would help us.

**Comment by mib4fun** [comment]
@EisenbergEffect, i have created the sample repo and an other issue #127
