### ISSUE TITLE
renderer.js:21 Uncaught (in promise) Error: DialogRenderer must implement getDialogContainer()

### ISSUE THREAD

**Issue by timvr01** [aurelia/dialog#130]
This morning when I opened my project I got this error when I tried to launch a dialog. I have no clue what this means and before today it was working just fine...

![screenshot 2016-03-29 10 33 26](https://cloud.githubusercontent.com/assets/10833461/14102274/d11e378a-f599-11e5-9469-8fff28131c37.png)

**Comment by iveetoo** [comment]
Did you call the useDefaults() method to apply the base configuration? The documentation was updated a few days ago

**Comment by timvr01** [comment]
I did not realise that. So it is not possible anymore to declare my settings like this?

```
.plugin('aurelia-dialog', (settings) => {
          settings.lock = false;
          settings.centerHorizontalOnly = true;
          settings.centerVerticalOnly = true;
          settings.startingZIndex = 5;
      })
```

**Comment by iveetoo** [comment]
It is possible, but you must declare your global settings on the configuration object, that is passed to the callback function. From the docs: 

> You can specify global settings as well for all dialogs to use when installing the plugin via the configure method. If providing a custom configuration, you must call the useDefaults() method to apply the base configuration.

```
export function configure(aurelia) {
  aurelia.use
    .standardConfiguration()
    .developmentLogging()
    .plugin('aurelia-dialog', config => {
      config.useDefaults();
      config.settings.lock = true;
      config.settings.centerHorizontalOnly = false;
      config.settings.startingZIndex = 5;
    });

  aurelia.start().then(a => a.setRoot());
}
```

Also, there isn't a  setting called `centerVerticalOnly`

**Comment by timvr01** [comment]
Thanks it works like that but i don't see my close X icon anymore, no matter the lock settings...

**Comment by timvr01** [comment]
Thanks a lot, it works that way!
