### ISSUE TITLE
Failing to load dialog resources with webpack

### ISSUE THREAD

**Issue by Jaans** [aurelia/dialog#132]
I'm trying to use this plug-in with webpack, but it doesn't work. When I initialise the plugin with the following:

```
bootstrap((aurelia: Aurelia): void => {
    aurelia.use
        .standardConfiguration()
        .developmentLogging()
        .plugin("aurelia-animator-css")
        .plugin("aurelia-dialog", (dialogConfig: any) => {
            dialogConfig.useDefaults();
            dialogConfig.lock = true;
            dialogConfig.startingZIndex = 5;
        });

    aurelia.start().then(a => a.setRoot());
});
```

I get the following errors in the Chrome console:

```
DEBUG [aurelia] Loading plugin aurelia-dialog.
1.bundle.js:53492 DEBUG [aurelia] Configured plugin aurelia-dialog.
1.bundle.js:208 Uncaught (in promise) Error: Cannot find module './aurelia-dialog/resources/ai-dialog'.
    at http://localhost:9000/1.bundle.js:208:42
    at webpackContextResolve (http://localhost:9000/1.bundle.js:208:90)
    at webpackContext (http://localhost:9000/1.bundle.js:205:30)
    at http://localhost:9000/bundle.js:13943:50
    at Function.requireEnsure [as e] (http://localhost:9000/bundle.js:62:29)
    at http://localhost:9000/bundle.js:13942:32
    at WebpackLoader._import (http://localhost:9000/bundle.js:13937:13)
    at http://localhost:9000/bundle.js:13993:17
    at WebpackLoader.loadModule (http://localhost:9000/bundle.js:13991:13)
    at WebpackLoader.loadAllModules (http://localhost:9000/bundle.js:13977:24)(anonymous function) @ 1.bundle.js:208webpackContextResolve @ 1.bundle.js:208webpackContext @ 1.bundle.js:205(anonymous function) @ bundle.js:13943requireEnsure @ bundle.js:62(anonymous function) @ bundle.js:13942_import @ bundle.js:13937(anonymous function) @ bundle.js:13993loadModule @ bundle.js:13991loadAllModules @ bundle.js:13977importViewResources @ 1.bundle.js:9812(anonymous function) @ 1.bundle.js:750
1.bundle.js:208 Uncaught (in promise) Error: Cannot find module './aurelia-dialog/resources/ai-dialog-header'.(…)(anonymous function) @ 1.bundle.js:208webpackContextResolve @ 1.bundle.js:208webpackContext @ 1.bundle.js:205(anonymous function) @ bundle.js:13943requireEnsure @ bundle.js:62(anonymous function) @ bundle.js:13942_import @ bundle.js:13937(anonymous function) @ bundle.js:13993loadModule @ bundle.js:13991loadAllModules @ bundle.js:13977importViewResources @ 1.bundle.js:9812(anonymous function) @ 1.bundle.js:750
1.bundle.js:208 Uncaught (in promise) Error: Cannot find module './aurelia-dialog/resources/ai-dialog-body'.(…)(anonymous function) @ 1.bundle.js:208webpackContextResolve @ 1.bundle.js:208webpackContext @ 1.bundle.js:205(anonymous function) @ bundle.js:13943requireEnsure @ bundle.js:62(anonymous function) @ bundle.js:13942_import @ bundle.js:13937(anonymous function) @ bundle.js:13993loadModule @ bundle.js:13991loadAllModules @ bundle.js:13977importViewResources @ 1.bundle.js:9812(anonymous function) @ 1.bundle.js:750
1.bundle.js:208 Uncaught (in promise) Error: Cannot find module './aurelia-dialog/resources/ai-dialog-footer'.(…)(anonymous function) @ 1.bundle.js:208webpackContextResolve @ 1.bundle.js:208webpackContext @ 1.bundle.js:205(anonymous function) @ bundle.js:13943requireEnsure @ bundle.js:62(anonymous function) @ bundle.js:13942_import @ bundle.js:13937(anonymous function) @ bundle.js:13993loadModule @ bundle.js:13991loadAllModules @ bundle.js:13977importViewResources @ 1.bundle.js:9812(anonymous function) @ 1.bundle.js:750
1.bundle.js:208 Uncaught (in promise) Error: Cannot find module './aurelia-dialog/resources/attach-focus'.(…)
```

This appears to be a similar / related loading problem to [this](https://github.com/aurelia/validation/issues/226), except that I don't think it has to do with SystemJS - it just appears not to be loading the view templates. 

Sadly, I'm out of my depth here with webpack - just trying to see whether it's a workable alternative to SystemJS workflow, but I'm not having much success, despite using the Typescript-Webpack skeleton as a guide (but it doesn't include validation or dialog, etc.). 

The above referenced validation plug-in issue is tripping me up also.

**Comment by Zensavona** [comment]
I'm experiencing this issue as well, it's because there's a html `<require>` which is requiring css, and tripping up Webpack.

@EisenbergEffect is this imported using a `<require>` in the html for ease of override? If not, would it be ok to move it to an `import` in the JS code? I'm pretty sure that would solve this issue.

**Comment by EisenbergEffect** [comment]
There's a difference between requires in html and in JS. We should work to get the css in html requires working with Webpack. It's probably just a bug in aurelia-webpack-loader. It would be excellent if some community members who were enthusiastic about webpack dug into that code and submitted a PR to get this working universally.

**Comment by fjes82** [comment]
martijnboland proposes a fix here: https://github.com/aurelia/webpack-plugin/issues/11.

It overrides the css loader for aurelia-dialog with the raw loader.

Worked for me.

**Comment by Jaans** [comment]
Thanks for that.

Sadly, the fix suggested by @fjes82 doesn't work for me. I've tried it any which way I can image and simply cannot get the issue resolved. It doesn't seem to be an issue with CSS loading as I have that configured to use the RAW loaders when required / imported with Aurelia.

In fact the errors I'm getting is that it's failing to load the modules, as in the `.js exports`. So that means that the webpack loader is expecting to find a map for `./aurelia-dialog/resources/ai-dialog` module in it's bundle, but doesn't. I checked the webpack bundles being output and also the webpack CLI command output, and for some reason it isn't including it in the bundle. I can confirm the source file is present in the NPM package.

I'll keep trying to figure this out and if I ever do manage to resolve I will post here.

**Comment by Jaans** [comment]
UPDATE: Webpack seems to be including the resource modules as can be evidenced from the CLI output below (refer 56,57,60, etc.)

```
   [55] ./~/aurelia-dialog/dist/commonjs/aurelia-dialog.js 2.33 kB {1} [built]
   [56] ./~/aurelia-dialog/dist/commonjs/resources/ai-dialog.js 521 bytes {1} [built]
   [57] ./~/aurelia-dialog/dist/commonjs/resources/ai-dialog-header.js 757 bytes {1} [built]
   [58] ./~/aurelia-dialog/dist/commonjs/dialog-controller.js 1.94 kB {1} [built]
   [59] ./~/aurelia-dialog/dist/commonjs/lifecycle.js 493 bytes {1} [built]
   [60] ./~/aurelia-dialog/dist/commonjs/resources/ai-dialog-body.js 546 bytes {1} [built]
   [61] ./~/aurelia-dialog/dist/commonjs/resources/ai-dialog-footer.js 3.22 kB {1} [built]
   [62] ./~/aurelia-dialog/dist/commonjs/resources/attach-focus.js 970 bytes {1} [built]
   [63] ./~/aurelia-dialog/dist/commonjs/dialog-configuration.js 1.72 kB {1} [built]
   [64] ./~/aurelia-dialog/dist/commonjs/renderers/renderer.js 825 bytes {1} [built]
   [65] ./~/aurelia-dialog/dist/commonjs/renderers/dialog-renderer.js 4.97 kB {1} [built]
   [66] ./~/aurelia-dialog/dist/commonjs/dialog-options.js 196 bytes {1} [built]
   [67] ./~/aurelia-dialog/dist/commonjs/dialog-service.js 3.52 kB {1} [built]

```
What is interesting is that while I can find the content of these modules (e.g. 56) in the bundles, it is not registered in the bundle mapping and that's why it doesn't find it. This looks like it could possibly be a webpack issue.

**Comment by istrau3** [comment]
You need to include the following in your webpack.config file:

```javascript
plugins: [
        new AureliaWebpackPlugin({
            includeSubModules: [
                {
                    moduleId: 'aurelia-dialog'
                }
            ]
        })
    ],
```

**Comment by Jaans** [comment]
That did it! Thank you @istrau3 

Is there any guidance somewhere on this `includeSubModules` bit to understand why it's needed and therefore when to use it how?

**Comment by istrau3** [comment]
@Jaans check out the aurelia webpack plugin readme =).

**Comment by EisenbergEffect** [comment]
Probably we need to add some notes on this to the skeleton. Anyone want to
send a PR? :)
On Apr 7, 2016 9:28 AM, "istrau3" <notifications@github.com> wrote:

@Jaans <https://github.com/Jaans> check out the aurelia webpack plugin
readme =).

—
You are receiving this because you were mentioned.

Reply to this email directly or view it on GitHub
<https://github.com/aurelia/dialog/issues/132#issuecomment-206901880>

**Comment by PWKad** [comment]
Seems completed so I am closing for now.

**Comment by kristianmandrup** [comment]
I still can't seem to load a simple `.css` file in a project created using the CLI. My bootstrap css gets loaded however.

```html
  <require from="bootstrap/css/bootstrap.css"></require>
  <require from="./styles.css"></require>
```

`Error: Failed loading required CSS file: styles.css` :(

Any docs on this?
