### ISSUE TITLE
Margin-left of created dialog

### ISSUE THREAD

**Issue by Silverado-by** [aurelia/dialog#133]
I'm using latest (0.5.10) of aurelia-dialog and slightly confused: showed dialog sticks to the left side of window. After some investigating i've found that nested element ('au-target') has marginLeft='0px' and i think it's obviously wrong in this case. I've created some workaround used settings.position in my viewmodel:

    position(modalContainer, modalOverlay) {
		var child = modalContainer.children[0];
		child.style.marginLeft = '';
		var vh = Math.max(document.documentElement.clientHeight, window.innerHeight || 0);
		child.style.marginTop = Math.max((vh - child.offsetHeight) / 2, 30) + 'px';
	}

But i don't think it's the right way. Am i doing something wrong or it's just a bug?

**Comment by PWKad** [comment]
Can you reproduce this anywhere?  I cannot with the provided samples or in my applications.  If you can please include it here and let's reopen this issue.
