### ISSUE TITLE
viewModel setting gets overridden by module index

### ISSUE THREAD

**Issue by heruan** [aurelia/dialog#136]
I'm trying to use a VM for the dialog, but `DialogService` ignores that and lookup the VM's moduleId to use that instead. Is this by design? Then I think the `viewModel` setting should be renamed with `moduleId`, such as in `RouteConfig` of "aurelia-router".

For example:
```javascript
import {MyModalVM} from "my-module";

    // ...
    this.dialogService.open({ viewModel: MyModalVM, model: "Test" });
```
this would lookup `"my-module"` with `Origin.get(instruction.viewModel).moduleId;` and then will use the first exported VM from that module, instead the desired VM.

**Comment by PWKad** [comment]
Can you explain the expected result and what is actually happening or what the bug is here?  Sorry I don't quite follow what isn't working (unless you mean that the name should be different)

Perhaps you mean if you try to pass an instance of a view-model it isn't working?

**Comment by heruan** [comment]
Say I have `my-module` which exports several VMs from its `my-module/index.js`. Then if I try the snippet above, `DialogService` tries to use `my-module/index.js` itself as the `viewModel`, not the `MyModalVM` which I have imported.

**Comment by npelletm** [comment]
Same issue DialogService try to load my-module/index.js

**Comment by EisenbergEffect** [comment]
If your view model isn't the only export from its module then Aurelia will get confused because it can't find a view associated with it.

**Comment by npelletm** [comment]
@EisenbergEffect : I removed the many export of my VM in my buggy require js bundle and it works :)
Thanks.

**Comment by EisenbergEffect** [comment]
Great!
