### ISSUE TITLE
Fast code close crash

### ISSUE THREAD

**Issue by rockResolve** [aurelia/dialog#137]
When I open and close a dialog quickly using code, the close can cause a number of different errors depending on the timing. At the worst "hideDialog is undefined", when the controller is not fully built on open, but a close is attempted.

**Use case:** Progress or Activity dialogs that may be closed by code rather than by a user clicking a button. Sometimes they may be closed very quickly after they have been opened.

Both the Open & Close operations generate promises to do the work, and both also use the CSS TransitionEnd event to trigger further processing. These factors cause two problems:

1. The Open CSS TransitionEnd event is not always fired. Normally this is not noticed as no further Open processing occurs afterward. However this appears to also cause the Close TransitionEnd event to never fire either. As the TransitionEnd is in the middle of close processing, it in turn causes the dialog & overlay to be hidden, but not destroyed. The symptom is that the invisible overlay consumes all mouse clicks.

2. The current code does not publish the Open Dialog promise. Currently the open returns a promise resolved with the state of any later closure. However very quick closes must wait at least for the dialog to fully open, otherwise the partially open dialog causes errors when the close is processed.

PR to follow

**Comment by jedd-ahyoung** [comment]
@rockResolve I've addressed this issue with a commit that allows skipping CSS transitions. However, I think we've also addressed the base issue by simplifying the renderer (no more method undefined errors). Within the next few days or so, would you be able to confirm that this is working for you (without ignoring the CSS transitions)? I'd like to see if we're supporting your use case with these fixes.

**Comment by EisenbergEffect** [comment]
@jedd-ahyoung Is this resolved now?

**Comment by rockResolve** [comment]
Sounds great in principal. Hope to test soon.

**Comment by davismj** [comment]
@rockResolve did you have a chance to test? is the issue resolved?

**Comment by rockResolve** [comment]
So finally had a chance to test this.

I found the root cause of much of this was the app router running removeAll on the viewSlot. This removed my previously created "Fetching data" dialog element, so the TransitionEnd was not fired, and the open (or openAndYeildController) promise was never resolved.

So ignoreTransitions was the perfect fix.

I also use the new dialogService.openAndYieldController which simplified my code.

Many thanks.

**Comment by PWKad** [comment]
Just noticed this was actually closed.
