### ISSUE TITLE
Setting the modal opacity via CSS not working

### ISSUE THREAD

**Issue by Tim-Erwin** [aurelia/dialog#139]
In the README there is an example to set the opacity of the modal:

```
ai-dialog-overlay.active {
  background-color: black;
  opacity: .5;
}
```

However, this does not work for me, because aurelia-dialog adds an embedded style `ai-dialog-overlay.active {opacity: 1;}` to the page which has precedence.

I could work around that issue by using `.ai-dialog-open ai-dialog-overlay.active` as selector.

**Comment by PWKad** [comment]
I'll try to double-check this and update readme if it is not working as described.  PR also welcome.

**Comment by dilvish4ever** [comment]
Same issue
Another work around `opacity: .5!important`

**Comment by jedd-ahyoung** [comment]
This should be fixed by https://github.com/aurelia/dialog/commit/c8b7cc0021ebb56b499a7320386c6d47630a95c2#diff-3f7038e519401159757001b6515db643R16 - setting the CSS is now supported at plugin configuration time. It can either be updated with desired settings or removed entirely to allow stylesheets to determine modal styling.

**Comment by avar0** [comment]
can somebody tell where the documentation for setting the css is? i cannot find it in the read me file

**Comment by Tim-Erwin** [comment]
Not sure if i understand correctly, but there is no setting that creates that CSS. You have to have your own CSS/SASS/LESS with the according rule. If you use the [skeleton app](https://github.com/aurelia/skeleton-navigation/tree/master/) you'll already find some CSS where you can add your rules.

**Comment by sahshaurya** [comment]
Hi, I tried adding 
```
ai-dialog-overlay.active {
  background-color: black;
  opacity: .5!important;
}

```
to the CSS file that I'm importing, but it doesn't help.

Any suggestions?

Thank you.

**Comment by StrahilKazlachev** [comment]
@sahshaurya If you are using a `rc` version, the classes are prefixed with `ux-` and not `ai-`, so `ux-dialog-overlay`.
