### ISSUE TITLE
can't load aurelia-dialog in skeleton-typescript-asp.net5

### ISSUE THREAD

**Issue by CarlosOnline** [aurelia/dialog#142]
**Error: A BindingLanguage must implement parseText**(...)(…)parseText     
GET http://localhost:49849/jspm_packages/npm/aurelia-dialog@0.5.10/dialog.css.js 404 (Not Found)

**How do I get the aurelia-dialog plugin to work in the skeleton-typescript-asp.net5?**

I ran 
jspm install aurelia-dialog
gulp build
launched the site and got the following errors.

```
    aurelia.use
        .standardConfiguration();
    aurelia.use.developmentLogging();
    aurelia.use.plugin('aurelia-dialog');

```

```
aurelia-templating.js:692 Uncaught (in promise) Error: A BindingLanguage must implement parseText(...)(…)parseText 
    @ aurelia-templating.js:692_compileNode 
    @ aurelia-templating.js:2008_compileNode 
    @ aurelia-templating.js:2028compile 
    @ aurelia-templating.js:1985(anonymous function) 
    @ aurelia-templating.js:2615

system.src.js:4597 GET http://localhost:49849/jspm_packages/npm/aurelia-dialog@0.5.10/dialog.css.js 404 (Not Found)I 
    @ system.src.js:4597(anonymous function) 
    @ system.src.js:4597(anonymous function) 
    @ system.src.js:4597(anonymous function) 
    @ system.src.js:4597(anonymous function) 
    @ system.src.js:4597(anonymous function) 
    @ system.src.js:4597(anonymous function) 
    @ system.src.js:4597(anonymous function) 
    @ system.src.js:4597(anonymous function) 
    @ system.src.js:4597(anonymous function) 
    @ system.src.js:4597
```

**Comment by doktordirk** [comment]
that parseText erro can happen with forks

**Comment by CarlosOnline** [comment]
How go I un-fork?  :)

**Comment by doktordirk** [comment]
i ususally just edit the config.js

**Comment by CarlosOnline** [comment]
Sorry but I need some more explicit help.  I have no ideas what is wrong
and how to fix it.

What changes should I make to load the plugin?

**Comment by PWKad** [comment]
You have multiple forks this is not related to dialog but your setup in general.  `jspm update` to update all of your libraries, if you still have problems after that join our gitter and someone can help guide you.
