### ISSUE TITLE
dialog with composed body not centering vertically

### ISSUE THREAD

**Issue by dilvish4ever** [aurelia/dialog#145]
There is a problem with displaying dialog content when it composed into body
```javascript
...
        <ai-dialog-body>
            <compose view-model.bind="bodyViewModel" model.bind="bodyModel"></compose>
        </ai-dialog-body>
...
```
The modal opens centered vertically as if there is no content and expanded down with composed content.

**Comment by EisenbergEffect** [comment]
@jedd-ahyoung We will need to incorporate the new transactional composition mechanism into the dialog system in order to fix this. I can do it. Just let me know when all the PRs you are working on for dialog are done. I'll get those in and then I can turn around and make the change for this.

**Comment by jedd-ahyoung** [comment]
@EisenbergEffect They're actually done. I finished them on Wednesday.

2016-05-06 9:31 GMT-04:00 Rob Eisenberg <notifications@github.com>:

**Comment by EisenbergEffect** [comment]
Great. I saw some messages come through. (I get a lot.) So, been a busy week, and I wasn't sure if it was all wrapped. I'll get those in soon and then look into this issue. Did you also wrap up the route generation piece? I think I saw that come through too.

**Comment by jedd-ahyoung** [comment]
@EisenbergEffect Route generation is finished, yes. I intend to tackle the
dialog close issue PR next (as that should be low-hanging fruit, as it's
already been done) and then work on some of the outstanding router issues
(the ones that I couldn't solve before). Let me know if you want me to help
with merging the dialog PRs, as they will probably need heavy rebasing.

2016-05-06 10:40 GMT-04:00 Rob Eisenberg <notifications@github.com>:

**Comment by EisenbergEffect** [comment]
@jedd-ahyoung Do you have commit rights on the dialog repo? If so, would you mind merging those PRs in? I actually want more core team members to do some of the merging. If you are interested to take on the dialog library as a lead, you could manage those and then just tell me when you needed a release. That would help a lot. Let me know. @PWKad has been doing a lot of dialog work, but he's heavily involved in validation now, so it would be cool if you could take that off his plate.

**Comment by jedd-ahyoung** [comment]
@EisenbergEffect Yeah, I can do the merge - that's no problem. I thought
you wanted a second pair of eyes on it, so I held off. Sure, I'll act as
lead on the dialog library.

2016-05-06 10:48 GMT-04:00 Rob Eisenberg <notifications@github.com>:

**Comment by jedd-ahyoung** [comment]
@EisenbergEffect This is complete. Let me know if you'd like me to work with the transactional composition.

**Comment by EisenbergEffect** [comment]
If you'd like to give that a go, go ahead. You'll need to create a new transaction so that modals to interfere with non modals. Each modal should have it's own. If you aren't sure how to do it, I can take care of it. Let me know.
