### ISSUE TITLE
Use of multiple models

### ISSUE THREAD

**Issue by arnevdv** [aurelia/dialog#146]
Is it possible to use multiple models in your dialog controller? 
For example:

`this.dialogService.open({ viewModel: PictureSlide, model: [this.object1, this.object2]});`

**Comment by AdamWillden** [comment]
Yes, whatever you set for `model` will be the argument passed to the `activate` callback of the specified viewModel

Try it and see. I've passed simple strings before and I don't believe there are any 'rules' as to what you can pass.

**Comment by arnevdv** [comment]
Thanks, it works like this :)

Service:
```
openPictureSlide(index) {
        this.dialogService.open({ viewModel: PictureSlide, model: [this.object1, this.object2, index] });
    }
```

Controller:
```
activate(objects) {
        this.object1= objects[0];
        this.object2= objects[1];
        this.index= objects[2];
    }
```
