### ISSUE TITLE
Problem with @inject(Element)

### ISSUE THREAD

**Issue by jbellsey** [aurelia/dialog#15]
I'm having trouble using `@inject(Element)` to access the DOM inside my dialog. Perhaps this is because the view-model is created dynamically, outside the main framework? I need access to the `<input>` field inside the dialog, and the only way to get it seems to be with "old-fashioned" DOM access, `document.getElementById()`.

Thoughts? Am I doing something wrong here?

```javascript
@inject(Element)
export class MyDialog {
    constructor(element) {
        this.root = element;    // returns null
    }
}
```
```HTML
<template>
    <dialog>
        <dialog-header>...</dialog-header>
        <dialog-body>
                <input ...>
        </dialog-body>
        <dialog-footer>...</dialog-footer>
    </dialog>
</template>
```

**Comment by PWKad** [comment]
I think that's the case - but what are you expecting to be returned?  The `input` or the entire `dialog`?

**Comment by jbellsey** [comment]
I would have expected the injected `element` to be the root dialog, as with any other Aurelia  view. Normally I would want to call `querySelector()` on the wrapper DOM element, to access the other elements inside the dialog, like the `input`.

In this case, I have to resort to using an ID to retrieve any DOM elements in this view. This is not ideal, even though I can work around the limitation for now.

```HTML
<template>
    <dialog>
        <input id="my-input" ...>   <!-- gross -->
    </dialog>
</template>
```

```javascript
export class MyDialog {
    attach() {
        this.input = document.getElementById('my-input');
        // would rather get "this.root" in the constructor, as above, then: 
        // this.input = this.root.querySelector('input');  (or something like that)
    }
}
```

**Comment by EisenbergEffect** [comment]
We can fix this up. It's probably just an oversight.

**Comment by EisenbergEffect** [comment]
In this case, the dialog is inside your view. So, it can't be injected. However, you can use a `ref` binding to gain access to any element inside your view.
