### ISSUE TITLE
New dependency on ai-dialog element

### ISSUE THREAD

**Issue by timbell** [aurelia/dialog#158]
Since #141 there is a dependency on the existence of an `<ai-dialog>` element:

(DialogRenderer._createDialogHost)
`let dialogHost = modalContainer.querySelector('ai-dialog');`

I am using the dialog plugin with bootstrap-style modals and don't have ai-dialog elements in my components (my root element is `<div class="modal-dialog">`). To avoid the dependency, could this be changed to something like:

`let dialogHost = anchor.firstElementChild;`

Or will I need to add `<ai-dialog>` as the root in all my modals?

**Comment by jedd-ahyoung** [comment]
@timbell Yes. This is a bug. We've done a lot of refactoring of the dialog
plugin. The dialogHost in this instance should be the containing div, not
the ai-dialog element.

2016-05-27 5:45 GMT-04:00 timbell <notifications@github.com>:

**Comment by jkehler** [comment]
I'm being bitten by this bug. I want to use a Bootstrap style modal instead of the default aurelia-dialog style. Is there any workaround for this bug?
