### ISSUE TITLE
In IE, Dialog has transparent background

### ISSUE THREAD

**Issue by gregoryagu** [aurelia/dialog#16]
I don't know if this is the correct fix, but by adding "background: white" to the dialog css class, it resolved the issue.

This fix is not needed for Chrome.

**Comment by CharlesPockert** [comment]
Same for Firefox - transparent BG

**Comment by xjdesigns** [comment]
@gregoryagu @charlespockert ,
Aurelia dialog uses the html5 dialog element, which been dropped from the html5 spec. So your work around would need to be adding base rules for this element in your css. 

Chrome currently still uses the dialog element, see caniuse.com for the list of supported browsers.

**Comment by EisenbergEffect** [comment]
@PWKad We need to rename our element to `ai-dialog` so it does not conflict with the native element.
