### ISSUE TITLE
exception on double click 

### ISSUE THREAD

**Issue by Leonidnei** [aurelia/dialog#160]
We use aurelia-dialog and found that double click on OK button causes exception in Chrome:

DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

Stack trace points to the second line in the method:
      dialogController.destroyDialogHost = function () {
        body.removeChild(modalOverlay);
        body.removeChild(modalContainer);
        dialogController.slot.detached();
        return Promise.resolve();
      };
in dialog-renderer.js 

We tried on the latest version (0.6.2), the problem still happens.

**Comment by EisenbergEffect** [comment]
@jedd-ahyoung This should be a simple fix. Can you handle it this week?

**Comment by jedd-ahyoung** [comment]
@EisenbergEffect I'll take a look at this before Saturday.

**Comment by Leonidnei** [comment]
Any news with this?

**Comment by thomasnordlund** [comment]
I'm still seeing this error randomly when I call dialogController.cancel

```
DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```

**Comment by timfish** [comment]
We're seeing an exception like this in the latest RC:
![image](https://user-images.githubusercontent.com/1150298/34651136-5e51cc48-f3cc-11e7-9f39-c367961a21e8.png)
