### ISSUE TITLE
Dialog not centered when page is scrolled

### ISSUE THREAD

**Issue by krostkowski** [aurelia/dialog#163]
I think it's connected to #103 
When I have a page with a scroll and at the bottom there is a button showing dialog, dialogis rendered too low. I've attached the screen.
![dialog_bottom](https://cloud.githubusercontent.com/assets/19343142/15826347/7b0d8edc-2c07-11e6-812b-03ecac21114c.png)

**Comment by jedd-ahyoung** [comment]
@krostkowski In this situation, are you using a position function? If you are, your position function will override any of the default centering functionality of the dialog renderer.

**Comment by krostkowski** [comment]
Thank you Jedd. It turned out that there is an issue with asp.net core rc2:
http://stackoverflow.com/questions/37361375/strange-65279-character-after-upgrading-to-asp-net-core-rc2
