### ISSUE TITLE
Aurelia dialog doesn't work on skeleton-es2016

### ISSUE THREAD

**Issue by AlbertoPersano** [aurelia/dialog#165]
Hello,
I've tried this in two different projects, the second time indeed I tried this into the skeleton-es2016.
Once in the main.js under src folder I try to add:
" .plugin('aurelia-dialog');"

 to  :  aurelia.use
    .standardConfiguration()
    .developmentLogging()

When I try to execute the application I get this error:

![error-aurlei-dialog](https://cloud.githubusercontent.com/assets/15791392/15936367/0667d86a-2e6b-11e6-9b48-e32c1d5cc3ad.PNG)

**Comment by EisenbergEffect** [comment]
This seems like an issue related to jspm. The error you are receiving about the BindingLanguage usually results from having forks installed. Check your installation and make sure you don't have multiple copies of the same library.
