### ISSUE TITLE
Dialog has no height with 0.6.2

### ISSUE THREAD

**Issue by jrigsby** [aurelia/dialog#167]
I did a jspm update today and found the dialog no longer shows properly.  My dialogs are fairly straight forward and worked prior to recent jspm update.  I cannot say if something else on my screen is newly causing a problem but cannot imagine thats the case given how simple it is.

At present the dialog shows, locks the screen and shows a horizontal line indicating a box with no height. No controls show.  I didnt see any pending issues but am surprised no one else has reported this so suspect Im doing something wrong.  I checked documentation in several places and don't see anything jumping out at me.  Should this be working at this point or should I get from some different source?  

Ive removed a css class from the code below to reduce confusion.  I had one to adjust the default width but confirmed its not a cause of a problem before posting.  As is the code below might not look great without that width but it should show.  I am using bootstrap.sass but again all worked previously.  

"npm:aurelia-dialog@0.6.2": {
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.2.1.0",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.2.0.0",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.3.0",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.3.0.2"
    },

view
<template>
    <ai-dialog>
        <ai-dialog-header>
            <h2>Edit User</h2>
        </ai-dialog-header>
        <ai-dialog-body>
            <div class="row">
                <form role="form" class="sky-form">
                    <fieldset>
                            <section class="col-xs-12 col-sm-6">
                                <label class="label">First name</label>
                                <label class="input">
                                    <input type="text" attach-focus="true" class="form-control" value.bind="user.firstName" />
                                </label>
                            </section>
                            <section class="col-xs-12 col-sm-6">
                                <label class="label">Last name</label>
                                <label class="input">
                                    <input type="text" class="form-control" value.bind="user.lastName" />
                                </label>
                            </section>

                        <section class="col-xs-12">
                            <label class="label">Login id</label>
                            <label class="input">
                                <input type="text" class="form-control" value.bind="user.email" />
                            </label>
                        </section>
                        <section class="col-xs-12 col-sm-6">
                            <label class="sky-checkbox">
                                <input type="checkbox" value.bind="user.isLockedOut" checked.bind="user.isLockedOut">
                                <i></i>Account is locked
                            </label>
                        </section>
                        <section class="col-xs-12 col-sm-6">
                            <label class="sky-checkbox">
                                <input type="checkbox" value.bind="user.isDisabled" checked.bind="user.isDisabled">
                                <i></i>Account is disabled
                            </label>
                        </section>
                    </fieldset>
                </form>
            </div>
            
        </ai-dialog-body>

        <ai-dialog-footer>
            <button click.trigger="controller.cancel()">Cancel</button>
            <button click.trigger="controller.ok(user)">Ok</button>
        </ai-dialog-footer>
    </ai-dialog>
</template>

viewmodel

import {DialogController} from "aurelia-dialog";
import {User} from "./models";
import {inject} from "aurelia-framework";

@inject(DialogController)
export class EditUser {
    user: User;
    controller: DialogController;

    constructor(controller: DialogController) {
        this.controller = controller;
    }

    activate(user) {
        this.user = user;
    }
}

**Comment by EisenbergEffect** [comment]
Dialog hasn't been updated to match the new shadow dom slots yet. Those are rolling out today and tomorrow. You are literally updating "out of band" beta 2 and 3s that aren't finished updating yet. As we mentioned in the blog, as a warning to everyone, if you update this week, you do so at your own risk and must be prepared to deal with issues like this.

**Comment by jrigsby** [comment]
Im prepared for that.  If Im doing something wrong I apologize, but I was trying to get access to more up to date code so that I could start on validation which I knew was coming out this week (and failed to work with prior versions).  I assumed I should update everything to see where my code stood. I want to be able to see problems and report them so they dont slip through (in this case I assumed I had missed some change and was supposed to code it differently) but if there is a flag somewhere that says a particular project isnt to be reported on I would like to understand how it works. 

 Hopefully when its updated my prior code will go back to working.  Ill just tell my boss not to get latest from tfs and use what I had working.

**Comment by EisenbergEffect** [comment]
Dialog is one of the last libraries to be updated. It should be updated tomorrow. The best source of information is the official blog. We try to warn people when there are big changes happening like this.

If you want to make a quick fix on your end, go into the dialog plugins html files and replace the content elements with a single slot element. That should do it for you.

**Comment by maikelRA** [comment]
I have the same problem
