### ISSUE TITLE
If installed via jspm it does not include the typescript definition (d.ts) file

### ISSUE THREAD

**Issue by nexbit** [aurelia/dialog#169]
I don't know if it's the intended behaviour, but I usually expects that the d.ts file for a plugin is installed alongside the source files.
This is true for *almost* all the aurelia plugins (I just realized that `aurelia-binding` lacks the d.ts file too), but it is missing for `aurelia-dialog` (tested with 1.0.0-beta.1.0.0).

Is it possible to include it alongside the main dist files as other plugins do? I depend on that for a dynamic discovery script that configures my IDE automatically..

Thanks!

**Comment by EisenbergEffect** [comment]
Please read the blog post: http://blog.durandal.io/2016/06/10/where-did-my-typescript-go/

**Comment by nexbit** [comment]
From your post:

> Make sure you have the latest version of the typings tool installed.

but I'm affected by this bug, and I'm stuck with 0.8.x version of `typings` tool for the time being: https://github.com/typings/typings/issues/525

Can I use typings 0.8 with aurelia repos, or not?
And please consider adding this clarification in the original post (that bug is affecting several users, and especially typings authors). Thanks!

**Comment by EisenbergEffect** [comment]
Please see Microsoft's post from today on typing aquisition going forward: https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/

Our repos are now setup using the `typings` field which is the correct way to set up a package. You can use any typing acquisition tool that you want if you aren't using npm. Another solution is to just npm install the modules and set up your Ts config to use node module resolution.

**Comment by nexbit** [comment]
Oh well, missed that! I'll need to restructure my workflow for the third time this year.. What a lucky man I am! :-P

**Comment by EisenbergEffect** [comment]
Just think how fun it is for us...we have 40ish repositories and we not only needed to update structure but also build configurations....

**Comment by unional** [comment]
@EisenbergEffect Thanks for updating the typings! Seems like this https://github.com/aurelia/framework/issues/360 can now closed. 👍
