### ISSUE TITLE
Error installing with jspm

### ISSUE THREAD

**Issue by deliberaligiacomo** [aurelia/dialog#174]
I tried to install this plugin with jspm, but the installation doesn't work. Jspm gave me this error message:

`C:\code>jspm install aurelia-dialog

err  Registry node not found.

err  Unable to load registry node

warn Installation changes not saved.`

Could you help me? Thanks

**Comment by EisenbergEffect** [comment]
I've never seen such an issue. Please report it to the jspm project.
