### ISSUE TITLE
BindingLanguage must implement inspectTextContent()

### ISSUE THREAD

**Issue by Tim-Erwin** [aurelia/dialog#176]
With the rc-1.0.0 of aurelia and aurelia-dialog@1.0.0-beta.1.1.0 I'm getting the following error when I include aurelia-dialog:

> aurelia-templating.js:734 Uncaught (in promise) Error: BindingLanguage must implement inspectTextContent().

This has already been mentioned on gitter on May 22nd when aurelia was still in beta. So this might not be a problem with this specific constellation of versions but rather a general problem with versions not matching.

**Comment by EisenbergEffect** [comment]
Please run `jspm inspect --forks` and let me know if you have any forks. If you do, that's probably the problem.

**Comment by Tim-Erwin** [comment]
There are no forks, sth else was messed up, cannot say what it was. After manually pinning and resolving to the old versions to get my application running again, I just did a fresh install and it works with the latest versions now. Sorry for bothering you with this. Why's there no rc-1.0.0 for dialogs?

By the way, good to "see" you :) (I'm the "python guy" from the first workshop in London and pretty close to deliver my first Aurelia project.)

**Comment by EisenbergEffect** [comment]
Interesting. Glad it's working though :)
For the dialog, we still may need to make a few breaks there, which is why it isn't tagged as RC just yet.

**Comment by BringerOD** [comment]
I have the same issue and I do have forks.  Not sure what to do exactly.  

`     Installed Forks

                      npm:aurelia-binding 1.0.0-rc.1.0.2 1.0.0-rc.1.0.3
         npm:aurelia-dependency-injection 1.0.0-rc.1.0.0 1.0.0-rc.1.0.1
                      npm:aurelia-logging 1.0.0-rc.1.0.0 1.0.0-rc.1.0.1
                   npm:aurelia-templating 1.0.0-rc.1.0.0 1.0.0-rc.1.0.1

`

**Comment by EisenbergEffect** [comment]
See the jspm documentation on how to resolve forks. You'll need to resolve your forks to all the latests versions.

**Comment by BringerOD** [comment]
That worked thanks!

**Comment by lukelarsen** [comment]
@BringerOD How did you resolves these forks? I'm new to jspm and confused by it.

**Comment by vaskokj** [comment]
For anyone else looking to solve this do the following

run 

jspm inspect --forks

you should get a list of items that have forks.

then to resolve the fork like the following:

jspm resolve --only npm:aurelia-dependency-inject@1.1.0

At that point if you run jspm inspect --forks you should no longer see that fork in your tree.
