### ISSUE TITLE
dialogs do not show up if browser is in  element fullscreen mode.

### ISSUE THREAD

**Issue by Alexander-Taran** [aurelia/dialog#179]
Need to add configurability, where should dialog attach with a default of 'body'.
So one could configure dialog (on per launch base) where to attach to.

**Comment by PWKad** [comment]
Can you please submit a repro?

**Comment by PWKad** [comment]
To implement this enhancement it should be sufficient to have an optional parameter in the [options](https://github.com/aurelia/dialog/blob/master/src/dialog-options.js#L6) that is used inside of the [renderer](https://github.com/aurelia/dialog/blob/master/src/dialog-renderer.js#L78) that defaults to body but can be overridden by the consumer.  Also would need some tests to cover the new functionality.

**Comment by StrahilKazlachev** [comment]
The new `host` setting allows specifying the element to parent the dialog. Defaults to the `<body>`.
