### ISSUE TITLE
Parents of nested Dialogs no longer close after child has closed

### ISSUE THREAD

**Issue by jsobell** [aurelia/dialog#180]
Something in the last update appears to have broken the closing of nested dialogs.
If a child dialog is displayed and closed, the controller of the parent no longer closes the parent.
It appears that renderer.hideDialog is called, but the parent doesn't close, so I assume it's something in the renderer failing to remove the dialog from the DOM.

**Comment by EisenbergEffect** [comment]
@jedd-ahyoung We need to get on this quickly and put out a patch release. Looks like there are several regressions in that last update.

**Comment by simonfox** [comment]
@EisenbergEffect I've opened the above PR which fixes this issue.

**Comment by davismj** [comment]
I've reviewed the PR and even though circle ci reports a failed test, I've found that the test actually pass.

However, I'm not sure about this PR. Just from reading through the code, it seems that the `Renderer` was designed to be a singleton, not a transient, i.e. there was no mistake. Still, I see the value in making it a transient. 

Before we pull it in, I'd either like (a) @jedd-ahyoung to weigh in or (b) a sample gist / repo where I can reproduce the issue.

**Comment by simonfox** [comment]
@davismj see the message with commit 0fcd535 by @jedd-ahyoung the renderer was refactored to be used as transient. 

Happy to also provide a gist if you still want it?

**Comment by davismj** [comment]
Ah, on second look, I see what you're referring to. I'd still want @jedd-ahyoung to weigh in if possible, but it seems that this will likely be pulled in.

**Comment by simonfox** [comment]
OK cool thanks. This definitely fixes the issue for us.

**Comment by danhowitt** [comment]
@simonfox thanks for the fix. I've pulled this in to one of our projects to resolve the issue. Appears to work perfectly.
