### ISSUE TITLE
the README instructions for webpack don't work w/RC skeleton

### ISSUE THREAD

**Issue by ajoslin103** [aurelia/dialog#185]
I'm having trouble trying to figure out how to get aurelia-dialog working with esnext-webpack RC skeleton

Perhaps the README could be updated

**Comment by EisenbergEffect** [comment]
@niieani Ping.

**Comment by niieani** [comment]
`aurelia-dialog` works out-of-the-box (after installing) with both webpack skeletons, so I don't know what problems you are referring to. 
"having trouble" is hardly a good way to describe your issues, please be more specific @ajoslin103, preferably by filling in the new issue template.

**Comment by ajoslin103** [comment]
@niieani I do apologize for the rather vague complaint -- the problems seemed so obvious to me, as someone who got the aurelia-dialog working in the skeleton some months ago following these instructions, but many things have changed...

so..

using the latest esnext-webpack skeleton (as of 3 days ago) & following the How to install block

1. done:  npm install aurelia-dialog

2. couldn't do: in index.html - there is no element with the attribute aurelia-app to modify

3. half-done: add to main.js:      .plugin('aurelia-dialog')
(had to ignore the rest of the supplied sample as it doesn't match the RC main.js much at all)

NOTE: at this point npm restarts the app & the app fails w/console msg: app.bundle.js:30685 Uncaught (in promise) Error: Cannot find module './aurelia-dialog'.(…)

So I skip ahead to the webpack specific instructions

#1 config aurelia webpack plugin -- there is no longer any plugins section in the webpack.config.js file --I am unsure as to where to add the provided block.

#2 solving the dialog.css issue -- there are no loaders configured in the webpack.config.js file to modify -- I am unsure as to how to proceed

**Comment by niieani** [comment]
Ok, now it's clear :) We need to update the docs.
Please run: `npm install aurelia-dialog --save` and the error should go away.  No additional steps are necessary for Webpack with the latest versions.

**Comment by ajoslin103** [comment]
It worked!  Thanks for the quick turnaround!
