### ISSUE TITLE
No type information for DialogConfiguration.settings

### ISSUE THREAD

**Issue by glen-84** [aurelia/dialog#196]
**I'm submitting a feature request**

* **Library Version:**
1.0.0-beta.2.0.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.3.1

* **NPM Version:**
3.10.3

* **JSPM OR Webpack AND Version**
jspm 0.17.0-beta.22

* **Browser:**
all

* **Language:**
TypeScript 1.8.x

**Current behavior:**
No type information for `DialogConfiguration.settings`

**Expected/desired behavior:**
Type information for `DialogConfiguration.settings`

**Description:**
I want to set the `startingZIndex`, as shown in the README, as follows:

```ts
        .plugin("aurelia-dialog", (config: DialogConfiguration) => {
            config.useDefaults();
            config.settings.startingZIndex = 1005;
        });
```

This results in:

```
error TS2339: Property 'settings' does not exist on type 'DialogConfiguration'.
```

... which means that I have to remove the `DialogConfiguration` type.

**Comment by davismj** [comment]
@cmichaelgraham Right now, the object in question is just a pojo, found here: https://github.com/aurelia/dialog/blob/master/src/dialog-options.js

Is there some way to generate interfaces, or something similar, to cover this particular use case?

**Comment by glen-84** [comment]
Thanks @davismj, I guess that works for now. =)

**Comment by cmichaelgraham** [comment]
`any` works :smile:

or you can define an interface [like this](https://github.com/plotter/platform/blob/master/src/platform/state/state-session.ts#L25-L29)

```javascript
export interface StateSessionJSON {
    locked: boolean;
    uniqueId: string;
    activePaks: ActivePakJSON[];
}
```

**Comment by davismj** [comment]
@cmichaelgraham but this is esnext, not typescript

**Comment by cmichaelgraham** [comment]
@davismj - i think it is ok in esnext also
https://github.com/aurelia/fetch-client/blob/a6db0c7596a801a3369709203dcdc57f1f60dc8e/src/interfaces.js#L7

**Comment by EisenbergEffect** [comment]
It will work. The Babel transpiler uses Flow types which can handle it.

**Comment by davismj** [comment]
Okay, great. I tried making an interface but it generated something like  `export declare export declare interface`. I'll try dropping the `export` clause.
