### ISSUE TITLE
Unhandled rejection Error: DialogRenderer must implement getDialogContainer()

### ISSUE THREAD

**Issue by anthonyborell** [aurelia/dialog#201]
This ones an oldie but a goodie, seems like a lot of people are having problems with `Unhandled rejection Error: DialogRenderer must implement getDialogContainer().`
I've tried many potential fixes suggested here but none have seemed to work for me.

I'm using: aurelia-cli 0.13.0 to build, aurelia-dialog 1.0.0-beta.3.0.0 and typescript.

When clicking a button to call my openDialog function, `var host = dialogController.renderer.getDialogContainer();` dialogController.renderer is empty.

![image](https://cloud.githubusercontent.com/assets/4422171/17509474/6629a45a-5e5d-11e6-8464-40674313b745.png)

Upon further inspection, when I export my dialog class, everything inside DialogController is undefined.

![image](https://cloud.githubusercontent.com/assets/4422171/17509588/0dd101bc-5e5e-11e6-9747-43844111646e.png)

Thanks

**Comment by anthonyborell** [comment]
@EisenbergEffect any ideas?

**Comment by SamDeBlock** [comment]
@anthonyborell Did you register the plugin in the config method using `.plugin('aurelia-dialog'` ?

**Comment by anthonyborell** [comment]
Hey @SamDeBlock, in my main.ts I've got the following code. Let me know if I'm doing it wrong.

```
export function configure(aurelia: Aurelia) {
  aurelia.use
    .standardConfiguration()
    .feature('resources')
    .plugin('aurelia-dialog', config => {
      config.useDefaults();
      config.settings.lock = true;
      config.settings.centerHorizontalOnly = false;
      config.settings.startingZIndex = 5;
    });

  if (environment.debug) {
    aurelia.use.developmentLogging();
  }

  if (environment.testing) {
    aurelia.use.plugin('aurelia-testing');
  }

  aurelia.start().then(() => aurelia.setRoot());
}
```

**Comment by anthonyborell** [comment]
Alright, with a bit of digging I found out the issue... totally on my end. 

Basically the `<body>` element on my index.html file was `<body aurelia-app>` and not `<body aurelia-app="main">`. 

So my main.ts was never getting hit, thus the aurelia-dialog was never being loaded.
