### ISSUE TITLE
Typescript webpack skeleton error

### ISSUE THREAD

**Issue by enrico-padovani** [aurelia/dialog#203]
**I'm submitting a bug report**

* **Library Version:**
1.0.0

**Please tell us about your environment:**
* **Operating System:**
Windows 8.1

* **Node Version:**
6.4.0

* **NPM Version:**
3.10.6

* **JSPM OR Webpack AND Version**
webpack 2.1.0-beta.21

* **Browser:**
all
* **Language:**
TypeScript 2.0.0

**Current behavior:**
I'm using the latest skeleton and after installing by following the instructions, I've got this error: Unhandled rejection Error: Cannot find module './176.html'

attached chrome log file [localhost-1471881985721.zip](https://github.com/aurelia/dialog/files/430608/localhost-1471881985721.zip).

**Comment by PWKad** [comment]
I've downloaded your logs but it seems like you have a bigger issue - in your logs you have multiple deprecation warnings about trying to use invalid storage.  Can you show the relevant code for showing the dialog?  I don't think this is related to this plugin.

**Comment by enrico-padovani** [comment]
This is the code I'm using:

* ./shell/prompt.ts
```
import { autoinject } from 'aurelia-framework';
import { DialogController } from 'aurelia-dialog';

@autoinject
export class Prompt {

    message: string = null;

    constructor(private controller: DialogController) {
        this.controller = controller;

        controller.settings.lock = false;
        controller.settings.centerHorizontalOnly = true;
    }

    activate(message: string){
        this.message = message;
    }
}
```
* ./shell/prompt.html
```
<template>
  <ai-dialog>
    <ai-dialog-body>
      <h2>Generic dialog</h2>
      <span>${message}</span>
    </ai-dialog-body>
    <ai-dialog-footer>
      <button click.trigger="controller.cancel()">Cancel</button>
      <button click.trigger="controller.ok()">Ok</button>
    </ai-dialog-footer>
  </ai-dialog>
</template>
```
* ./home/test.ts
```
import { autoinject } from 'aurelia-framework';
import { DialogService } from 'aurelia-dialog';
import { Prompt } from '../shell/prompt';

@autoinject
export class Test {

  constructor(private dialogService: DialogService) { }

  openDialog() {
    this.dialogService.open({ viewModel: Prompt, model: 'Good or Bad?' }).then(response => {
      if (!response.wasCancelled) {
        console.log('good');
      } else {
        console.log('bad');
      }
      console.log(response.output);
    });
  }
}
```
* ./home/test.html
```
<template>
  <section class="au-animate">
    <button click.trigger="openDialog()">Open dialog</button>
  </section>
</template>
```
This is a screenshot of Chrome debugger (I'm using Chrome 52)
![error](https://cloud.githubusercontent.com/assets/7766472/17922725/db019bc8-69e0-11e6-8a42-38573ec81e09.png)
If you look at right the source of errors coming from aurelia-metadata.js and bluebird.js. Do you see some misusing in the code above?

Thanks!

**Comment by rajajhansi** [comment]
@PWKad, @enrico-padovani  - I face this same issue in a project built on top of the latest skeleton-navigation-typescript-webpack. The boostrap dialog was showing up for sometime and then it stopped working throwing the error:
"Unhandled rejection Error: Cannot find module './176.html'.
    at webpackContextResolve (http://localhost:9000/app.bundle.js:24427:9)
    at webpackContext "

**Comment by rajajhansi** [comment]
@PWKad , @enrico-padovani  - This seems to be a new issue in aurelia-dialog and the workaround given  by @mattbeckman in https://github.com/aurelia/dialog/issues/200 works! Instead of using the injected instance, just providing the path to the view model resolves this issue although it sucks!

**Comment by enrico-padovani** [comment]
I just tried again now after few days but now it works, changed nothing ... I'm a bit confused!

**Comment by enrico-padovani** [comment]
I moved dialog stuff into global resouces and loaded as feature. Maybe this was the reason why it worked.

**Comment by rajajhansi** [comment]
@enrico-padovani, I moved Prompt component into global resources and made it part of an existing feature. Then, I added the following code in my view model that launches Aurelia Dialog:
```
import {Prompt} from "./resources/components/prompt";
...
this.dialogService.open(
              {viewModel: Prompt, model: "You have unsaved changes. Are you sure you wish to leave?"}).then(response => {
      if (!response.wasCancelled) {
        console.log('stay');
      } else {
        console.log('leave');
      }
      console.log(response.output);
    });
```

It is working now :) I wish Aurelia has some mechanism for View models to avoid having to import {ViewModel} similar to what they have (global resources, features) for Views to avoid <require>.
