### ISSUE TITLE
ai-dialog-open class must be removed only when the last dialog closes.

### ISSUE THREAD

**Issue by ppn2** [aurelia/dialog#207]
**I'm submitting a bug report**

* **Library Version:**
1.0.1

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
4.4.6

* **NPM Version:**
3.10.6

* **JSPM OR Webpack AND Version**
requirejs 2.2.0, jspm 0.16.42

* **Browser:**
Chrome Version 52.0.2743.116 m
* **Language:**
TypeScript 1.8

**Current behavior:**
When a dialog opens, ai-dialog-open class is added to the body to hide the overflow. When dialog closes the ai-dialog-open is removed. However, if multiple dialogs are opened, the ai-dialog-open class should be removed only if the last dialog is opened. At this moment the class is removed as soon as first dialog is closed.

**Expected/desired behavior:**

if there are multiple dialogs, the ai-dialog-open class should be removed from the body tag, only if the last dialog is closed. Closing a dialog, while there are other dialogs underneath, should not remove the ai-dialog-open.

**Comment by CasiOo** [comment]
I opened an issue about the same here https://github.com/aurelia/dialog/issues/70
I still find it being a bug.

**Comment by ppn2** [comment]
hi, is there any progress on this?

**Comment by PWKad** [comment]
Fix should be going out Tuesday
