### ISSUE TITLE
openAndYieldController() doesn't resolve when dialog opens

### ISSUE THREAD

**Issue by aivins** [aurelia/dialog#208]
**I'm submitting a bug report**

* **Library Version:**
1.0.0-beta.3.0.0

**Please tell us about your environment:**
* **Operating System:**
OSX 10.11.6

* **Node Version:**
v4.2.4

* **NPM Version:**
2.14.12

* **JSPM OR Webpack AND Version**
JSPM 0.16.34

* **Browser:**
Chrome 53.0.2785.89 beta (64-bit)

* **Language:**
TypeScript 2.0.0

**Current behavior:**
Calling openAndYieldController() does not resolve when the dialog opens, or even when it is closed.

**Expected/desired behavior:**
Calling openAndYieldController() should resolve when the dialog opens as per the documentation. For me the first then() handler I attach never runs. No error is caught either.

**Comment by StrahilKazlachev** [comment]
Strange, it works for me. Can you share a sample?

**Comment by aivins** [comment]
@StrahilKazlachev sure - here's the Prompt class I'm using in its entirety.

```javascript
import {autoinject} from 'aurelia-framework';
import {DialogController} from 'aurelia-dialog';

@autoinject()
export class Prompt {
    params: any;

    constructor(private controller: DialogController) {
        this.controller.settings.lock = false;
        this.controller.settings.centerHorizontalOnly = true;
    }

    activate(params) {
        this.params = params;
    }
}
```

And here's the call I'm making from a ViewModel which has DialogService injected as this.dialog. The dialog *does* open, but never resolves. If I call controller.ok() on the DialogController injected into Prompt, the dialog closes. Even then openAndYieldController doesn't resolve.

```javascript
openDialog() {
  return this.dialog.openAndYieldController({ viewModel: Prompt, model: {message: 'Are you sure?'}})
    .then(response => {
      debugger;
     })
    .catch(error => {
       debugger;
     })
}
```

**Comment by StrahilKazlachev** [comment]
Ahh, so it does open. When it opens it should hit your `.then()` `debugger` statement. And what you call a `response` in TS it looks like this `DialogController & { result: Promise<DialogResult>}`. '.open' and `openAndYieldController` are used differently, check the docs, look for `Getting access to DialogController API outside`. If you do not need the controller where you open the dialog, just use `.open()`.

**Comment by aivins** [comment]
Thanks for looking at it, but I do need to get at the controller and that's what's not working. It never hits my debugger statement. Nothing I can do seems to be able to make that happen, which is why I'm concluding it isn't resolving at all. The docs make sense, it just doesn't behave as documented for me.

**Comment by StrahilKazlachev** [comment]
Did you try using `.open()`, just to see if you can get data when it closes?

**Comment by aivins** [comment]
Yeah .open() works fine for me. Using it heavily elsewhere in the project.

**Comment by aivins** [comment]
One clue is that when I call controller.ok() on the controller injected into Prompt, the dialog opened by openAndYieldController() does close. However the none of my debugger statements are ever reached.

**Comment by StrahilKazlachev** [comment]
There seems to be something going on with `.centerHorizontalOnly`, try commenting out `this.controller.settings.centerHorizontalOnly = true;`.

**Comment by aivins** [comment]
No difference I'm afraid. Thanks for looking. I'll get into the aurelia-dialog code tomorrow and see if I can track it down myself. Then I'll report back.

**Comment by StrahilKazlachev** [comment]
Ok, so the problematic Promise is the one returned from `DialogRenderer.showDialog`. I think this is tracked in #190.
As a workaround `settings.ignoreTransitions = true` can be used.

**Comment by pkozul** [comment]
Not sure if it's related to this issue, but I found that using IE9, I also needed to use:

`ignoreTransitions: true `

Without this, the then(response) continuation method would never get called after closing the dialog.

This was not occurring in IE10 and new versions though.

**Comment by aivins** [comment]
@StrahilKazlachev and @pkozul - after a good night's sleep I realised I wasn't running the server in --watch mode last night. My humble apologies for the run around!

@StrahilKazlachev you were right the first time - it's `settings.centerHorizontalOnly = true;` that causes this. `ignoreTransitions` doesn't appear make a difference.

That workaround is fine for me so my problem is solved. I'll leave it up to you whether to leave this open or not. Thanks again. You've saved me a lot of time.

**Comment by ggayowsky** [comment]
I am also encountering a similar issue.

openAndYieldController does not fall into the then(controller -> ...) block after the modal opens. It is only after I close the modal, that it falls into the then block

**Comment by EisenbergEffect** [comment]
Closing this since #190 is the real issue.
