### ISSUE TITLE
Pressing escape closes all the dialogs

### ISSUE THREAD

**Issue by VMBindraban** [aurelia/dialog#211]
**I'm submitting a bug report**

* **Library Version:**
1.0.0-beta.3.0.0

* **JSPM**
JSPM 0.16.15

* **Browser:**
Chrome 52 / Firefox 48

* **Language:**
ESNext

**Current behavior:**
Pressing escape closes all the dialogs

**Expected/desired behavior:**
Pressing escape should only close the top dialog.
https://github.com/aurelia/dialog/blob/master/src/dialog-renderer.js#L35

**Comment by EisenbergEffect** [comment]
@PWKad Can you take a look at this please?

**Comment by PWKad** [comment]
Was hoping to get some tests or an explanation from Jedd on what has been done since the code is a bit of a mess but I'll do my best to figure out what's going on here

**Comment by StrahilKazlachev** [comment]
@PWKad Actually I am working on this, but wanted to see how my other PR goes first.

**Comment by PWKad** [comment]
Fixed in #212
