### ISSUE TITLE
[ENHANCEMENT] Ability to close any open dialog upon route change.

### ISSUE THREAD

**Issue by don-bluelinegrid** [aurelia/dialog#214]
**I'm submitting a feature request**
- **Library Version:**
  1.0.0-beta.3.0.0

**Please tell us about your environment:**
- **Operating System:**
  OSX 10.5
- **Node Version:**
  4.4.7
- **NPM Version:**
  3.10.3
- **JSPM OR Webpack AND Version**
  webpack 2.1.0-beta.22
- **Browser:**
  all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView
- **Language:**
  TypeScript X.X 

**Expected/desired behavior:**
There is a common issue that occurs when showing modal elements (elements attached to the DOM programmatically, outside the context of a view template) in a SPA.  If the underlying view is changed via navigation, the modal element won't be hidden.

As an example, let's say I have an Aurelia application with various routes registered, and I have visited these routes:
/#/home
/#/main
/#/manage
While on the /#/manage, view, I show a modal dialog using aurelia-dialog, and then I use the browser 'back' button (or the Router navigation) to return to the /#/main view.  In this case, I will see the /#/main view, with the dialog from the /#/manage view still showing.

It would be desirable to have the dialogs dismissed by default on a router view change, or at least have an option for this behavior.  Without this, some messy code has to be inserted to listen for route changes, check to see if there is a visible dialog, and then dismiss it.

Don

**Comment by StrahilKazlachev** [comment]
I wouldn't say `messy`. The `dialog-service` has a `controllers: DialogController[]` property you can iterate and call `.cancel()` on every controller. Still there could be a utility method - `releaseAll()`, `closeAll()`, ... Would you format the issue according to the template to have it as a feature request?

**Comment by don-bluelinegrid** [comment]
Regardless of the subjective view of what constitues "messy" code, it is clear that the code to uniformly close any open dialogs on a route change would a) be an extremely common/desirable use case, and b) could be considered boilerplate code.

The value of a framework/library is to eliminate this sort of boilerplate code.  So, while it could certainly be helpful to have a utility function to close all open dialogs - it would be more useful to have an option to set a default behavior, to call such a function on a route change.

Don

**Comment by EisenbergEffect** [comment]
I understand the situation. Let's take it in phases. As @StrahilKazlachev suggests, why don't we start with a `closeAll()` method first. That will conquer the first level of tedium and it's a necessary foundation for the next level. Once we have that implemented, we can discuss how to hook this into the router in a way that doesn't cause undue coupling. @don-bluelinegrid Would you be interested in putting together a PR to add that feature? Or perhaps @StrahilKazlachev ?

**Comment by StrahilKazlachev** [comment]
@EisenbergEffect I don't mind.

**Comment by EisenbergEffect** [comment]
Go for it @StrahilKazlachev :)

**Comment by StrahilKazlachev** [comment]
`DialogService.prototype.closeAll()` is in `1.0.0-rc.1`.

**Comment by don-bluelinegrid** [comment]
Upgrading from 1.0.0-beta-3 to 1.0.0-rc.1 produces many typing errors:

```
[at-loader] Checking finished with 52 errors
[at-loader] node_modules/aurelia-dialog/dist/commonjs/dialog-settings.d.ts:13:33 
    TS2304: Cannot find name 'object'. 

[at-loader] node_modules/aurelia-dialog/dist/commonjs/dialog-settings.d.ts:14:9 
    TS2304: Cannot find name 'object'. 

[at-loader] src/lib/aurelia-easywizard/controller/wizard-controller.ts:37:53 
    TS2339: Property 'modelView' does not exist on type 'DialogSettings'. 

[at-loader] src/lib/aurelia-easywizard/controller/wizard-controller.ts:38:56 
    TS2339: Property 'modelPromise' does not exist on type 'DialogSettings'. 

[at-loader] src/lib/aurelia-easywizard/controller/wizard-controller.ts:39:49 
    TS2339: Property 'title' does not exist on type 'DialogSettings'. 

[at-loader] src/lib/aurelia-easywizard/controller/wizard-controller.ts:40:50 
    TS2339: Property 'okText' does not exist on type 'DialogSettings'. 

[at-loader] src/lib/aurelia-easywizard/controller/wizard-controller.ts:41:54 
    TS2339: Property 'showCancel' does not exist on type 'DialogSettings'. 

[at-loader] src/lib/aurelia-easywizard/controller/wizard-controller.ts:42:60 
    TS2339: Property 'isSubmitDisabled' does not exist on type 'DialogSettings'. 

[at-loader] src/lib/aurelia-easywizard/controller/wizard-controller.ts:42:111 
    TS2339: Property 'isSubmitDisabled' does not exist on type 'DialogSettings'. 

[at-loader] src/lib/aurelia-easywizard/controller/wizard-controller.ts:43:38 
    TS2339: Property 'isSubmitDisabled' does not exist on type 'DialogSettings'. 

[at-loader] src/lib/aurelia-easywizard/controller/wizard-controller.ts:44:48 
    TS2339: Property 'item' does not exist on type 'DialogSettings'. 

[at-loader] src/lib/aurelia-easywizard/controller/wizard-controller.ts:46:50 
    TS2339: Property 'rules' does not exist on type 'DialogSettings'. 

[at-loader] src/lib/aurelia-easywizard/controller/wizard-controller.ts:47:39 
    TS2339: Property 'rules' does not exist on type 'DialogSettings'. 

[at-loader] src/lib/aurelia-easywizard/controller/wizard-controller.ts:55:55 
    TS2339: Property 'steps' does not exist on type 'DialogSettings'. 

[at-loader] src/lib/aurelia-easywizard/controller/wizard-controller.ts:56:49 
    TS2339: Property 'steps' does not exist on type 'DialogSettings'. 

[at-loader] src/model/model.ts:34:47 
    TS2339: Property 'modelView' does not exist on type 'DialogSettings'. 

[at-loader] src/model/model.ts:35:50 
    TS2339: Property 'modelPromise' does not exist on type 'DialogSettings'. 

[at-loader] src/model/model.ts:36:43 
    TS2339: Property 'title' does not exist on type 'DialogSettings'. 

[at-loader] src/model/model.ts:37:50 
    TS2339: Property 'loadingTitle' does not exist on type 'DialogSettings'. 

[at-loader] src/model/model.ts:38:44 
    TS2339: Property 'okText' does not exist on type 'DialogSettings'. 

[at-loader] src/model/model.ts:39:48 
    TS2339: Property 'showCancel' does not exist on type 'DialogSettings'. 

[at-loader] src/model/model.ts:40:55 
    TS2339: Property 'showErrors' does not exist on type 'DialogSettings'. 

[at-loader] src/model/model.ts:40:105 
    TS2339: Property 'showErrors' does not exist on type 'DialogSettings'. 

[at-loader] src/model/model.ts:41:61 
    TS2339: Property 'isSubmitDisabled' does not exist on type 'DialogSettings'. 

[at-loader] src/model/model.ts:41:120 
    TS2339: Property 'isSubmitDisabled' does not exist on type 'DialogSettings'. 

[at-loader] src/model/model.ts:42:30 
    TS2339: Property 'isSubmitDisabled' does not exist on type 'DialogSettings'. 

[at-loader] src/model/model.ts:43:42 
    TS2339: Property 'item' does not exist on type 'DialogSettings'. 

[at-loader] src/model/model.ts:45:49 
    TS2339: Property 'gridOptions' does not exist on type 'DialogSettings'. 

[at-loader] src/model/model.ts:47:44 
    TS2339: Property 'rules' does not exist on type 'DialogSettings'. 

[at-loader] src/model/model.ts:48:33 
    TS2339: Property 'rules' does not exist on type 'DialogSettings'. 

[at-loader] src/model/model.ts:49:53 
    TS2339: Property 'rules' does not exist on type 'DialogSettings'. 

[at-loader] src/model/prompt.ts:24:47 
    TS2339: Property 'modelView' does not exist on type 'DialogSettings'. 

[at-loader] src/model/prompt.ts:25:50 
    TS2339: Property 'modelPromise' does not exist on type 'DialogSettings'. 

[at-loader] src/model/prompt.ts:26:50 
    TS2339: Property 'loadingTitle' does not exist on type 'DialogSettings'. 

[at-loader] src/model/prompt.ts:27:43 
    TS2339: Property 'title' does not exist on type 'DialogSettings'. 

[at-loader] src/model/prompt.ts:28:45 
    TS2339: Property 'message' does not exist on type 'DialogSettings'. 

[at-loader] src/model/prompt.ts:29:44 
    TS2339: Property 'okText' does not exist on type 'DialogSettings'. 

[at-loader] src/model/prompt.ts:30:48 
    TS2339: Property 'showCancel' does not exist on type 'DialogSettings'. 

[at-loader] src/model/prompt.ts:31:54 
    TS2339: Property 'isSubmitDisabled' does not exist on type 'DialogSettings'. 

[at-loader] src/model/prompt.ts:31:99 
    TS2339: Property 'isSubmitDisabled' does not exist on type 'DialogSettings'. 

[at-loader] src/model/prompt.ts:32:30 
    TS2339: Property 'isSubmitDisabled' does not exist on type 'DialogSettings'. 

[at-loader] src/model/prompt.ts:33:42 
    TS2339: Property 'item' does not exist on type 'DialogSettings'. 

[at-loader] src/model/prompt.ts:36:33 
    TS2339: Property 'rules' does not exist on type 'DialogSettings'. 

[at-loader] src/model/prompt.ts:37:53 
    TS2339: Property 'rules' does not exist on type 'DialogSettings'. 

[at-loader] src/model/prompt.ts:45:101 
    TS2339: Property 'rules' does not exist on type 'DialogSettings'. 

[at-loader] src/services/alertsService.ts:8:42 
    TS2305: Module '"/Users/donpeterkofsky/Documents/gc-2-dev/node_modules/aurelia-dialog/dist/commonjs/aurelia-dialog"' has no exported member 'DialogResult'. 

[at-loader] src/services/communityService.ts:8:42 
    TS2305: Module '"/Users/donpeterkofsky/Documents/gc-2-dev/node_modules/aurelia-dialog/dist/commonjs/aurelia-dialog"' has no exported member 'DialogResult'. 

[at-loader] src/services/dataService.ts:9:42 
    TS2305: Module '"/Users/donpeterkofsky/Documents/gc-2-dev/node_modules/aurelia-dialog/dist/commonjs/aurelia-dialog"' has no exported member 'DialogResult'. 

[at-loader] src/services/dataService.ts:386:35 
    TS2339: Property 'openAndYieldController' does not exist on type 'DialogService'. 

[at-loader] src/services/dataService.ts:413:35 
    TS2339: Property 'openAndYieldController' does not exist on type 'DialogService'. 

[at-loader] src/services/dataService.ts:426:35 
    TS2339: Property 'openAndYieldController' does not exist on type 'DialogService'. 

[at-loader] src/services/dataService.ts:443:35 
    TS2339: Property 'openAndYieldController' does not exist on type 'DialogService'. 
```
Please provide a readme/changelog that provides migration instructions.


Thanks,
Don

**Comment by StrahilKazlachev** [comment]
http://blog.aurelia.io/2017/04/27/aurelia-dialog-release-candidate/
https://github.com/aurelia/dialog/blob/master/doc/article/en-US/dialog-basics.md - still not published in the HUB
TS =>2.2

**Comment by don-bluelinegrid** [comment]
@StrahilKazlachev 

With all due respect, the reply is not really helping me.  I read through both of the links you provided, and those both appear to provide "Getting Started" information for implementation.  I don't see any information about migration from the previous version, and I saw no information about a specific version dependency for TypeScript.  

Where do we find the dependency information for the plugin?  (I am current on TS "2.1.6")

Also, does this mean that aurealia-dialog requires TS?  How does that work for Auerelia projects that don't use TS?

**Comment by don-bluelinegrid** [comment]
@StrahilKazlachev 

I followed some other advice about resolving the typescript errors in Aurelia, and that eliminated most of the typings errors.

However, now i am seeing errors specifically related to aurelia-dialog:

```

[at-loader] src/services/communityService.ts:8:42 
    TS2305: Module '"/Users/donpeterkofsky/Documents/gc-2-dev/node_modules/aurelia-dialog/dist/commonjs/aurelia-dialog"' has no exported member 'DialogResult'. 

[at-loader] src/services/dataService.ts:9:42 
    TS2305: Module '"/Users/donpeterkofsky/Documents/gc-2-dev/node_modules/aurelia-dialog/dist/commonjs/aurelia-dialog"' has no exported member 'DialogResult'. 

[at-loader] src/services/dataService.ts:386:35 
    TS2339: Property 'openAndYieldController' does not exist on type 'DialogService'. 

[at-loader] src/services/dataService.ts:413:35 
    TS2339: Property 'openAndYieldController' does not exist on type 'DialogService'. 

[at-loader] src/services/dataService.ts:426:35 
    TS2339: Property 'openAndYieldController' does not exist on type 'DialogService'. 

[at-loader] src/services/dataService.ts:443:35 
    TS2339: Property 'openAndYieldController' does not exist on type 'DialogService'. 

```

Are these related to breaking changes in aurelia-dialog rc-1?  Is there specific information about breaking changes and developer migration instructions?  I looked at your "breaking changes" document and it does mention the removal of ``openAndYieldController```, but it doesn't mention anything about removal of ```DialogResult```.

Thanks,
Don

**Comment by StrahilKazlachev** [comment]
Apologies for the lack of sufficient migration documentation. Regarding `class DailogResult` it is a slip on my part, it is removed. In the API is replaced by [interface DialogCloseResult](https://github.com/aurelia/dialog/blob/1.0.0-rc.1.0.1/src/dialog-result.ts#L20).
Also the usage of the dialog plugin does not require TS. The source was migrated to TS and is currently compiled with TS 2.2. The distribution is still js+d.ts.

**Comment by don-bluelinegrid** [comment]
@StrahilKazlachev 
Thanks for the reply.

This is still unclear to me about how to migrate my code that was using beta-3.  I have a lot of code that looks like this:

```
    this.dialogService.openAndYieldController({modelView:'model/communityModel.html', title:title, 
      loadingTitle: 'app.loading', item:community, okText:this.i18n.tr('button.save'), validationRules:vRules})
    .then((controller:any) => {
        // do things here that access the dialog's controller and associated ViewModel.
    }
```


The current implementation of ```dialogService.open()``` seems significantly different than this.  How exactly do I get access to DialogController after opening the dialog - or, is there a different pattern to use now?

Also, above you said DialogResult is replaced with DialogCloseResult, but in your blog link it shows DialogOpenResult.  Which do we use?

Thanks,
Don

**Comment by don-bluelinegrid** [comment]
@StrahilKazlachev 

Hi -

I am seeing other issues now, as I am trying to refactor.

1. First of all, I see that the DialogController is available in the Promise result object, but there is something wrong with the typings, because this is appearing as a plain native Object, not any DailogXXResult type.

2. Second, I see there is a not about removing "viewModel" from the controller because it was undocumented.  But, it is documented here as being used in the setting to create the controller:
https://github.com/aurelia/dialog/blob/1.0.0-beta.3.0.1/README.md
So, it seems reasonable to expect this to be available through the controller.  However, when I inspect the controller object, I am seeing this:
```
controller:DialogController
    controller:Controller
        behavior:HtmlBehaviorResource
        boundProperties:Array(0)
        container:Container
        elementEvents:null
        instruction:BehaviorInstruction
        isAttached:true
        isBound:true
        scope:View
        view:View
        viewModel:Model
```
So, it looks like the viewModel actually is not deprecated like your doc says, but is contained in some new `Controller` type object, inside the `DialogController` object.  What is this new `Controller`, and why do we have a data structure with colliding property names like `controller.controller`?

This is making it quite challenging to refactor existing aurelia-dialog code.

Don

**Comment by StrahilKazlachev** [comment]
`old` => `new`
`dialogService.openAndYieldController(...).then(controller => ...)` => `dialogService.open(...).then((result: DialogOpenResult | DialogCancelResult) => ...)` - resolves when the dialog opens/shows(**not** closed) with `DialogOpenResult`, or when `canActivate` returns/resolves to false - considered a cancellation, resolves with `DialogCancelResult`.

`dialogService.open(...).then((result: DialogResult) => ...)` => `dialogService.open(...).whenClosed((result: DialogCloseResult) => ...)` - resolves when the dialog gets closed.

From `DialogOpenResult` you can access the controller and the Promise that resolves when the dialog closes. Doing `dialogService.open(...).then(r => r.wasCancelled ? r : r.closeResult).then((r: DialogCloseResult) => ...)` is basically `dialogService.open(...).whenClosed((result: DialogCloseResult) => ...)`. So when you are finished with the controller you ca return the `closeResult` and chain.

**Comment by StrahilKazlachev** [comment]
`DialogController` - the `.viewModel`, `.view` and `.controller` were available directly on the `DialogController` instance. Since `controller: Controller`(from `aurelia-templating`) contained them it was unnecessary duplication.

**Comment by don-bluelinegrid** [comment]
OK, thanks. 
And what will be the `new` version of this?

```
controller.result.then((response) => {
        if (response.wasCancelled) {
          // Reset validation error state.
          this.logger.debug('Cancel');
        }
      })
```

**Comment by StrahilKazlachev** [comment]
The controller is no longer augmented. Use the `OpenDialogResult` `closeResult` property.

**Comment by EisenbergEffect** [comment]
We shipped an PI for this, so closing.
