### ISSUE TITLE
Property 'result' does not exist on type 'DialogController'.

### ISSUE THREAD

**Issue by don-bluelinegrid** [aurelia/dialog#216]
**I'm submitting a bug report**
- **Library Version:**
  major.minor.patch-pre1.0.3Beta

**Please tell us about your environment:**
- **Operating System:**
  OSX 10.6
- **Node Version:**
  4
- **NPM Version:**
  3.10
- **JSPM OR Webpack AND Version**
  webpack 2.1.0-beta.22
- **Browser:**
  all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView
- **Language:**
  TypeScript

**Current behavior:**

Webpack/Typescript build fails with this error:

```
Property 'result' does not exist on type 'DialogController'.
```

This error is generated by code copied from the example for "Getting access to DialogController API":

```
    this.dataService.openPromptDialog(this.i18n.tr('community.members.confirmDelete.title'),
      message,
      communityMembers, this.i18n.tr('button.delete'), 'modelPromise')
    .then((controller:any) => {
      controller.result.then((response) => {
        if (response.wasCancelled) {
          // Cancel.
          console.debug('Cancel');
        }
      })

```

In looking at the source code, there is no 'result' property that exists on the DialogController class.

**Expected/desired behavior:**

Documentation should describe how to use this functionality correctly.
Error should not occur when implementing code copied from example.
- **What is the expected behavior?**
- **What is the motivation / use case for changing the behavior?**

**Comment by EisenbergEffect** [comment]
@PWKad Can you take a look at this?

**Comment by StrahilKazlachev** [comment]
.result is not part of the DialogController interface. It is added to the controller instances returned by .openAndYieldController(settings: any): DialogController & { result: Promise<DialogResult> }

**Comment by don-bluelinegrid** [comment]
@StrahilKazlachev 

Yes, I saw that - this is the exact thing that I am reporting.

In the project code examples, it shows this:

```
      controller.result.then((response) => {
        if (response.wasCancelled) {
          // Cancel.
          console.debug('Cancel');
        }
      })
```

Since, as we see, the 'result' property is not a part of the DialogController interface - and is not declared in the typings - then in a typed language (i.e., TypeScript) the reference to 'result' is not permitted.

That seems like a bug - having an expectation to refer to a an undeclared property ('result') of a type ('DialogController').

Don

**Comment by StrahilKazlachev** [comment]
With the current typings generation mechanism we can not use union types. So either the DialogController interface has to change or add new one DialogControllerWithResult or something.

**Comment by PWKad** [comment]
In the `dialog-service.js` we are dynamically adding a result property to the controller that doesn't exist.  Should we return a union type or actually just add an class instance field on the `dialog-controller.js` with the proper type so the .d.ts is correct?

**Comment by StrahilKazlachev** [comment]
@PWKad Adding it to the `DialogController` is ok with me. As I get it the `Renderer` is the pluggable part and the controller instances are created by the `DialogService`, so extending the `DialoalogController` API with a new mandatory field should not result in a breaking change for anyone. I can add it with the `DialogSettings` definitions I'm working on.

**Comment by PWKad** [comment]
@StrahilKazlachev as I thought of this more perhaps adding `result` to the `DialogController` is more of a short-term fix.  In reality we probably need to massage the return type to return a controller instance and a result separately instead of tacking the result on to the controller for the sake of returning it.  Thoughts?

**Comment by StrahilKazlachev** [comment]
The latest release has this covered - `interface OpenDialogResult`.
