### ISSUE TITLE
Convert to src to TypeScript

### ISSUE THREAD

**Issue by PWKad** [aurelia/dialog#217]
Right now we have recognized a few issues in the build process such as missing the ability to support union types and some of the other ts2.0 new type features.  The build process also can be a bit tricky since there are so many moving parts.  With Aurelia-Validation I believe @jdanyow and @niieani have done a good job of showing that the plugin repo's can use TS in a nice, clean, and elegant fashion.

I'm proposing we convert over the existing codebase to use the TypeScript build and enforce typings a bit further.

Pros:

Easier build process
Easier to enforce typings are correct

Cons: 

Could be intimidating to ask for PRs if the developer isn't comfortable with TypeScript
Adds no real "features" to the repo.

@EisenbergEffect @StrahilKazlachev @cmichaelgraham and anyone else mentioned or who is interested feedback welcome.

**Comment by EisenbergEffect** [comment]
I'm ok with this but we need a full working build process. The Validation library is actually in TypeScript but it's kind of a pain because it's missing a lot of features that the build from our other libraries have. We need to get that library at 100% fidelity first and then we can use it as a template to move other libraries over.

**Comment by jdanyow** [comment]
https://github.com/aurelia/validation/issues/357

**Comment by EisenbergEffect** [comment]
Thanks!

**Comment by PWKad** [comment]
Agreed then that those issues need to be resolved first.  I'll comment there.

**Comment by PWKad** [comment]
Still waiting on a few last tasks before converting just giving an update

**Comment by PWKad** [comment]
@StrahilKazlachev I think we can safely start on this after the current PR's are accepted as all of the outstanding issues from validation are handled (except for one last task which has a PR that will be merged this week)

If you want to schedule a quick call some time over the next week or two to discuss current state and how we can do this whilst achieving the coveted v1 tag let me know!  Thanks again for all your contributions, they do not go unnoticed.

**Comment by PWKad** [comment]
For the initial implement -

1. Convert build.js task to use `gulp-typescript` instead of babel
2. Remove dts-generator
3. Make sure .d.ts is being generated / output
4. Make sure output matches current output structure

After that we can review tooling.

**Comment by niieani** [comment]
@PWKad I think it might be easier to just switch to the stack used by any of the Aurelia repos which already use TypeScript, and get rid of gulp dependencies.

**Comment by PWKad** [comment]
After converting over we will probably do that, trying to isolate to one major change at a time.

**Comment by StrahilKazlachev** [comment]
Done and released. Common build infrastructure is being discussed separately.
