### ISSUE TITLE
[feature] Ability to define custom renderer per-modal

### ISSUE THREAD

**Issue by vermilion** [aurelia/dialog#220]
**I'm submitting a feature request**
- **Library Version:**
  1.0.0-beta.3.0.0

**Please tell us about your environment:**
- **Operating System:**
  Windows 10
- **Node Version:**
  5.10.0
  
  
- **NPM Version:**
  3.10.7
  
  
- **JSPM OR Webpack AND Version**
  requirejs
  
  
- **Browser:**
  all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView
- **Language:**
  TypeScript 2.0.2
- **What is the expected behavior?**
  Currently i'm faced with the problem of defining:
  1 default renderer
  2 renderer for notifications (non-blocking and with different behavior)

Thought of having smth like this:
dialogService.useRenderer(NotifyCustomRenderer);
- **What is the motivation / use case for changing the behavior?**
  Ability to use differently styled and behaved modals - same as aurelia-validation

**Comment by StrahilKazlachev** [comment]
With `rc-1` we introduced the `childConainer` setting. You can provide a `Container`, preconfigured how to resolve `Renderer`, per `.open()` call.
