### ISSUE TITLE
.open() never resolves if canActivate() returns false

### ISSUE THREAD

**Issue by StrahilKazlachev** [aurelia/dialog#223]
**I'm submitting a bug report**
- **Library Version:**
  1.0.0-beta.3.0.1

**Please tell us about your environment:**
- **Operating System:**
  Windows [7|10]
- **Node Version:**
  6.2.0
- **NPM Version:**
  3.8.9
- **JSPM OR Webpack AND Version**
  JSPM 0.16.32
- **Browser:**
  all
- **Language:**
  all

**Current behavior:**
If the VM `.canActivate()` method returns `false` the whole part where `compositionEngine.compose()` and `renderer.showDialog()` is skipped. If you have called:
- `.open()` - the returned promise will never resolve.
- `.openAndYieldController()` - the returned promise will resolve with the controller, but the `.result` property added to the controller will never resolve.

**Expected/desired behavior:**
- **What is the expected behavior?**
  Since there is no retry mechanism if `.canActivate()` returns false that should be considered a cancellation. The caller of `.open()`/`openAndYieldController()` should be notified for the cancellation or inability to proceed, if returning `false` is not considered a (early) cancellation.

**Comment by mattbeckman** [comment]
I think I was bit by this bug today. I couldn't get the dialog promise to return after using controller.ok().

I bypassed by using a canDeactivate() method to do a delayed promise resolution:

`    canDeactivate() {
        return new Promise(function(resolve, reject) { 
            console.log("Called canDeactivate");
            window.setTimeout(
                function() {
                    resolve(true);
                }, 100);
        });
    }`

**Comment by davismj** [comment]
@pwkad Do we think the promise returned from `.open` should `reject` or `resolve(false)`?

**Comment by PWKad** [comment]
@davismj `reject` only if the developer asks for it specifically to keep a good dev experience

**Comment by StrahilKazlachev** [comment]
Closed #225.
