### ISSUE TITLE
bindable bug with object assignment

### ISSUE THREAD

**Issue by bcanzanella** [aurelia/dialog#226]
**I'm submitting a bug report**

* **Library Version:**
aurelia-dialog@1.0.0-beta.3.0.1

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.4.0

* **NPM Version:**
3.10.3

* **JSPM OR Webpack AND Version**
JSPM 0.16.44 

* **Browser:**
Chrome 53.0.2785.143 

* **Language:**
all | TypeScript 2.0

**Current behavior:**
if an object bound to the aurelia-dialog is updated via re-assignment (eg: from the parent view-model), the dialog's view is not updated.

https://gist.run/?id=b5c16b9948fdd03f6e56e827e222c84a

in the above gist, there is a ```setTimeout``` which re-assigns the ```@bindable``` model after 10 seconds.

steps:
- click the 'open dialog' button as soon as the page loads. 
- after 10 seconds, the "(app [inline]) inner data" will change  from 

`first inner`
`second inner`

to 

`replace 1`
`replace 2`

- the contents of the modal dialog will not update.

note: in the above gist, the version of aurelia-dialog is not the most up-to-date (@0.5.7), so i've also included a repo using the latest aurelia-dialog version (both the gist and repo below exhibit the same issue).

https://github.com/bcanzanella/aurelia-dialog-binding-issue

* **What is the expected behavior?**
the dialog's view is correctly updated, without having to close & re-open it.

* **What is the motivation / use case for changing the behavior?**
this kind of model updating seems to work with user-defined components, using ```<compose>```, and ```slot```ted views. I expect it to work across open modals too.

**Comment by davismj** [comment]
I'm not convinced this is a bug. Unlike the `<compose>` case, where the binding system would be listening for changes to the `outer` _property_, in this case you are simply passing in the _object_ itself. The `dialogService` has no reasonable way of knowing where it came from or when it changes.

**Comment by bcanzanella** [comment]
hmm, i'm confused... if i use ```Object.assign``` instead of ```=``` inside the ```setTimeout```, it works as i expected. i'm not sure if that is the expected behavior or not, but it seems as if something is getting lost using ```=``` instead of ```Object.assign``` .

updated gist: https://gist.run/?id=fbee5194ad988fa98e46261e7b61dcf9

in my use-case, i'd rather not use Object.assign as i'm doing more of a "merge" -- i'd rather replace the object.

**Comment by PWKad** [comment]
@bcanzanella You are changing the definition of the object instead of the properties that are referenced in the object.  This will never truly work the way you want it to by simply passing reference and then changing completely.

I think I see where you were going with outer and inner, your scenario above would work if you were just changing the value of inner and not outer, but passing outer all together.  You can see this here - https://gist.run/?id=b91df5edf408c688d7312c10366ecb81

This is not specific to dialog, it is how JavaScript and references work.
