### ISSUE TITLE
.ok() is not being resolved after set settings 'position' or 'centerHorizontalOnly'

### ISSUE THREAD

**Issue by lares83** [aurelia/dialog#228]
**I'm submitting a bug report**
- **Library Version:**
  major.minor.patch-pre

**Please tell us about your environment:**
- **Operating System:**
  Windows 10
- **Node Version:**
  7.0.0
  
  
- **NPM Version:**
  3.10.8
  
  
- **JSPM OR Webpack AND Version**
  webpack 2.1.0-beta.25
  
  
- **Browser:**
  all
- **Language:**
  ESNext

**Current behavior:**
In model where I inject DialogService, when I set  

```
controller.settings.position = (modalContainer) => {
     modalContainer.classList.add('some-class');
};
```

or

```
controller.settings.centerHorizontalOnly = true;
```

`ok()` promise is not being resolved.

I also noticed that in first example `.cancel()` callback is being resolved but in second it doesn't.
After I remove all those settings everything works fine.

**Expected/desired behavior:**
Promises are being resolved

**Comment by StrahilKazlachev** [comment]
@lares83 Could you try setting `ignoreTransitions: true`?

**Comment by lares83** [comment]
@StrahilKazlachev yes it helped, thanks :) In that case I'm closing this ticket.

**Comment by StrahilKazlachev** [comment]
@lares83 Ok, it's tracked here #190 if you want to keep an eye on it.
