### ISSUE TITLE
Add d.ts

### ISSUE THREAD

**Issue by gregoryagu** [aurelia/dialog#23]
There is currently no type definition file.

**Comment by hoangcuongvn** [comment]
I see the package aurelia-dialog does not have the .d.ts file, me too.

If generating the .d.ts file is not difficult, please add it into the package like other Aurelia packages. That will help us much.

**Comment by gregoryagu** [comment]
This is the absolute minimum until a real one is written.
```
declare module "aurelia-dialog" {
    export class DialogController {
        ok: any;       
        cancel(): void;
        settings: any;
    }
    export class DialogService {
        open(settings:any): any;
    }

}
```

**Comment by PWKad** [comment]
@gregoryagu Can you please check the new .d.ts file that's distributed for correctness based on your expertise?  I've added to the best of my knowledge.
