### ISSUE TITLE
Aurelia Dialog, cannot find ./118.html

### ISSUE THREAD

**Issue by jdemeuse1204** [aurelia/dialog#231]
**I'm submitting a bug report**

* **Library Version:**
1.0.0-beta.3.0.1

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.2.0

* **NPM Version:**
3.10.3

* **JSPM OR Webpack AND Version**
webpack 2.1.0-beta.22

* **Browser:**
Chrome 54

* **Language:**
ESNext

**Current behavior:**
When I attempt to open my Aurelia dialog I am getting the following message: **_Unhandled rejection Error: Cannot find module './117.html'._**  I attempted to create a gist, but aurelia-dialog is missing from the dependencies.  Instead, I included a link to my project below.  On my login page I wired up the submit button to pop open the dialog box, this is when the error is happening.  Login.js is referenced below.  This seems to be a bug unless I have something configured incorrectly.

NOTE:  The project I am using came from a clone of aurelia-esnext-webpack located in the skeletons repo.

Documentation Location: https://github.com/aurelia/dialog
Project Location: https://github.com/jdemeuse1204/Aurelia-Modal-Issue
Login.js Location: https://github.com/jdemeuse1204/Aurelia-Modal-Issue/blob/master/src/viewmodels/login.js
Login link: http://localhost:9000/#/Login

**Expected/desired behavior:**
Dialog should open with no errors.

* **What is the expected behavior?**
Just looking for the modal to open

* **What is the motivation / use case for changing the behavior?**
I can use bootstrap modals, but I would much rather use Aurelia dialog's instead :)

**Comment by StrahilKazlachev** [comment]
Not a problem with the dialog itself, check #213.

**Comment by jdemeuse1204** [comment]
I checked the #213 and got the modal to work. 

Code:  

```
// viewModal had to be change from Confirm (from import) to 'modals/confirm', please note any relative path will not work
// it must be an absolute path
  this.dialogService.open({ viewModel: 'modals/confirm', model: modalModel }).then(response => {
            debugger;
            if (!response.wasCancelled) {
                console.log('good - ', response.output);
            } else {
                console.log('bad');
            }
            console.log(response.output);
        });
```

I was using a relative path and that was not working, using the absolute path to the modal worked.  @StrahilKazlachev is there a webpack plugin or any configuration to fix this?

**Comment by StrahilKazlachev** [comment]
I'm not a webpack guy. Probably @niieani can point you to the appropriate resources.

**Comment by jdemeuse1204** [comment]
@niieani do you know or can you point me in the direction of anyone who would know of any webpack configuration changes or plugin's that would help with this issue?

**Comment by jdemeuse1204** [comment]
Closing this issue since its a bug with webpack.  Using the string path instead of the actual object from the import worked

**Comment by niieani** [comment]
@jdemeuse1204 not sure what's the cause. But with the new experimental webpack skeleton (soon to be released) the problem might not exist.

**Comment by jdemeuse1204** [comment]
Thank you @niieani, once it is released I can test it out and see if the issue still exists
