### ISSUE TITLE
Escape key does not close dialog

### ISSUE THREAD

**Issue by lstarky** [aurelia/dialog#234]
**I'm submitting a feature request**

* **Library Version:**
aurelia-dialog@1.0.0-beta.3.0.1

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.8.0

* **NPM Version:**
3.10.3

* **JSPM OR Webpack AND Version**
Not using either

* **Browser:**
Chrome 54.0.2840.71 m (64-bit)

* **Language:**
ESNext

**Current behavior:**
Escape key does not close dialog

**Expected/desired behavior:**

* **What is the expected behavior?**
Escape key should close dialog with .cancel()

* **What is the motivation / use case for changing the behavior?**
More compatible with Bootstrap modal dialog

**Comment by StrahilKazlachev** [comment]
Is `lock` set to `false` for the dialog you expect to close?

**Comment by lstarky** [comment]
I have not given it any specific settings regarding `lock`.  Here's my instantiation code:
```
this.dialogService.open({ viewModel: SettingsSchoolDivisionEdit, model: record }).then(response => {
  if (!response.wasCancelled) {
    console.log("Success");
  }
});
```

**Comment by StrahilKazlachev** [comment]
Try setting it to `false`, it defaults to `true`. You can do it either per dialog basis or when configuring the plugin.

**Comment by lstarky** [comment]
When I set `lock` to `false`, the Escape key works, but there are a couple negative side-effects: (1) clicking outside the window closes the window, (2) an extra X is added to the top-right corner of the header (but poorly placed).  Can I get the Escape key to work but still prevent clicking outside of the box and either improve the location of the X or skip it since I've already added my own?

On a side note, even when `lock` is set to `true`, the top navigation is still active (mouse-hover, mouse-click).  Is that intentional?  I would not have chosen that, since it does some weird things like allowing navigation in the "locked" background even while the modal form is static on front.

**Comment by StrahilKazlachev** [comment]
The handling of the ESC key and clicking outside the dialog is done in the `DialogRenderer`.  I think it would be possible to put thess in separate settings, any suggestions?
The X button is part of the `ai-dialog-header` custom element. If you ignore the button this is the header
```
<div class="dialog-header-content">
  <slot></slot>
</div>
```

**Comment by lstarky** [comment]
IMO it would be good to have separate settings, similar to what [Bootstrap Modals](http://getbootstrap.com/javascript/#modals) offers.

`backdrop` = true/false/static (default = true) Includes a modal-backdrop element. Alternatively, specify static for a backdrop which doesn't close the modal on click.
`keyboard` = true/false (default = true) Closes the modal when escape key is pressed

**Comment by lstarky** [comment]
I would also suggest the 50% opacity black background to be the default behavior.
