### ISSUE TITLE
Inline view slots (shadow dom) broken in IE11, Windows 8.1

### ISSUE THREAD

**Issue by rquast** [aurelia/dialog#235]
## I'm submitting a bug report

Aurelia Dialog 1.0.0-beta.3.0.1
Windows 8.1 (from https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/)
Internet Explorer 11
Node v7.1.0
npm 4.0.2
ESNext
webpack 2.1.0-beta.25 (current skeleton)

https://github.com/rquast/skeleton-navigation/tree/master/skeleton-esnext-webpack

** Changes made to skeleton to replicate behavior: **
https://github.com/aurelia/skeleton-navigation/compare/master...rquast:master

**Current Behavior:**

Broken with a replaceChild error. See attached screenshot.
![virtualbox_ie11 - win8 1_17_11_2016_13_16_30](https://cloud.githubusercontent.com/assets/1103891/20375157/0479eb74-acc9-11e6-874e-eb68b03023fb.png)

**Expected/desired behavior:**

Should load without error.

**What is the motivation / use case for changing the behavior?**

Aurelia (and Aurelia Dialog) should work in Internet Explorer 11.

**Comment by EisenbergEffect** [comment]
@jdanyow Have you seen this before? @niieani What about you. I suspect a configuration problem.

**Comment by niieani** [comment]
Hmm, might it be something with PAL being initialized _after_ aurelia-dialog is loaded, for some reason? I'll look into it. 

I'm so looking forward to ditching the old webpack-plugin, it's the reason for so many issues...

**Comment by niieani** [comment]
Hold on, I think I see where the problem _might be_. 

@rquast you are using `edit-person` as the ViewModel but it's not declared as a build resource in `package.json`. Can you try adding `edit-person` to `build.resources` there and see if this persists? (btw. this won't be necessary with the new set of plugins in the new skeleton)

**Comment by rquast** [comment]
I'll give it a go and let you know, but won't be able to for a few days since I'll be away. You could also try it yourself if you have the time to download the virtualbox of IE11 windows 8.

**Comment by niieani** [comment]
@rquast I'm pretty busy myself, but let me know when you're back. 👍

**Comment by PWKad** [comment]
Why is it `export async` in the main.ts?  I'm combing through just looking around but nothing stands out besides a few non-closed html elements.

**Comment by niieani** [comment]
@PWKad `export async` is correct since `configure` returns a Promise. It just allows you to `await` inside of the body of the method. You can see the Webpack skeletons utilizing this in a few places, including unit tests.

**Comment by rquast** [comment]
@PWKad I had this same problem in my own code, without that export async, or regenerator runtime. The code I did is just the skeleton merged with the sample code in Aurelia Dialog. @niieani I'll give those changes you suggested a go shortly.

**Comment by rquast** [comment]
@niieani adding edit-person to the build resources solved the problem.

```
  "aurelia": {
    "build": {
      "resources": [
        "edit-person"   
        ]
    }
  },
```
![virtualbox_ie11 - win8 1_21_11_2016_17_13_54](https://cloud.githubusercontent.com/assets/1103891/20473686/0b1e5d28-b00e-11e6-92d1-1ed5400b5ae0.png)

**Comment by rquast** [comment]
Closing as this will be fixed in the new webpack skeleton.
