### ISSUE TITLE
Promise dialogService.open() not always executed after calling dialogController.ok() 

### ISSUE THREAD

**Issue by VMBindraban** [aurelia/dialog#237]
**I'm submitting a bug report**

* **Library Version:**
1.0.0-beta.3.0.1

* **JSPM**
JSPM 0.16.15

* **Browser:**
Chrome 53

* **Language:**
ESNext

**Current behavior:**
`dialogController.ok()` doesn't always fire the Promise of `dialogService.open()`.
The `catch` isn't being called either.

Seems to be a issue with focus.

In `1.0.0-beta.3.0.0` it does however (expected behavior).

Example:
https://gist.run/?id=26d06cd22e6bda0e2c9430eb26de8040

**Comment by StrahilKazlachev** [comment]
The gist just stays on `Loading...` for me. From what you are saying I remember only one such scenario, if the VM has `canDeactivate()` and it returns `false`. If you don't have `canDeactivate` you could try passing `ignoreTransitions: true` to `dialogService.open`.

**Comment by VMBindraban** [comment]
Seems to be a issue with focus.

```js
function onTransitionEnd(e) {
  if (e.target !== renderer.modalContainer) {
    resolve();  // fix
    return;
  }
  ...
}
```

**Comment by StrahilKazlachev** [comment]
There is an issue about problems when the dialog does not have transitions set. In that case try `ignoreTransitions: true`;

**Comment by VMBindraban** [comment]
@StrahilKazlachev Thanks, that seems to "fix" it. I will close this.
