### ISSUE TITLE
Move docs to hub

### ISSUE THREAD

**Issue by PWKad** [aurelia/dialog#239]
Move docs and code samples to hub.  During transition leave the docs in the README.md until fully merged.

**Comment by stsje** [comment]
The docs in README seems to have been removed.
The hub docs don't work (it isn't loading). Has been a problem for weeks now.

Did you guys mean to remove the docs from the README already, or was it a mistake?

**Comment by StrahilKazlachev** [comment]
@stsje Removing the docs from the README is not a mistake. About the HUB, so far there hasn't been a dialog page. With the next release of the dialog that should be rectified(hope it's this week).

**Comment by stsje** [comment]
@StrahilKazlachev But you are linking to the hub docs in the README: http://aurelia.io/hub.html#/doc/article/aurelia/dialog/latest/dialog-basics

So we're supposed to view the history of README to find the docs?

**Comment by StrahilKazlachev** [comment]
@stsje No, you are not supposed to view the history, just it's taking a bit longer than anticipated to get the release. After the release the HUB page should be OK.

**Comment by stsje** [comment]
Can't you just rollback the README until the hub page is released?

The docs for the dialog plugin has been missing for quite a while now. I don't see how that can be acceptable when so many of us are using the plugin.

**Comment by StrahilKazlachev** [comment]
I can, but that will not help much. The release is scheduled for this week, right @EisenbergEffect? There are changes, new features, ... Those that are unable to upgrade to the RC will have to check an older version, by tag, ... - didn't think of that in the previous message.

**Comment by EisenbergEffect** [comment]
Yes, it's going out this week :)

**Comment by TGMorais** [comment]
Any ETA on this? 
The blog post was out yesterday, but the docs link is still [broken](http://aurelia.io/hub.html#/doc/article/aurelia/dialog/latest/dialog-basics), leaving aurelia-dialog rather undocumented.

**Comment by StrahilKazlachev** [comment]
@TGMorais Probably next week. The docs have been basically moved [here](https://github.com/aurelia/dialog/blob/master/doc/article/en-US/dialog-basics.md).

**Comment by StrahilKazlachev** [comment]
@PWKad Can we close this now?

**Comment by stsje** [comment]
Really nice. The new documentation is well written.
