### ISSUE TITLE
The way to not include default styles?

### ISSUE THREAD

**Issue by wegorich** [aurelia/dialog#244]
Hey I have the trouble with ai-dialog styles. 
The core issue:
- the styles are included in style tag with quite long query selectors like: `ai-dialog>ai-dialog-footer button:hover:enabled`, and it broke the markup we already have.
- it's quite hard to override it without !important tag, cause the styles are in style tag.
- not possible avoid loading styles.
- quite hard to customize dialogs markup, with custom theme, without deep overriding

**Comment by StrahilKazlachev** [comment]
If disabling them is an option for you you could call `.useCSS('')` when configuring the dialog.
Also if you could format your comment according to the issue template.

**Comment by ajoslin103** [comment]
please add useCSS() to the readme -- it took forever to find it by reading thru comments

**Comment by sebastien-roch** [comment]
Found out that it works like this now:

``` 
.plugin('aurelia-dialog', config => {
    config.useDefaults();
    config.cssText = '';
})
```
