### ISSUE TITLE
[*BUG*] Clicking Enter/Return closes Dialog

### ISSUE THREAD

**Issue by don-bluelinegrid** [aurelia/dialog#245]
**I'm submitting a bug report**

* **Library Version:**
1.0.0-beta.3.0.1

**Please tell us about your environment:**
* **Operating System:**
OSX 10.x|Linux (distro)|Windows [7|8|8.1|10]

* **Node Version:**
6.9.2

* **NPM Version:**
3.10.9

* **JSPM OR Webpack AND Version**
webpack 

* **Browser:**
all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Bro

* **Language:**
TypeScript X.X | ESNext

**Current behavior:**
When displaying an aurelia-dialog that contains an HTML form, clicking the Enter/Return key closes the dialog.  This is a change in behavior from prior versions of aurelia-dialog.  This breaks our application forms, which are designed to submit on Enter/Return.

**Expected/desired behavior:**
The aurelia-dialog should cancel/close on these events: clicking a Cancel button; clicking a close/OK button; clicking off the dialog (on the mask); clicking the Esc key.  The aurelia-dialog should *not* cancel/close on clicking the Enter/Return key.

* **What is the motivation / use case for changing the behavior?**
This breaks our application forms, which are designed to submit on Enter/Return.  Common expectation is that a form should be able to be submitted via click on Enter/Return key.  In addition, this is unexpected/undesirably changed behavior from prior versions.

**Comment by StrahilKazlachev** [comment]
I'll look into this but it will be faster with a sample.
This does sound a bit strange to me since at work we are using the dialog in and we don't have problems with the Return key, can't remember right now if there was something requiring the Enter key. Also there is just one `keypress` handler, for the Esc key.

**Comment by PWKad** [comment]
@don-bluelinegrid if you can fork this repo and add your sample to the `sample` application (instructions to run are in the readme) it should be easier than starting a repro from scratch.

**Comment by StrahilKazlachev** [comment]
Could not reproduce with `1.0.0-beta.3.0.0` nor `1.0.0-beta.3.0.1`, will wait for repro.
