### ISSUE TITLE
Possible bug on close dialog

### ISSUE THREAD

**Issue by filipegeraim** [aurelia/dialog#248]
**I'm submitting a bug report**
**I'm submitting a feature request**

* **Library Version:**
major.minor.patch-pre

**Please tell us about your environment:**
* **Operating System:**
OSX 10.x|Linux (distro)|Windows [7|8|8.1|10]

* **Node Version:**
6.2.0

* **NPM Version:**
3.8.9

* **JSPM OR Webpack AND Version**
JSPM 0.16.32 | webpack 2.1.0-beta.17

* **Browser:**
all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView

* **Language:**
all | TypeScript X.X | ESNext

**Current behavior:**
I need to display two dialogs in a given situation (one opening over the other). When closing the second the event "DialogResult" is not activated, however it is only activated when no dialog is active.

**Expected/desired behavior:**

* **What is the expected behavior?**
The expected behavior should be to trigger the "DialogResult" every time it is closed and not trigger all when all are disabled.

* **What is the motivation / use case for changing the behavior?**
Doing this you can control the individual result of each dialog at the exact moment that "ok ()" or "cancel ()"

**Comment by StrahilKazlachev** [comment]
Do you mean the promise does not resolve? Could you share a snippet, a runnable gist or something?
Try setting `ignoreTransitions: true` first.

**Comment by filipegeraim** [comment]
Now, when you close the dialogue, it triggers the promise, but it closes the first dialogue together.

I'll see if I can run in the gist, but maybe it will take some time.
I can explain a little of what I want to do.

1) Open a registration dialog;
2) Press the delete button;
3) Open a second confirmation dialog;
4) When you press the 'Yes' button, you should call the service to delete. With the option "ignoreTransitions = false" the pledge is not triggered, only when I close the registration dialog (it triggers both promises). If I put "ignoreTransitions = true" the prompt is triggered, but the registration dialog closes as well.

**Comment by StrahilKazlachev** [comment]
Sorry, the runnable gist will not do, it is out-of-date. You could fork the dialog repo and use the sample in it, then share it. One last setting to try before that `lock: true, ignoreTransitions: true`.

**Comment by filipegeraim** [comment]
Look, it worked fine by putting these two parameters in the settings. Can you explain why you put this on?

**Comment by StrahilKazlachev** [comment]
So `ignoreTransitions` is for a bug where the promise does not get resolved if the dialog does **not** have transitions - fix will be out in the next release. `lock` - currently this setting controls 3 things:
- `false`
  - ESC key cancels the dialog
  - clicking outside the dialog cancels it - I think that when you click on the second dialog this is triggered - not 100% sure.
  - the `x` button in the right top corner of `ai-dialog-header` is shown.
- `true`
  - ESC key does not trigger close
  - clicking outside does not trigger close
  - the `x` button is not shown

For me this is too much for a single setting so this is one of the things that we'll try to address for the next release.
