### ISSUE TITLE
[BUG] enableEscClose dont work when lock=true

### ISSUE THREAD

**Issue by zedL** [aurelia/dialog#250]
**I'm submitting a bug report**

* **Library Version:**
1.0.0-beta.3.0.1

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.4.0

* **NPM Version:**
4.0.3

* **Browser:**
Chrome

* **Language:**
TypeScript

**Current behavior:**
pressing escape dont close the dialog

**Expected/desired behavior:**
when I set lock and enableEscClose to true, the dialog should close when I press enter

``` 
 let aureliaDialogConfiguration = (config) => {
    config.useDefaults();
    config.settings.lock = true;
    config.settings.enableEscClose = true;
    config.settings.centerHorizontalOnly = false;
    config.settings.startingZIndex = 50;
  };

  aurelia.use
    .standardConfiguration()
    .feature('resources')
    .plugin('aurelia-mdl-plugin')
    .plugin('aurelia-validation')
    .plugin('aurelia-i18n', aureliaI18nConfiguration)
    .plugin('aurelia-dialog', aureliaDialogConfiguration);
```

**Comment by StrahilKazlachev** [comment]
I'm closing this since there is no `enableEscClose` setting  in 1.0.0-beta.3.0.1. It is still just in master. Also I don't follow what is role of the *enter* key here.

**Comment by zedL** [comment]
Why you close this issue?

From your own documentation:
enableEscClose allows pressings escape to close the modal without lock: false. (optional, defaults to true)
But this not works.

**Comment by StrahilKazlachev** [comment]
This "doc" is for the master - the latest. The version you have specified - *1.0.0-beta.3.0.1*, does not have/support that setting. To see the *readme* for a specific version select the tag for the version.
From the next release we will have the dialog API doc and articles in the hub.
