### ISSUE TITLE
Docs for yieldController out of date

### ISSUE THREAD

**Issue by stickfigure** [aurelia/dialog#251]
The README has instructions under "Getting access to DialogController API outside" that do not work. This doesn't actually yield and call the promise:

`this.dialogService.open({yieldController: true, viewModel: EditPerson, model: this.person}).then(`

From experimentation it looks like `openAndYieldController()` needs to be called instead.

**Comment by StrahilKazlachev** [comment]
You are looking at the "doc" in the master branch - the latest. From the branch menu select a tag for the appropriate version.
We are working on a new set of docs for the next release that will go in the hub.
