### ISSUE TITLE
Compatibility with new webpack build

### ISSUE THREAD

**Issue by jods4** [aurelia/dialog#254]
One goal of the new webpack build is that libs work out-of-the-box with zero config.
To achieve this goal a few small changes are required.
- [x] Be sure to wrap dynamically loaded modules into `PLATFORM.moduleName`, for example here: https://github.com/aurelia/dialog/blob/master/src/dialog-configuration.js#L9-L13
- [ ] @niieani mentionned that this lib encourages passing a VM loaded with a static `import` and then asking Aurelia to find a matching view, which requires hacky origin stuff. I have added support for that scenario in the webpack plugin, but we need to verify that it works.
- [ ] everything else should be fine, but running a few tests would be nice.

**Comment by no1melman** [comment]
What is the state on getting dialog to work with the current webpack implementation? Can it? What else do we have to do to get it to work?

**Comment by niieani** [comment]
@no1melman I didn't have the capacity to test this yet. If you do, feel free to let us know if everything works as it should, or if there are complications.
Thanks

**Comment by no1melman** [comment]
I didnt get it to work in the end, but that was like 2 weeks ago - I can't say i tried very hard...

**Comment by Vaccano** [comment]
@niieani Just an FYI, this does not work.  I get the following error:

**Unable to find module with ID: aurelia-dialog**

Here is the full stack trace:

>bundle.js:6086 Unhandled rejection Error: Unable to find module with ID: aurelia-dialog
    at WebpackLoader.<anonymous> (http://my-computer/my-app/bundle.js:35379:35)
    at step (http://my-computer/my-app/bundle.js:35228:23)
    at Object.next (http://my-computer/my-app/bundle.js:35209:53)
    at http://my-computer/my-app/bundle.js:35203:71
    at Promise._execute (http://my-computer/my-app/bundle.js:5512:9)
    at Promise._resolveFromExecutor (http://my-computer/my-app/bundle.js:7790:18)
    at new Promise (http://my-computer/my-app/bundle.js:7386:10)
    at 168.__awaiter (http://my-computer/my-app/bundle.js:35199:12)
    at WebpackLoader.168.WebpackLoader._import (http://my-computer/my-app/bundle.js:35344:16)
    at WebpackLoader.<anonymous> (http://my-computer/my-app/bundle.js:35444:44)
    at step (http://my-computer/my-app/bundle.js:35228:23)
    at Object.next (http://my-computer/my-app/bundle.js:35209:53)
    at http://my-computer/my-app/bundle.js:35203:71
    at Promise._execute (http://my-computer/my-app/bundle.js:5512:9)
    at Promise._resolveFromExecutor (http://my-computer/my-app/bundle.js:7790:18)
    at new Promise (http://my-computer/my-app/bundle.js:7386:10)

**Comment by Vaccano** [comment]
I was able to get it working using the ModuleDependencyPlugin:

Declare:

        const { AureliaPlugin, ModuleDependenciesPlugin } = require('aurelia-webpack-plugin');

Added to `plugins`

         new ModuleDependenciesPlugin({
            "aurelia-framework": [ 'aurelia-dialog' ],
            "aurelia-dialog": [ './ai-dialog', './ai-dialog-header', './ai-dialog-body', 
                                './ai-dialog-footer', './attach-focus' ]
        }),

**Comment by jods4** [comment]
@Vaccano 
The first part looks like you forgot to `moduleName` the plugin when you import it:
```js
.plugin(PLATFORM.moduleName('aurelia-dialog'))
```
The internal stuff has to be done inside the `aurelia-dialog` library itself.

**Comment by Vaccano** [comment]
@jods4 Do I need the `PLATFORM.moduleName` even if I am not doing any splits?

**Comment by Vaccano** [comment]
@jods4 You are right.  Adding in the `PLATFORM.moduleName` made the first part unneeded.

**Comment by heruan** [comment]
The `master` branch has support for the latest Webpack plugin (`PLATFORM.moduleName` and such). Any ETA for the next release?

**Comment by StrahilKazlachev** [comment]
@heruan Very soon.

**Comment by StrahilKazlachev** [comment]
Out in `1.0.0-rc.1`.

**Comment by jods4** [comment]
@StrahilKazlachev thanks!
I updated aurelia/pal#21 accordingly.

**Comment by jdemeuse1204** [comment]
@StrahilKazlachev Why was this closed?  I do not see this issue as resolved.  I am still getting `Unhandled rejection Error: Unable to find module with ID: aurelia-dialog`.  I have the latest skeleton as of two days ago.

**Comment by jdemeuse1204** [comment]
@StrahilKazlachev I am trying to load the dialog with options:

` .plugin(PLATFORM.moduleName('aurelia-dialog'), config => {
      config.useDefaults();
      config.settings.lock = true;
      config.settings.centerHorizontalOnly = false;
      config.settings.startingZIndex = 9999;
    })`

this does not work, however ` .plugin(PLATFORM.moduleName('aurelia-dialog'))` does work.  This should be a bug unless I am loading something incorrectly

**Comment by jods4** [comment]
@jdemeuse1204 
Something is confusing because the situation you describe can't really happen.

Having `PLATFORM.moduleName('aurelia-dialog')` in the file ensures inclusion by Webpack.
So if it works in the second case, there is no way the first case results in `Error: Unable to find module with ID: aurelia-dialog` at runtime.

Other things could go wrong but not that.

**Comment by jdemeuse1204** [comment]
@jods4 I am not sure how, but that is the case.  I can create a quick repo if you want to see it, or would you rather see a gist?

**Comment by jods4** [comment]
have you taken the debugging steps outlined in the wiki?
What is the problem in the first case: `aurelia-dialog` is _not_ in your bundle? Or is it there under an alternate name? Or is it correctly there?

**Comment by jdemeuse1204** [comment]
I have `aurelia-dialog` installed, and am trying to use it as a plugin but I cannot configure it.  I get this error referenced above.

`Unhandled rejection Error: Unable to find module with ID: aurelia-dialog`

**Comment by jods4** [comment]
Have a look at the output of webpack with `--display-modules` please and let me know if the module is really missing or if it has an incorrect ID.

https://github.com/aurelia/webpack-plugin/wiki/Debugging-missing-modules#cant-find-module-id-at-runtime

**Comment by jdemeuse1204** [comment]
@jods4  I was able to get it working by putting this in my `webpack.config`:

```
    new ModuleDependenciesPlugin({
      'aurelia-framework': [ 'aurelia-validation', 'aurelia-dialog', 'aurelia-validatejs' ]
    }),
```

And this in my `main.js` file

```
  aurelia.use
    .standardConfiguration()
    .developmentLogging()
    .plugin('aurelia-dialog', config => {
      config.useDefaults();
      config.settings.lock = true;
      config.settings.centerHorizontalOnly = false;
      config.settings.startingZIndex = 9999;
    })
    .plugin('aurelia-validation')
    .plugin('aurelia-validatejs');
```

**Comment by jods4** [comment]
Having `.plugin(PLATFORM.moduleName('aurelia-dialog'))` (same for the other two) in your `main.js` should have exactly the same effect as `ModuleDependenciesPlugin`.

**Comment by jdemeuse1204** [comment]
@jods4 That worked, thank you!

**Comment by radenkozec** [comment]
@jods4 @jdemeuse1204 For me it works only without config. 

`aurelia.use.plugin(PLATFORM.moduleName('aurelia-dialog'));`
As soon as I put additional settings via config like this:
```
 aurelia.use.plugin(PLATFORM.moduleName('aurelia-dialog', config => {
          config.useDefaults();
          config.settings.lock = false;
          config.settings.startingZIndex = 1050;
      }));

```
it does not work anymore. Error message is:

> Unable to find module with ID: aurelia-dialog
Do you have some suggestion?
