### ISSUE TITLE
Tabbing behind modal dialog

### ISSUE THREAD

**Issue by stuartbloom** [aurelia/dialog#256]
Hi there, I have a modal dialog that has a couple of anchors in the header and a button in the footer.

What I use the tab key, the anchors are not included in the tab order and the elements in the page that is under the overlay get focus.

Is there anything I am doing wrong?

Thanks

**Comment by jedd-ahyoung** [comment]
@stuartbloom Thanks for using the dialog plugin! No, you're not doing anything wrong. This is something that we're looking to support natively: https://github.com/aurelia/dialog/issues/1

**Comment by EisenbergEffect** [comment]
Closing as duplicate.

**Comment by stuartbloom** [comment]
@jedd-ahyoung thanks for the update.  Do you have any timeline?  if not, does the plugin have any callback that is called and can be used when the dialog is displayed/hidden?

Thanks again
