### ISSUE TITLE
Request for new release

### ISSUE THREAD

**Issue by larvanitis** [aurelia/dialog#258]
When can we expect a new release, please?

The latest (1.0.0-beta.3.0.1) has an issue when the dialogs `canActivate` returns false, which is fixed in dc44a34fdebfbf79129d4f4ac0c0f0009b0a2a64.

**Comment by StrahilKazlachev** [comment]
We are prepping a new big one for this month.

**Comment by larvanitis** [comment]
Thanks, I'll have to work around that issue until then.

**Comment by Vaccano** [comment]
The aurelia release did not have a new version of `aurelia-dialog`.  

Did I miss something or was the promise of a big release not intended for `aurelia-dialog` (even though the issue was asked on the dialog repository).
