### ISSUE TITLE
Support dialog integration in custom elements

### ISSUE THREAD

**Issue by StrahilKazlachev** [aurelia/dialog#260]
**I'm submitting a feature request**

* **Library Version:**
1.0.0-beta.3.0.1

**Please tell us about your environment:**
* **Operating System:**
all

* **Node Version:**
6.2.0

* **NPM Version:**
3.8.9

* **JSPM OR Webpack AND Version**
all

* **Browser:**
all

* **Language:**
all

**Current behavior:**
Can not make a dialog be part of a custom element - both DOM and DI hierarchy.
  1. the dialog has its Container created from the root Container
  2. can not specify where to append it in the DOM - always in the body #179

**Expected/desired behavior:**

* **What is the expected behavior?**
To be able to specify the dialog host element and provide a child container to use instead of creating new one from the root container. Allowing for a Container provision could also solve #220

* **What is the motivation / use case for changing the behavior?**
Lets say we have a complex value we want to provide an editor for(custom element). That editor has a simplified and advanced mode(requires a lot of screen estate). The advanced mode is shown in a dialog. I want to seamlessly integrate that dialog as part of the custom element both DOM and DI hierarchy.
The complex value may be recursive in terms of type - it may contain a value, as a property - direct or not, that is of the same complex type(linked list like).

**Comment by StrahilKazlachev** [comment]
@EisenbergEffect @PWKad What do you think?

**Comment by EisenbergEffect** [comment]
Yes, let's support this as long as we can fall back to a the root container and the body if they aren't provided.

**Comment by EisenbergEffect** [comment]
With all of the customizations, we need to make sure that the basic behavior remains as simple as always.
