### ISSUE TITLE
feat(dialog-controller): Add indication of user action in canDeactivate.

### ISSUE THREAD

**Issue by ydbondt** [aurelia/dialog#261]
**I'm submitting a feature request**

* **Library Version:**
1.0.0-rc-1

**Please tell us about your environment:**
* **Operating System:**
all

* **Node Version:**
6.2.0

* **NPM Version:**
3.8.9

* **JSPM OR Webpack AND Version**
JSPM 0.16.32

* **Browser:**
all

* **Language:**
all

**Current behavior:**
`canDeactivate` and `deactivate` function is called just before closing a dialog. However, it's not possible to see if the user has pressed OK, or just closed (or cancelled) the dialog. 

**Expected/desired behavior:**

* **What is the expected behavior?**
Both functions should have parameter of type `DialogCloseResult`.

* **What is the motivation / use case for changing the behavior?**
1. You need to know whether the close was cancel or not, and/or the output, in `.canDeactivate()`/`.deactivate()` of the dialog VM.
2. You have passed the `DialogController` to some other API and the close was triggered programmatically through the `DialogController` API.
If we go with this API extension it should:

* cover both `.canDeactivate()` and `.deactivate()`
* pass both the `wasCancelled` flag and the output - could reuse the `DialogCloseResult` interface
* the changes must be done against the `rc-1.0.0` branch

**Comment by EisenbergEffect** [comment]
You can return a result of any type from your custom dialogs.

**Comment by ydbondt** [comment]
How do you mean ?
I would like this to work transparently, without having to program any logic in the dialog.
The way I do this dirty check is to inject the function canDeactivate() in the dialog and do the check.
When canDeactivate is called, the controller doesn't know anything about the user interaction.

To give you more context. I wrote a custom attribute that I put on the form of the dialog. 
Here's a piece of code that I am using (partially from https://github.com/aurelia/templating-resources/issues/160#issuecomment-164277649):

```js

    bind() {
        this.bindings = this.view.bindings;
        let i = this.bindings.length;
        let self = this;
        while (i--) {
            let binding = this.bindings[i];
            binding.dirtyTrackedUpdateSource = binding.updateSource;
            binding.updateSource = function(newValue) {
                this.dirtyTrackedUpdateSource(newValue);
                let model = self.value;
                if (!model.canDeactivate) {
                    model.canDeactivate = function () {
                        // This always shows a prompt, even if the user pressed OK.
                        // Want to be able to check ok/cancel here.
                        return self.prompt.confirm({
                            title: "Unsaved Data",
                            message: "When you close this popup all data in the form will be lost.<br>Do you want to continue ?"
                        }).then((resp) => !resp.wasCancelled);
                    }
                }
            };
        }

    }

```

**Comment by ydbondt** [comment]
@EisenbergEffect Since I want to make something generic I can't just write the code in the dialog callback. Can you take a look at my previous comment please ?

**Comment by StrahilKazlachev** [comment]
OK, so here is a use case:
1. You need to know whether the close was *cancel* or not, and/or the output, in `.canDeactivate()`/`.deactivate()` of the dialog VM.
2. You have passed the `DialogController` to some other API and the close was triggered programmatically through the `DialogController` API.

If we go with this API extension it should:
* cover both `.canDeactivate()` and `.deactivate()`
* pass both the `wasCancelled` flag and the output - could reuse the `DialogCloseResult` interface
* the changes must be done against the `rc-1.0.0` branch

**Comment by StrahilKazlachev** [comment]
@EisenbergEffect @PWKad what do you think of the use case above ☝️?

**Comment by EisenbergEffect** [comment]
I'm fine to add something like this. However, instead of simply passing a boolean to the callback, we should pass an object with properties. This would allow it to match the same basic signature as what the router would do with these callbacks and it allows us to add other parameters in the future, if needed.

**Comment by ydbondt** [comment]
I'll change the PR.

**Comment by PWKad** [comment]
@StrahilKazlachev this is closed now correct?

**Comment by ydbondt** [comment]
Correct. Thnx !
