### ISSUE TITLE
Will not typescript compile with March release

### ISSUE THREAD

**Issue by Vaccano** [aurelia/dialog#267]
**I'm submitting a bug report**

* **Library Version:**
Aurelia-Dialog 1.0.0-beta.3.0.1 (latest via npm)
Aurelia-Templating 1.3.0 (latest via npm)

**Please tell us about your environment:**
* **Operating System:**
Windows 7

* **Node Version:**
6.10.1

* **NPM Version:**
4.4.4

**Webpack AND Version**
webpack 2.2.1

* **Browser:**
N/A - Typescript Compile Issue

* **Language:**
TypeScript 2.2

**Current behavior:**
When used with the latest (March) release has the following TypeScript compile errors: 

ERROR in C:\my-path\my-project\node_modules\aurelia-dialog\dist\aurelia-dialog.d.ts
(9,3): error TS2305: Module ''aurelia-templating'' has no exported member 'customAttribute'.

ERROR in C:\my-path\my-project\node_modules\aurelia-dialog\dist\aurelia-dialog.d.ts
(10,3): error TS2305: Module ''aurelia-templating'' has no exported member 'customElement'.

ERROR in C:\my-path\my-project\node_modules\aurelia-dialog\dist\aurelia-dialog.d.ts
(11,3): error TS2305: Module ''aurelia-templating'' has no exported member 'inlineView'.

ERROR in C:\my-path\my-project\node_modules\aurelia-dialog\dist\aurelia-dialog.d.ts
(12,3): error TS2305: Module ''aurelia-templating'' has no exported member 'bindable'.

ERROR in C:\my-path\my-project\node_modules\aurelia-dialog\dist\aurelia-dialog.d.ts
(13,3): error TS2305: Module ''aurelia-templating'' has no exported member 'CompositionEngine'.

ERROR in C:\my-path\my-project\node_modules\aurelia-dialog\dist\aurelia-dialog.d.ts
(14,3): error TS2305: Module ''aurelia-templating'' has no exported member 'ViewSlot'.

**Expected/desired behavior:**

No typescript errors on compilation using the latest march release. 

* **What is the expected behavior?**

No typescript errors on compilation using the latest march release.

* **What is the motivation / use case for changing the behavior?**

So that we can upgrade to the latest release and still use Aurelia-Dialog.

**Comment by StrahilKazlachev** [comment]
This is strange, you sure your project setup is OK? Only from the errors you've provided I would say the problem is in `aurelia-templating`. But [here](https://github.com/aurelia/templating/blob/fae7342220a6a8d8fafbef38e650b09dd43db172/dist/aurelia-templating.d.ts#L1178) is the exported `ViewSlot`(will not search for the other errors).

**Comment by Vaccano** [comment]
@StrahilKazlachev No, I am not sure.  I got rid of what I had and installed fresh compiled my code and got this error.  I am sure I have everything installed like I did before the upgrade, but if there is some new dependencies, I may be missing them.  (I have not updated Aurelia for some time.)

**Comment by StrahilKazlachev** [comment]
There are no new deps in the dialog.
If you import any of the above, lets say `customAttribute` or `customElement` **from** `aurelia-templating` in your code, do you get the same error?

**Comment by Vaccano** [comment]
@StrahilKazlachev Yep.  My bad.  For some reason that I cannot fathom, `aurelia-templating.d.ts` is not being found by the typescript compiler.  (It is clearly there on the disk in the `node_modules/aurelia-templating/dist` folder.)

I will close this issue since it is clearly not an issue with Aurelia Dialog.  Sorry for the confusion.
