### ISSUE TITLE
Bundling

### ISSUE THREAD

**Issue by Mordred** [aurelia/dialog#27]
Can you add `imports` to the `index.js` so that bundler will bundle all files? Currenlty only `index.js` is bundled and the rest is loaded on demand.

**Comment by EisenbergEffect** [comment]
This can be achieved by using our bundling library.

**Comment by Mordred** [comment]
@EisenbergEffect OK, maybe I have to be concrete:

![image](https://cloud.githubusercontent.com/assets/29232/9844626/f3002d24-5ac4-11e5-8445-0d555bcfaa98.png)

I'm using your bundling library.

**Comment by EisenbergEffect** [comment]
You need to update the bundle config to include those. See the way the existing bundle config is done and then just use a glob pattern for now. I will re-open this to add the export statements.
