### ISSUE TITLE
Documentation link in readme.md broken

### ISSUE THREAD

**Issue by tetious** [aurelia/dialog#278]
The link in the readme seems to lead to a bad URL on Aurelia Hub that just shows a loading spinner forever.

I tried poking around and using the search to find the correct link and was unsuccessful. Maybe it didn't get deployed?

Documentation content does seem to be in this repo... :)

**Comment by StrahilKazlachev** [comment]
The docs will be available in the hub with the next release, hopefully. The docs are in `./doc/article/**.*`.
