### ISSUE TITLE
Issue installing typings... status code (404)

### ISSUE THREAD

**Issue by bernatvadell** [aurelia/dialog#279]
Hi guys,
I've a bug when try install a typings.
When execute typings install github:aurelia/dialog displays on console the next message:

typings ERR! message Unable to read typings for "aurelia-dialog". You should check the entry paths in "typings.json" are up to date
typings ERR! caused by https://raw.githubusercontent.com/aurelia/dialog/master/dist/aurelia-dialog.d.ts/index.d.ts responded with 404, expected it to equal 200
typings ERR!
typings ERR! cwd C:\TFS\Architecture\Main\Internationalization\Intricom.Internationalization.Web\Intricom.Internationalization.Web
typings ERR! system Windows_NT 10.0.14393
typings ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\aalonso.CONTRIBUCIONS\\AppData\\Roaming\\npm\\node_modules\\typings\\dist\\bin.js" "inst
all" "github:aurelia/dialog"
typings ERR! node -v v7.8.0
typings ERR! typings -v 2.1.1
typings ERR!
typings ERR! If you need help, you may report this error at:
typings ERR!   <https://github.com/typings/typings/issues>

Any fix?

Ty

**Comment by StrahilKazlachev** [comment]
The `typings.json` has not been updated. The `typings` field in the `package.json` is OK.

**Comment by AdamWillden** [comment]
@StrahilKazlachev are you looking at this right now or do I need to create a local workaround (trying to perform a release of software and ran into this issue)

**Comment by AdamWillden** [comment]
See related PR which I guess should allow this to function again.

**Comment by bernatvadell** [comment]
@AdamWillden your changes have worked for me. @StrahilKazlachev can you merge to master?
