### ISSUE TITLE
Events on elements inside dialog are prevented (RC1)

### ISSUE THREAD

**Issue by RomkeVdMeulen** [aurelia/dialog#281]
**I'm submitting a bug report**

* **Library Version:**
1.0.0-rc.1

**Please tell us about your environment:**
* **Operating System:**
Linux (Ubuntu 16.04)

* **Node Version:**
6.10.2

* **NPM Version:**
3.10.10

* **JSPM OR Webpack AND Version**
JSPM 0.16.48

* **Browser:**
Chrome 58

* **Language:**
TypeScript 2.2.1

**Current behavior:**
Most interactive elements inside a dialog stopped working when I upgraded to RC1. I can't follow links, I can't check checkboxes or radios — neither by clicking or by keyboard navigation. Looking at the source code, I suspect the culprits to be the [keyboard](https://github.com/aurelia/dialog/blob/1.0.0-rc.1/src/dialog-renderer.ts#L64) and [click](https://github.com/aurelia/dialog/blob/1.0.0-rc.1/src/dialog-renderer.ts#L156) event listeners.

**Expected/desired behavior:**
Events should not be prevented from executing if they were triggered on interactive elements inside the dialog body.

**Reproduction**
1. Create new project
2. Add aurelia-dialog plugin
3. Create dialog VM and view with links, checkboxes, radios
4. Open dialog in browser and try to interact with these elements

**Comment by StrahilKazlachev** [comment]
I'll look into it when I get back from work. I do remember fixing something like this 😞

**Comment by StrahilKazlachev** [comment]
It's only the click handler, now I'm trying to find/remember why I did it like that.

**Comment by RomkeVdMeulen** [comment]
Not just the clickhandler: keyboard also doesn't work. It should be possible to tab to a checkbox and hit space to check it but that also doesn't work.

**Comment by StrahilKazlachev** [comment]
Tried exactly that, the `click` handler gets invoked. It's not hard to fix, I'm just trying to reason with the *beta* version of the handler.

**Comment by jrigsby** [comment]
I just updated and #284 is still a problem.  I looked at the code and see the changes in dialog-renderer.js, so the update got the latest.  When I open my dialog and press the type=file nothing happens.

**Comment by don-bluelinegrid** [comment]
+1 

I am experiencing the same problem described in #284; has broken several critical aspects of our application.

**Comment by AdamWillden** [comment]
Am I correct in thinking that the linked fix is not yet in a release? I have a form within a dialog which will not submit. Am I right to assume the behaviour is related to this bug?

**Comment by AdamWillden** [comment]
@EisenbergEffect it appears you perform the releases yourself. Is it possible to get this into a release ASAP, it's quite a critical bug.

**Comment by CD-UNCC** [comment]
New to this, how can I be informed when this path is live?

**Comment by AdamWillden** [comment]
Best bet is to keep an eye on the commits/releases, there's no automated method to get notified ...someone might be kind enough to ping a message on here to say when it's released!

**Comment by EisenbergEffect** [comment]
Released :)

**Comment by AdamWillden** [comment]
Just wanted to confirm that the fix worked for my use case :-) Thanks for the release.

**Comment by jmvtrinidad** [comment]
Still not working with the latest version(^1.0.0-rc.1.0.3).
Submit event is triggered when the input element is only one inside a form element, but with two input, submit event is not trigger.

Here's my template
``` html
<template>
  <ux-dialog style="width: 700px">
    <ux-dialog-header>
      <h2>Edit Employee Information</h2>
    </ux-dialog-header>
    <ux-dialog-body>
      <form role="form" ref="form" submit.delegate="saveEmployee(employee)">
        <input type="text">
        <input type="text">
      </form>
    </ux-dialog-body>
    <ux-dialog-footer>
      <div class="row">
        <div class="col-md-12">
          <div class="pull-right">
            <button class="btn btn-warning" click.trigger="controller.cancel()">Cancel</button>
            <button class="btn btn-primary" submit-form.bind="form">Save</button>
          </div>
        </div>
      </div>
    </ux-dialog-footer>
  </ux-dialog>
</template>
```

Any idea?
