### ISSUE TITLE
Dialog's no longer have borders or modals

### ISSUE THREAD

**Issue by dinkzilla** [aurelia/dialog#282]
I updated from 1.0.0-beta.3.0.1 to 1.0.0-rc.1 this morning and all of the dialogs in my project lost their container and modal. Switching back to the beta version immediately fixed issue, all other things in my project and environment remaining the same.

I don't have time today to look into what is happening or produce a repro demo unfortunately, but I wanted to get this out there since it doesn't appear to be listed yet.

I'll try to remember to come back with more info next week when my schedule loosens.

Screenshot of beta:
![dialog](https://cloud.githubusercontent.com/assets/5820014/25535438/0a29b354-2c05-11e7-9431-5a651b1498df.PNG)

Screenshot of rc:
![dialog-rc-broken](https://cloud.githubusercontent.com/assets/5820014/25535434/085584cc-2c05-11e7-8a11-f9241e15a41d.PNG)

**Comment by StrahilKazlachev** [comment]
Did you saw the breaking changes in naming for elements/css classes(`ai-` =>`ux-`)?

**Comment by RomkeVdMeulen** [comment]
See breaking changes in [release notes](http://blog.aurelia.io/2017/04/27/aurelia-dialog-release-candidate/)

**Comment by dinkzilla** [comment]
Makes sense, I had not seen those.
Are these breaking changes referenced somewhere on Github?

**Comment by StrahilKazlachev** [comment]
@dinkzilla Only in the [changelog](https://github.com/aurelia/dialog/blob/master/doc/CHANGELOG.md), but there isn't a *breaking change* marker. I'll leave this open if the naming change is not the case.

**Comment by dinkzilla** [comment]
Can you please add it to the changelog? Preferably note breaking changes there directly, but at least a link to that Aurelia Blog entry would have been super helpful.

**Comment by StrahilKazlachev** [comment]
@dinkzilla Will bring it up with the team.
