### ISSUE TITLE
input type=file no longer works after loading RC

### ISSUE THREAD

**Issue by jrigsby** [aurelia/dialog#284]
**I'm submitting a bug report**

* **Library Version:**
RC latest as of 4/28/2017

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
v7.7.2

* **NPM Version:**
4.1.2

* **JSPM OR Webpack AND Version**
JSPM 0.16.52

* **Browser:**
Chrome Version 57.0.2987.133 (64-bit)
also IE and Edge

* **Language:**
Typescript 2.1.5

**Current behavior:**
Prior to installing RC version I had a dialog with a input type=file that worked fine.  Now clicking the button shows nothing.  It may be opening behind things, I dont know, but I see nothing.  Ive updated all my html replacing ai- with ux-.  I also removed any styles used to customize the select files button to show the real one and that doest help either. In IE I can double click the input field and get it to show but edge and Chrome dont work at all and the Browse button itself doesnt work.

**Expected/desired behavior:**

* **What is the expected behavior?**
I expect the windows file dialog to popup to allow selecting files.

**Comment by StrahilKazlachev** [comment]
Tracked in #281

**Comment by don-bluelinegrid** [comment]
+1 

Experiencing the same problem; has broken several critical aspects of our application.
