### ISSUE TITLE
Forms no longer work within <ux-dialog-body> [submit.delegate] broken

### ISSUE THREAD

**Issue by CD-UNCC** [aurelia/dialog#289]
**I'm submitting a bug report**

* **Library Version:**
aurelia-dialog@1.0.0-rc.1.0.2

**Please tell us about your environment:**
* **Operating System:**
Win 10 x64

* **Node Version:**
6.2.0

* **NPM Version:**
3.10.10

* **JSPM OR Webpack AND Version**
using aurelia-cli

* **Browser:**
Chrome latest

* **Language:**
ESNext

**Current behavior:**
Putting a form in an aurelia-dialog modal and tying submit.delegate to controller.ok() does nothing. Not only does controller.ok() not fire, no event tied to submit.delegate will fire.

**Expected/desired behavior:**

I cant make a gist of it not working because the gist is using the old non RC version of aurelia dialog so it will work. Here is a gist of it working: https://gist.run/?id=5abaa0a16e8ee3c01efed8f99a4c0d20
`foo()` should be replaceable with controller.ok()
```
  <ux-dialog>
    <ux-dialog-body>
    <form role = "form" submit.delegate = "controller.ok()">
      <button type = "submit">Signup</button>
       </form>
    </ux-dialog-body>
  </ux-dialog>
```
This will not work. it used to.
* **What is the expected behavior?**

for a form to be placed in a modal and submit.delegate to be linkable to any controller or viewmodel method. 
* **What is the motivation / use case for changing the behavior?**

**Comment by StrahilKazlachev** [comment]
#281

**Comment by EisenbergEffect** [comment]
Released :)

**Comment by CD-UNCC** [comment]
@EisenbergEffect You are a glorious human being. Thank you
