### ISSUE TITLE
Problem using dialogue using skeleton-navigation-0.18.1

### ISSUE THREAD

**Issue by mrpink76** [aurelia/dialog#29]
* Downloaded the skeleton-navigation-0.18.1 source

* Ran the following commands
npm install
jspm install -y
gulp watch

The Skeleton app was working fine

* Modified the welcome.js as follows:

import {inject} from 'aurelia-framework';
import {DialogService, Prompt} from 'aurelia-dialog';

@inject(DialogService)
export class Welcome{
// ...
  constructor(dialogService){
      this.dialogService = dialogService;
  }
// ...
  submit(){
      this.dialogService.open({ viewModel: Prompt, model: 'Good or Bad?'}).then(() => {
          console.log('good');
        }).catch(() => {
      console.log('bad');
        });
  }

// ...
// END OF FILE

* Installed the added dependecy
jspm install aurelia-dialog

* When I click the submit button I get the following error in the console:
Unhandled promise rejection Error: Error instantiating configure. Check the inner error for details.(…)

Regards,
Petter

**Comment by PWKad** [comment]
Hello - could you please give some more info?  We have removed prompt from the exports as it is only a sample file but you can use it to construct your own application specific version.  If you are still having issues please come back and let me know or drop by our official gitter - http://gitter.im/aurelia/discuss
