### ISSUE TITLE
Promise resolves immediately after opening a dialog

### ISSUE THREAD

**Issue by RobertHerhold** [aurelia/dialog#290]
**I'm submitting a bug report**
* **Library Version:**
1.0.0-rc.1.0.2

**Please tell us about your environment:**
* **Operating System:**
OSX 10.12.4

* **Node Version:**
7.6.0

* **NPM Version:**
4.1.2

* **JSPM OR Webpack AND Version**
webpack 1.13.2

* **Browser:**
Chrome 57.0.2987.133

* **Language:**
ESNext

**Current behavior:**

Promise returned from `dialogService.open` resolves immediately after opening the dialog, although the dialog stays open. It works fine in `1.0.0-beta.3.0.1`, which I was using before.

**Expected/desired behavior:**

The Promise should only resolve after doing `controller.ok()` or `controller.cancel()`

**Comment by CD-UNCC** [comment]
you can no longer use `open().then()` you must use `open().whenClosed((response)=>{/*logic*/})`

**Comment by RobertHerhold** [comment]
@CD-UNCC Thanks, that works. What's the benefit of using `whenClosed` instead of just a standard Promise?

**Comment by CD-UNCC** [comment]
@RobertHerhold not sure. probably had something to do with being able to configure aurelia-dialog to break the promise chain with an error upon cancel now if the user wanted to. This version has brought lots of changes. I have an issue open at the moment where forms no longer work in modals. If you check the docs page on the git readme, however, its up to date if you have further inquires.

**Comment by RobertHerhold** [comment]
👍 Thanks

**Comment by niemyjski** [comment]
I'm also hitting this behavior? It seems really odd that the returned type has promise in the name but I can't await it.... Is this a bug? The samples should reflect async and await too, this isn't very idiomatic.
