### ISSUE TITLE
Close button (x) should automatically appear when dialogController.settings.lock = true

### ISSUE THREAD

**Issue by salminio** [aurelia/dialog#292]
**I'm submitting a bug report**

* **Library Version:**
"aurelia-dialog": "1.0.0-beta.3.0.1",

**Please tell us about your environment:**
* **Operating System:**
Windows 7 (although it's true for others I've tested on)

* **Node Version:**
v7.7.4

* **NPM Version:**
npm info using npm@4.1.2
npm info using node@v7.7.4
npm info ok
3.8.6

* **JSPM OR Webpack AND Version**
aurelia-cli (AMD)

* **Browser:**
all

* **Language:**
ESNext

**Current behavior:**
When dialogController.settings.lock = true - meaning the user cannot click outside the dialog to dismiss - so it's more like a dialog and not a popover - the upper right hand corner close (x) button does not appear. However if you set dialogController.settings.lock = false it does appear. Seems backwards to me... In the latter case I can just click outside the dialog to make it go away - no need for the X. Seems like it should appear when the user has no ability to dismiss the dialog by default. Or at the least it should probably be a setting as to when it does and does not appear.

**Expected/desired behavior:**
The 'X' close button should probably be an option/setting to show.

**Comment by JSeligsohn** [comment]
According to [this](http://blog.aurelia.io/2017/04/27/aurelia-dialog-release-candidate/) blog post, announcing the updated version - 1.0.0-rc.1.0.3 there is a bindable property `showCloseButton`. 
Add it to the `<ux-dialog-header>` tag like this:
`<ux-dialog-header showCloseButton.bind="false">`

**Comment by StrahilKazlachev** [comment]
Working as intended.
We acknowledged that the `lock` is too involved, that's why we introduced the `keyboard` and `overlayDismiss` settings as well as the bindable property `show-close-button`, as @JSeligsohn mentioned. `lock` is still present since we wanted to keep the breaking changes at minimum. It is used to init settings that were not set, keeping the beta version behavior.
