### ISSUE TITLE
Dialog is 100% transparent when upgrading to RC dialog

### ISSUE THREAD

**Issue by radenkozec** [aurelia/dialog#296]
**I'm submitting a bug report**

* **Library Version:**
npm:aurelia-dialog@1.0.0-rc.1.0.2 and rc.1.0.3

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.2.0

* **NPM Version:**
3.8.9

* **JSPM OR Webpack AND Version**
JSPM 0.16.32

* **Browser:**
 Chrome 

* **Language:**
ESNext

**Current behavior:**

**Expected/desired behavior:**
When upgraded from Beta Dialog to RC dialog all dialog views are now 100% transparent.
When I revert to Beta dialog aurela-dialog@1.0.0-beta.3.0.1 everything works. 
There is some problem with opacity.

**Comment by StrahilKazlachev** [comment]
Did you update the custom elements names accordingly(`ai-` => `ux-`)? Also if you have custom styles you'll have to update all places where you have `ai-`.

**Comment by radenkozec** [comment]
So @StrahilKazlachev this is breaking change? I need in all my custom elements update:
 <ai-dialog>
        <ai-dialog-body>
<ai-dialog-footer

to appropriate ux variants such as ux-dialog right?

Did not noticed this is breaking change sorry. I will close this ticket now.
