### ISSUE TITLE
Example code still using the old html tags

### ISSUE THREAD

**Issue by dkent600** [aurelia/dialog#297]
**I'm submitting a bug report**

* **Library Version:**
1.0.0-rc.1.0.3

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
v6.10.3

* **NPM Version:**
5.0.0

* **JSPM OR Webpack AND Version**
webpack 2.5.1

* **Browser:**
All

* TypeScript 2.3

**Current behavior:**
`prompt.html` in the shipped doc\example folder is still using old `ai` instead of the new `ux` tags.

I haven't checked whether there are other similar issues with the rest of the code in that folder.

**Expected/desired behavior:**
example code should be up-to-date

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**
The Aurelia docs for `Aurelia-dialog` uses the `Prompt` view as an example, but it seems likely that it won't work.

**Comment by chabou-san** [comment]
I'm coming here a little too late, but you missed a replacement `ai` -> `ux` on line 3 on the closing tag of the dialog-header. :)
