### ISSUE TITLE
Allow user to override the standard templates with their own templates

### ISSUE THREAD

**Issue by PWKad** [aurelia/dialog#3]
This is to allow extending the template much easier.

**Comment by EisenbergEffect** [comment]
I think we can do this by creating a custom view strategy. Let's call it a ConfigurableViewStrategy. By default it will use the provided view, but it can also tie into some plugin configuration that lets the end developer provide an alternate html path to load. We could even add this view strategy to the framework core if you think it makes sense.

**Comment by PWKad** [comment]
I thought about this more and it's actually not even needed - the developer simply uses their own custom elements instead of the default `ai-` ones when creating a modal - 

```html
<template>
  <my-custom-dialog>
    <my-custom-dialog>
      <form submit.trigger="controller.ok(answer)">
        <input type="text" value.bind="answer" style="width: 100%; line-height: 16px; font-size: 16px" attach-focus>
      </form>
    </my-custom-body>
  </my-custom-dialog>
</template>
```
