### ISSUE TITLE
keyboard set to Escape closes on Enter

### ISSUE THREAD

**Issue by dkent600** [aurelia/dialog#303]
**I'm submitting a bug report**

* **Library Version:**
1.0.0-rc.1.0.3

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
v8.1.2

* **NPM Version:**
5.0.3

* **JSPM OR Webpack AND Version**
webpack 2.6.1

* **Browser:**
all 

* **Language:**
TypeScript 2.4

**Current behavior:**
Supply `keyboard: ["Escape"]` and observe that the dialog closes on Enter, not just Escape.   Doesn't matter whether `lock` is true or false.

**Expected/desired behavior:**
* **What is the expected behavior?**
According to the Aurelia documentation, the dialog should not close on enter unless one supplies "Enter" in the array supplied to the `keyboard` setting.

* **What is the motivation / use case for changing the behavior?**
A dialog that can be cancelled via ESC, but where any other response must come from the mouse (or touch).

**Comment by dkent600** [comment]
As an aside to this, the documentation is not clear, at least to me, exactly *how* the keyboard setting "overrides" the lock setting.  I would request that this bit of documentation be cleared up.

The "lock" setting makes a dialog model with respect to mouse clicks outside the dialog (and removes the "X" button).  That would seem to me to be independent of the keyboard behavior.

**Comment by StrahilKazlachev** [comment]
1. About the `ENTER` issue - please do make sure you don't have any button that closes the dialog on focus when pressing the enter key.
2. The `lock` setting is pre RC setting that used to control 3 things:
    - false - can close on ESC or outside click, the `x` button is visible
    - true - can not close on ESC or outside click, the `x` button is not visible.
For the RC we introduced `keyboard` and `overlayDismiss` settings and added a bindable property - `show-close-button` to the `<ux-dialog-header>`. Now `lock` is a *legacy* setting that we left for compatibility reasons and is overridden by any of the mentioned settings and bindable property.

**Comment by dkent600** [comment]
You are right, Enter was being trapped by a button with focus.  Sorry for the false alarm, and thanks for the documentation update.  This can be closed.

Regarding `show-close-button`, I don't think this is such a great idea as adding a new setting that controls it's visibility.  I explained why [here](https://github.com/aurelia/dialog/issues/304).

**Comment by dkent600** [comment]
With regard again to docs, such as `overlayDismiss`, it would be really good, and standard, if the docs gave the default value for each optional setting.
