### ISSUE TITLE
create separate setting to control presence of 'X' button

### ISSUE THREAD

**Issue by dkent600** [aurelia/dialog#304]
**I'm requesting a feature change **

The "lock" setting makes a dialog model with respect to mouse clicks outside the dialog.

It also removes the 'X' button.  What is the motivation for removing the 'X' button?  Being modal should not imply anything about whether a dialog can be closed by clicking on the 'X' button *within* the dialog.

I would request that there be a separate dialog setting that removes (or adds) the 'X' button.

** Use case motivation

A modal dialog that can be closed, effectively cancelled by clicking on the 'X' button.

**Comment by StrahilKazlachev** [comment]
Use the bindable property `show-close-button` to the `<ux-dialog-header>`.

**Comment by dkent600** [comment]
> Use the bindable property show-close-button to the <ux-dialog-header>

That doesn't work unless you have access to the view/viewmodel that defines the dialog.  But if one is providing settings for a dialog that is contained in, for example, a plugin, then this option is not available.

**Comment by StrahilKazlachev** [comment]
I'm against any new settings that control/provide defaults for bindable properties.
The user of the plugin may use own custom elements and not the `aurelia-dialog` provided ones - which are *optional*.
Plugins should provide their own API for any additional custom settings. We may reserve a keyword in `DialogSettings` for a custom settings object - like the `settings` field in `RouteConfig`.
@PWKad @EisenbergEffect what are your opinions?

@dkent600 Currently we don't intend to remove or modify the legacy `lock` setting so you can achieve what you want like this:
```javascript
{
  lock: false,
  keyboard: false,
  overlayDismiss: false
}
```
All elements will have the `x` button but none will be closed on ESC or outside click.

**Comment by dkent600** [comment]
OK, but I assume `lock` is deprecated, so it isn't reliably supported.

**Comment by dkent600** [comment]
I am little uncomfortable with the mix of bindable properties and configuration settings here.....
