### ISSUE TITLE
Styles still use old naming "ai-" instead of "ux-"

### ISSUE THREAD

**Issue by hoangcuongvn** [aurelia/dialog#306]
**I'm submitting a bug report**

* **Library Version:**
1.0.0-rc.1.0.3

* **Operating System:**
Windows 10

* **Node Version:**
6.2.0

* **NPM Version:**
3.8.9

* **JSPM OR Webpack AND Version**
webpack 2.6.1

* **Browser:**
all

* **Language:**
all

**Current behavior:**
Styles still use old naming "ai-" instead of "ux-".
https://github.com/aurelia/dialog/tree/master/styles

**Expected/desired behavior:**
Renaming "ai-" to "ux-" in input.less.

**Comment by StrahilKazlachev** [comment]
@PWKad This file is not in use, the styles are inlined in `dialog-configuration.ts` since beta. Are there any plans to use it? If not I suggest we remove it.

**Comment by hoangcuongvn** [comment]
I think it's used to generate that inline css. This output.less is necessary in customizing aurelia-dialog through custom css. So please do not remove it.

**Comment by StrahilKazlachev** [comment]
@hoangcuongvn definitely not used. Currently they are out-of-sync. The inlined styles are OK, you can check if you want. There has not been any build task to do such injection.

**Comment by RichiCoder1** [comment]
I'd like them to stick around as they make an excellent template if I want to replace the inline styles.

**Comment by Alexander-Taran** [comment]
pr seems legit
if css file is not used -> can merge
if css file is used and styles are wrong -> should be merged
