### ISSUE TITLE
Dialog is not modal in IE10

### ISSUE THREAD

**Issue by GabrielMancik** [aurelia/dialog#308]
**I'm submitting a bug report**

* **Library Version:**
1.0.0-rc.1.0.3

**Please tell us about your environment:**
* **Operating System:**
Windows 8.1

* **Node Version:**
6.9.2

* **NPM Version:**
3.9.6

* **JSPM Version**
JSPM 0.16.48

* **Browser:**
IE 10

* **Language:**
TypeScript (did not tried other)

**Current behavior:**
Buttons outside dialog are clickable

**Expected/desired behavior:**
Buttons outside dialog should not be clickable

**Notes**
Tried with nearly empty dialog (only text inside ux-dialog element) to rule out other causes.

**Comment by StrahilKazlachev** [comment]
Can we get this issues formatted according to the template and some more descriptive info?

**Comment by GabrielMancik** [comment]
I was so vague because I thought that everything was clickable. But it is not. I am using aurelia-mdl package (https://github.com/genadis/aurelia-mdl) and whole menu element is clickable.
```
<label mdl="checkbox" class="mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect" for="rememberMeCheckbox">
	<input type="checkbox" id="rememberMeCheckbox" class="mdl-checkbox__input" checked.bind="rememberCredentials">
	<span class="mdl-checkbox__label">Remember Me</span>
</label>
```

Here checkbox itself is not clickable but label is.

```
<button mdl="button" id="reload-list-button" click.delegate="loadList()" class="mdl-button mdl-js-button mdl-js-ripple-effect">
	<i class="material-icons">refresh</i>
</button>
```

Here button is clickable only one time and then i can not click it anymore

**Comment by StrahilKazlachev** [comment]
@GabrielMancik Can you confirm that you have this problem only with elements that have the `mdl` attribute?

**Comment by StrahilKazlachev** [comment]
Closing since there hasn't been a response for over a year.
