### ISSUE TITLE
Scrolling

### ISSUE THREAD

**Issue by Mordred** [aurelia/dialog#31]
Bootstrap modal is setting `.modal-open` class on the `body` element to set `overflow: hidden`. Can you add this behaviour so that scrolling will not scroll page under dialog?

**Comment by Mordred** [comment]
Can you release this?

**Comment by PWKad** [comment]
@Mordred I saw an issue on the dialog and realized this commit broke the styling on the modal.  It is now 100% width of the screen.  Are you sure that the PR was working properly?  I'm going to have to back it out I think.  You can see the issue by cloning the repository and running the sample app with `gulp watch`

**Comment by Mordred** [comment]
@PWKad Can you post some images? Because I don't know what you mean. I've tried your sample it using Chrome and modal has only 300px. What browser are you using?

**Comment by PWKad** [comment]
Sorry I think the issue was the Chrome styling for a native `dialog` element caused the math introduced in this PR to work but when I switched the name it went crazy.  Sorry for the false alarm.
