### ISSUE TITLE
showCloseButton bindable property not working

### ISSUE THREAD

**Issue by zhhz** [aurelia/dialog#314]
**I'm submitting a bug report**
aurelia-dialog

* **Library Version:**
1.0.0-rc1.0.3

**Please tell us about your environment:**
* **Operating System:**
OSX 10.x

* **Node Version:**
6.2.0

* **NPM Version:**
3.8.9

* **Browser:**
all

* **Language:**
ES6

**Current behavior:**
UxDialogHeader component seems like ignores the bindable property 'showCloseButton'.

**`<ux-dialog-header showCloseButton.bind="showCloseBtn">`**

All it matters is the [controller|config].settings.lock=[true|false]

* **What is the expected behavior?**
the showCloseButton should have the highest priority

**Comment by StrahilKazlachev** [comment]
Use `show-close-button` as you would with any other bindable property.

**Comment by zhhz** [comment]
duh, how silly I was. It got me again. Thanks for the quick response.
