### ISSUE TITLE
Cannot read property 'lock' of undefined when using ux-dialog-header

### ISSUE THREAD

**Issue by AngkouLee** [aurelia/dialog#317]
**I'm submitting a bug report**

* **Library Version:**
1.0.0-rc.1.0.3

**Please tell us about your environment:**
* **Operating System:**
Windows 7

* **Node Version:**
6.5.0

* **NPM Version:**
4.3.0

* **JSPM OR Webpack AND Version**
No JSPM or webpack 

* **Browser:**
Chrome Version 59.0.3071.115 | Firefox 54.0.1

* **Language:**
TypeScript 2.0.0

**Current behavior:**

1. Using DialogServer in file A.ts, and open a dialog using viewModel B.
2. In B.html, using <ux-dialog-header> tag, only have text in it.
3. Error will show when loading the page A. Error message is 'TypeError: Cannot read property 'lock' of undefined', the error is about the code under src/ux-dialog-header.ts line 33, 'this.controller.settings' is not defined.
4. viewModel B is a custom element, only use aurelia-framework and jquery in it.
5. Here is the code I used to open a dialog:
`this._dialogService.open({ viewModel: B, model: 'Good or Bad?', lock: false}).whenClosed(response => {
      if (!response.wasCancelled) {
        console.log('good');
      } else {
        console.log('bad');
      }
      console.log(response.output);
    });`
6. After all the attempts, I used the code in dialog documentation to do the same thing but still failed.

**Expected/desired behavior:**

* **What is the expected behavior?**

The page will load without error and ux-dialog-header can be successfully show

**Comment by StrahilKazlachev** [comment]
I'll request a repro. Under normal circumstances I can't think of a case where the `DialogController` will not be injected.

**Comment by StrahilKazlachev** [comment]
No response.

**Comment by Sayan751** [comment]
@StrahilKazlachev I have faced this issue while unit testing a dialog VM. Only I was directly testing those instead of using DialogService. It seems that the dialog service with the ehlp of dialog composition engine composes and injects the settings to DialogController while instantiating.

However, as the Dialog VM is directly tested, there is  practically no opportunity to inject the settings to dialog controller. I tried the following handler, and it worked.

```javascript
aurelia.container.registerHandler(DialogController, () => {
  const defaultDialogSettings = aurelia.container.get(DefaultDialogSettings);
  return aurelia.container.invoke(DialogController, [defaultDialogSettings]);
});
```

However, i feel that performing the tests by using DialogService is better approach.

**Comment by StrahilKazlachev** [comment]
@Sayan751 it entirely depends on what you are testing, if it's just custom elements then I wouldn't go with the `DialogService`. Just using `aurelia-testing` is enough for me.

**Comment by Sayan751** [comment]
@StrahilKazlachev 
The problem in my case is that the following line in `ux-dialog-header` fails as there is no settings injected to the controller.

```javascript
this.showCloseButton = !this.controller.settings.lock;
```

And in my dialog VM, I have `<ux-dialog-header>` element. Therefore, in order to make this thing work, I need to provide the settings somehow.
