### ISSUE TITLE
Tabbing is allowed under dialog

### ISSUE THREAD

**Issue by rokaskuciauskas** [aurelia/dialog#331]
Do Aurelia support tabbing prevention under the aurelia dialog, because now it is possible to use tab on page under modal.

**Comment by timfish** [comment]
This is party covered by #1.

See [my comment](https://github.com/aurelia/dialog/issues/1#issuecomment-342782883) there which details a custom attribute which can help.

**Comment by StrahilKazlachev** [comment]
Questions are to be asked on our [Discourse forums](https://discourse.aurelia.io/), [Gitter channel](https://gitter.im/aurelia/discuss), SO, ... Also this is part of #1.
