### ISSUE TITLE
Aurelia dialog throws Access is denied error in IE11 and Edge when running in iFrame

### ISSUE THREAD

**Issue by ItWorksOnMyMachine** [aurelia/dialog#334]
**I'm submitting a bug report**

* **Library Version:**
1.0.0-rc.2.0.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
8.8.1

* **NPM Version:**
5.5.1

* **JSPM OR Webpack AND Version**
webpack 3.5.5

* **Browser:**
IE11 and Edge

* **Language:**
TypeScript 2.4.2

**Current behavior:**
When using an Aurelia application embedded in an iFrame, when the DialogService's open method is called, then IE11 and Edge throw an Access is denied error inside aurelia-metadata's Origin.get method.

**Expected/desired behavior:**
The expected behavior is that the dialog shows itself.  This works fine in Chrome and Firefox, it only fails in IE11 and Edge.

* **What is the motivation / use case for changing the behavior?**
The motivation is to be able to show an Aurelia dialog correctly when the application is running in an iFrame.  Granted, it's an edge-case, but probably one that will happen as legacy apps start migrating to newer apps using frameworks like Aurelia.

**Comment by StrahilKazlachev** [comment]
Since you've pinpointed the problem, why not submit the issue in `aurelia-metadata`? I can dig into the issue, but I'll need the version of `aurelia-metadata` you are using.

**Comment by StrahilKazlachev** [comment]
You are probably opening a dialog passing a `class` for `viewModel`? If so a work around will be to use a app root relative *moduleId*.

**Comment by ItWorksOnMyMachine** [comment]
@StrahilKazlachev, you rock!  The switch to moduleId fixes this issue for me.
