### ISSUE TITLE
'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.

### ISSUE THREAD

**Issue by dijkpim** [aurelia/dialog#337]
**I'm submitting a bug report**

* **Library Version:**
1.0.0-rc.2.0.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
v8.9.1

* **NPM Version:**
v5.5.1

* **JSPM OR Webpack AND Version**
webpack 3.8.1

* **Browser:**
all

* **Language:**
TypeScript X.X

**Current behavior:**
[Deprecation] 'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.
(anonymous) @ vendor.js:11688
(anonymous) @ aurelia-loader-webpack.js:144
WebpackLoader.__WEBPACK_IMPORTED_MODULE_2_aurelia_pal__.PLATFORM.eachModule @ aurelia-loader-webpack.js:141
get @ vendor.js:11685
58.DialogService.ensureViewModel @ dialog-service.js:55
58.DialogService.open @ dialog-service.js:131
Landing.test @ landing.ts:80
evaluate @ vendor.js:7533
callSource @ vendor.js:11122
handleEvent @ vendor.js:11131
handleDelegatedEvent @ vendor.js:9246

**Expected/desired behavior:**
I followed the aurelia docs:
http://aurelia.io/docs/plugins/dialog#attach-focus-custom-attribute

* **What is the expected behavior?**
No warning of Deprecation

* **What is the motivation / use case for changing the behavior?**
Deprecation

**Comment by StrahilKazlachev** [comment]
Issue is for `aurelia-pal`/`aurelia-pal-browser`, the dialog does not use any storage APIs.
