### ISSUE TITLE
templating load error "Too much recursion" when using aurelia-bootstrapper 2.2.0

### ISSUE THREAD

**Issue by chrsmrtn-** [aurelia/dialog#340]
**I'm submitting a bug report**

* **Library Version:**
1.0.0-rc.2.0.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
7.4.0

* **NPM Version:**
5.3.0

* **JSPM OR Webpack AND Version**
Aurelia CLI 0.31.3

* **Browser:**
Chrome 64.0.3282.167 
Firefox 58.0.2 (64-bit) 
Edge 41.16299.15

* **Language:**
TypeScript 2.7.1

**Current behavior:**
Unable to load app due to templating error for Aurelia-dialog.  This worked fine with Aurelia-bootstrap version 2.1.1. Updated to Aurelia-bootstrap 2.2.0 and now get the following error in Firefox.  Similar "recursive errors" show up in Edge and Chrome as well.

DEBUG [templating] importing resources for aurelia-dialog/ux-dialog-footer 
Array []
vendor-bundle.js:14042:8
Unhandled rejection InternalError: too much recursion
    _compileElement@http://localhost:9000/scripts/vendor-bundle.js:21438:9
    _compileNode@http://localhost:9000/scripts/vendor-bundle.js:21252:18
    _compileNode@http://localhost:9000/scripts/vendor-bundle.js:21274:28
    compile@http://localhost:9000/scripts/vendor-bundle.js:21221:7
    compile@http://localhost:9000/scripts/vendor-bundle.js:22695:37
    _compileElement@http://localhost:9000/scripts/vendor-bundle.js:21528:16
    _compileNode@http://localhost:9000/scripts/vendor-bundle.js:21252:18
    _compileNode@http://localhost:9000/scripts/vendor-bundle.js:21274:28
    compile@http://localhost:9000/scripts/vendor-bundle.js:21221:7
    compile@http://localhost:9000/scripts/vendor-bundle.js:22695:37
    _compileElement@http://localhost:9000/scripts/vendor-bundle.js:21528:16
    _compileNode@http://localhost:9000/scripts/vendor-bundle.js:21252:18
    _compileNode@http://localhost:9000/scripts/vendor-bundle.js:21274:28
    compile…
vendor-bundle.js:1398:13

**Expected/desired behavior:**
The templating to load the Aurelia-dialog-footer without the recursion error

To reproduce update the Aurelia-bootstrapper to version 2.2.0 in a project that has the Aurelia-dialog working with Aurelia-bootstrapper 2.1.1

* **What is the expected behavior?**
For the Aurelia-dialog to import its resources properly without error

* **What is the motivation / use case for changing the behavior?**

**Comment by compgumby** [comment]
Same here... Serious bummer.

**Comment by Alexander-Taran** [comment]
If you look at changes between 2.1.1 and 2.2.0, only the dependencies changed
https://github.com/aurelia/bootstrapper/compare/c781a80515d35c9ab2f571138fe916d2bfe47d1f...master

**Comment by StrahilKazlachev** [comment]
Try a clean install of the dependencies.

**Comment by chrsmrtn-** [comment]
Will do. I think this means I just delete node_modules folder and run `npm install`? If not, how does one perform a clean install of dependencies

**Comment by StrahilKazlachev** [comment]
Yes, delete and install.

**Comment by chrsmrtn-** [comment]
That did the trick. I did update NPM to version 5.6.0 in the meantime

**Comment by elitemike** [comment]
I am running into this issue and a clean install didn't help me.  I'm using NPM 5.7.1
