### ISSUE TITLE
Plugin setting configurations not working

### ISSUE THREAD

**Issue by TomStark16** [aurelia/dialog#355]
**I'm submitting a bug report**

* **Library Version:**
^1.0.0-rc.1.0.3

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
v8.11.3

* **NPM Version:**
6.1.0

* **JSPM OR Webpack AND Version**
No JSPM or webpack

* **Browser:**
all

* **Language:**
TypeScript ^2.6.2

**Current behavior:**
1. Default settings are configured for the aurelia-dialog with "lock" set to false so the "X" close button should show.
eg: 

`import { FrameworkConfiguration } from "aurelia-framework";

export const configure = (aurelia: FrameworkConfiguration, config: any) => {
  aurelia
    .plugin('aurelia-dialog', (dConfig: any) => {
      dConfig.useDefaults();
      dConfig.settings.lock = false;
      dConfig.settings.showCloseButton = true;
      dConfig.settings.centerHorizontalOnly = true;
      dConfig.settings.centerVerticalOnly = true;
      dConfig.settings.startingZIndex = 1000;
    })
    .plugin('aurelia-validation');
};
`
2. When we import DialogService and call "open({viewModel, model})" the "X" button is not appearing. Debugging up to this point shows that this.dialogService.defaultSettings.lock = true (not set to false like we have configured in the plugin's default settings). 

**Expected/desired behavior:**
For the Close button to show. 

* **What is the expected behavior?**
For the Close button to show. 

* **What is the motivation / use case for changing the behavior?**
We believe a code change between the following dates July 19th, 2018 - July 30th, 2018 has caused the issue. We can't identify any changes on our end between theses dates that may have effected the close button which is why we are thinking this might be a bug.

**Comment by StrahilKazlachev** [comment]
`lock` has been *deprecated*(*not* remove), since `v1.0.0-rc.1.0.0` - use `keyboard` and `overlayDismiss`.
`showCloseButton` - this is *undocumented* *@bindable* property of `<ux-dialog-header>`, it isn't a *general* dialog setting.
