### ISSUE TITLE
Cannot find name 'AddEventListenerOptions'. 

### ISSUE THREAD

**Issue by falconmick** [aurelia/dialog#371]
**I'm submitting a bug report**

* **Library Version:**
dialog#1.0.0-beta.3.0.1

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
8.15.0

* **NPM Version:**
6.4.1

* **JSPM OR Webpack AND Version**
JSPM 0.16.41

* **Browser:**
all

* **Language:**
TypeScript 3.3

**Current behavior:**
Build failing due to typing issue originating out of this packages typings:
typings\modules\aurelia-dialog\index.d.ts(1576,44): error TS2304: Cannot find name 'AddEventListenerOptions'. 

**Expected/desired behavior:**
to not get typings errors

**Comment by bigopon** [comment]
@falconmick Can you at least update to latest version of v1? v1.0.0-beta.x is a bit hard to support/debug now

**Comment by bigopon** [comment]
If you still get the same error with v1, please help comment here

**Comment by falconmick** [comment]
I'll get back to you. It's an older project and nobody left at the company knows it so It's kinda not a fun day when this stops working! Thanks for getting back to me

**Comment by StrahilKazlachev** [comment]
There is something strange here. First there is no such type - `AddEventListenerOptions`, used in the `1.0.0-beta.3.0.1` [types](https://github.com/aurelia/dialog/blob/1.0.0-beta.3.0.1/dist/aurelia-dialog.d.ts). Second, this is a DOM API, I have no recollection of having anything explicitly typed with it. Third, what is this line number - *1576*? The .d.ts file for this version is only 231 lines.
> typings\modules\aurelia-dialog\index.d.ts(1576,44)

**Comment by rajansen** [comment]
looks like aurelia-templating.d.ts is imported from the latest dist, see this commit:
https://github.com/aurelia/templating/commit/d2da4143389291077a7efd05d960f5ed45dcc0cf#diff-d4ec8ae7ec00cac9b4cc47b504a8882c

**Comment by StrahilKazlachev** [comment]
So this issue can be closed, since it's not in the dialog?

**Comment by falconmick** [comment]
Issue must have been due to build server and dev machines being on a certain typescript version and then somthing made both of em jump to another as the issues were caused by wrong versions of typescript
