### ISSUE TITLE
Typings fail to install

### ISSUE THREAD

**Issue by tcs-devel** [aurelia/dialog#376]
[4c9929c](https://github.com/aurelia/dependency-injection/commit/4c9929c5c503809157c193fde61630b8a5d36ea9) or another recent change seems to break typings installation.

```
typings ERR! message Unable to read typings for "aurelia-dependency-injection". The author of "aurelia-dialog" needs to check the entry paths in "typings.json" are up to date
typings ERR! caused by https://raw.githubusercontent.com/aurelia/dependency-injection/master/dist/aurelia-dependency-injection.d.ts/index.d.ts responded with 404, expected it to equal 200
```

Note: we are using version 1.0.0-rc.2.0.0 but I assume the issue also exists in the latest version as no specific version is specified in your `typings.json`.

**Comment by StrahilKazlachev** [comment]
Tracked here https://github.com/aurelia/dependency-injection/issues/178
