### ISSUE TITLE
DialogCloseError is not exposed in typings

### ISSUE THREAD

**Issue by silbinarywolf** [aurelia/dialog#382]
**I'm submitting a bug report**

* **Library Version:**
2.0.0-rc.7

**Please tell us about your environment:**
* **Language:**
TypeScript

**Current behavior:**
Cannot import DialogCloseResult, like so:
```
import { DialogCloseResult } from 'aurelia-dialog';
```

Looks like a mistake where the following file isn't importing the generated type info:
```
https://github.com/aurelia/dialog/blob/master/dist/types/aurelia-dialog.d.ts
https://github.com/aurelia/dialog/blob/master/dist/types/dialog-close-error.d.ts
```

**Expected/desired behavior:**
I should be able to import this type information.

**Comment by bigopon** [comment]
@silbinarywolf thanks for filing this. This is probably because of merging v2 to master work. Would be nice if you could help PR to fix this 👍

**Comment by StrahilKazlachev** [comment]
It only needs a reexport added to `aurelia-dialog.ts`.
