### ISSUE TITLE
Export the Prompt example

### ISSUE THREAD

**Issue by heruan** [aurelia/dialog#40]
It would be nice to have `Prompt` exported to import it for the most common use-cases.

**Comment by heruan** [comment]
Or, better, a simple confirmation Yes/No dialog!

**Comment by PWKad** [comment]
We were previously exporting the prompt but it's more of an example - I'll leave this issue open and if we get more interest maybe we can make it as an export again.

**Comment by EisenbergEffect** [comment]
In my experience, people want to do prompts a little different, even from app to app, so I'm not sure if we should include one out of the box. However, this might be a great way to do some documentation. Basically, create the prompt as part of a docs article on how to use the dialog plugin. Thoughts?
