### ISSUE TITLE
404 on typings install for Aurelia metadata

### ISSUE THREAD

**Issue by adamavenant** [aurelia/dialog#408]
**I'm submitting a bug report**

* **Library Version:**
1.0.0-beta.3.0.1

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.2.0

* **NPM Version:**
3.10.10

* **JSPM OR Webpack AND Version**
JSPM 0.16.55

* **Browser:**
all

* **Language:**
all

**Current behavior:**
When running `npm install`, the following error is returned: 
`typings ERR! message Unable to read typings for "aurelia-metadata". You should check the entry paths in "typings.json" are up to date
typings ERR! caused by https://raw.githubusercontent.com/aurelia/metadata/master/dist/types/aurelia-metadata.d.ts/index.d.ts responded with 404, expected it to equal 200`

**Expected/desired behavior:**

`npm install` completes successfully

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**
This is breaking our build and we would like to fix it. The error message recommends contacting the author of

**Comment by Alexander-Taran** [comment]
@adamavenant not sure what do you mean.
cloning the repo and npm Install works
adding Aurelia-dialog to package.json and running npm install works.
What does not work for you?

**Comment by Alexander-Taran** [comment]
@bigopon 
```ts
async triageQuestion(id) =>{
 respondSameDay()
 let response = await getResponseFromOP( { timeout : fromWeeks(4) } )
 if(!response) {
    closeQuestion(id,randomReason())
 }
}
```

**Comment by bigopon** [comment]
should be already fixed
