### ISSUE TITLE
configuring

### ISSUE THREAD

**Issue by derekpitt** [aurelia/dialog#47]
It would be kind of cool to pass in a callback to configure some global stuff in the renderer (or anything for that matter).. something like:

     aurelia.use('aurelia-dialog', config => {
       config.renderer.defaultSettings.lock = true;
     });

or something like that, so i don't have to put configuration in each place where I use the controller.

I can whip up an example if you guys would like?

Let me know what you think

**Comment by PWKad** [comment]
Seems reasonable enough - creating a todo for this.
