### ISSUE TITLE
Ability to close a dialog from the DialogService

### ISSUE THREAD

**Issue by iosulfur** [aurelia/dialog#49]
I have this use case:

1. Open one modal for confirmation via `this.dialogService.open`: "Do the update?": [Yes] [No]
2. Open one modal for progress via `this.dialogService.open`: "Progress of the update.": (no buttons)
3. Close the modal via `this.dialogService.close`.
4. Open one modal for progress via `this.dialogService.open`: "Complete. Refresh page.": [Refresh]

I expect to be able to run step 3, but the dialog service class has no such method. Without that method, calling another `this.dialogService.open` will open the original modal from step 1.

**Comment by PWKad** [comment]
You really shouldn't have more than one open dialog at a time.  Why not just have a single dialog that composes it's body depending on what step you are on so you can manage the state easier?

**Comment by iosulfur** [comment]
I agree. I was trying to rely on the user closing, or the code closing the previous modal before opening another.

Your suggestion is a much better way to handle a changing modal. I have refactored my usage and tested such an implmentation succesfully. Thank you.

I am now:

1. Open one modal for upgrade.
2. Implement buttons that trigger custom methods.
3. Work on the view-model passed to the dialog as if it is a miniature view.
4. Track state of upgrade.
5. Use upgrade state variable in template to change markup:

```
<template>
  <ai-dialog>

    <template if.bind="state.isA">
      <ai-dialog-header>
        <span>State A</span>
      </ai-dialog-header>

      <ai-dialog-body>
        <p>Status A</p>
      </ai-dialog-body>

      <ai-dialog-footer>
        <button click.trigger="a()">Action A</button>
        <button click.trigger="controller.cancel()">Cancel</button>
      </ai-dialog-footer>
    </template>

    <template if.bind="state.isB">
      <ai-dialog-header>
        <span>State B</span>
      </ai-dialog-header>

      <ai-dialog-body>
        <p>Status B</p>
      </ai-dialog-body>

      <ai-dialog-footer>
        <!-- no buttons -->
      </ai-dialog-footer>
    </template>

    <template if.bind="state.isC">
      <ai-dialog-header>
        <span>State C</span>
      </ai-dialog-header>

      <ai-dialog-body>
        <p>Status C</p>
      </ai-dialog-body>

      <ai-dialog-footer>
        <button click.trigger="c()">Action C</button>
      </ai-dialog-footer>
    </template>

  </ai-dialog>
</template>
```

**Comment by genericuser-me** [comment]
I have a use case where I am calling dialog within dialog:
I have a dialog, where I show the progress of file uploading.

Now, when I edit the file, I give the ability to change the underlying file (Edit is a dialog),

1. Edit File Properties (1st dialog)
2. Replace underlying File
3. Upload progress (2nd dialog).
4. On completion of upload dialog progress bar, close that dialog.
5. Call  `this.dialog.close(true)` on the edit dialog.

The step 5 doesnt close the edit dialog. It just stays there.  Any suggestions?
