### ISSUE TITLE
How to implement 'Pressing escape will cancel / close the dialog'

### ISSUE THREAD

**Issue by sickboy** [aurelia/dialog#52]
Would this be a functionality to be built into the dialog component, or up to the app designer?
Any suggestions on how to proceed?

I suppose canDeactivate lifecycle behavior needs to be definable then..

**Comment by PWKad** [comment]
@sickboy this is already built in functionality for the plugin - if you define that the controller is lock = false as shown in the readme it would allow pressing escape to cancel.  In the future please direct questions to our official gitter - gitter.im/aurelia
