### ISSUE TITLE
The dialog positioning does not work correctly when the body of the dialog contains a compose tag

### ISSUE THREAD

**Issue by jbgarr** [aurelia/dialog#53]
When creating a custom dialog that uses a `<compose>` tag in the body, the dialog is not positioned correctly when it's opened. So for example, something like the following will result in the dialog being positioned in the lower right of the screen instead of centered vertically and horizontally.

Dialog Content
```
<template>
  <ai-dialog>
    <ai-dialog-body>
      <compose view-model="myViewModel"></compose>
    </ai-dialog-body>

    <ai-dialog-footer>
      <button click.trigger="controller.cancel()">Cancel</button>
      <button click.trigger="controller.ok()">Ok</button>
    </ai-dialog-footer>
  </ai-dialog>
</template>
```

myViewModel.html - the view that's being composed in the dialog.
```
<template>
  <style>
    .testContent {
      width: 600px;
      height: 300px;
    }
  </style>

  <div class="testContent">
    <p>Hello There!</p>
  </div>
</template>
```

**Comment by PWKad** [comment]
Hi @jbgarr sorry for just getting around to this but I've confirmed this is not an issue on latest.  Please feel free to re-open if you can reproduce again but for now it is working as expected with the repro above.
