### ISSUE TITLE
Make the stylesheet a configuration option.

### ISSUE THREAD

**Issue by rquast** [aurelia/dialog#54]
The stylesheet is currently hardcoded into the plugin. Would like to see this as an option so the look can be more customizable.

**Comment by PWKad** [comment]
You can actually use your own custom modal and stylesheet very easily - need to rename this issue something like 'Include instructions for a custom modal / dialog'

**Comment by alexmills** [comment]
I'm using custom modals but there is still a stylesheet taking over? Am I missing something?

**Comment by PWKad** [comment]
@alexmills Can you show an example of your modal implementation with code?  I'll post how and why it doesn't collide and close this issue.

**Comment by alexmills** [comment]
Configured in main.ts

``` javascript
export function configure(aurelia) {

    // Developement Profile
    aurelia.use
      .standardConfiguration()
      .developmentLogging()
      .plugin('aurelia-html-import-template-loader')
      .plugin('aurelia-dialog')
      .plugin('aurelia-validation');

  aurelia.start()
  .then(a => a.setRoot());
}
```

Simple Modal HTML (__UploadErrorModal__)

``` html
<template>
  <require from="common/select"></require>
  <ai-dialog class="little">
    
    <ai-dialog-header>
      Upload Error: ${name}
    </ai-dialog-header>
    
    <ai-dialog-body>

      <div class="label-text-group">
        <p class="label-text">Unable to upload file, please try again.</p>
      </div>

    </ai-dialog-body>
    
    <ai-dialog-footer>
      <button class="btn-green-outline" click.trigger="controller.cancel()">OK</button>
    </ai-dialog-footer>
    
  </ai-dialog>
</template>
```

Called using DialogService (__dialog__)

``` javascript
this.dialog.open({viewModel:UploadErrorModal,model:file})
```

But there is CSS inserted at the top of the page which takes over footer buttons

<img width="313" alt="screen shot 2015-11-25 at 9 19 57 am" src="https://cloud.githubusercontent.com/assets/661414/11385640/c7501198-9355-11e5-8525-31b9b060854f.png">

**Comment by PWKad** [comment]
The `ai-dialog` custom element and it's children would all use their own styling - if you want to have your own modal implementation you should create your own variation such as `am-dialog` or `my-modal` or whatever you want to name it.  This prevents collision for styling and naming.
