### ISSUE TITLE
Dialog errors for Firefox on core-js@1.2.x

### ISSUE THREAD

**Issue by JoshHarris** [aurelia/dialog#59]
We found that updating core-js to the latest version using `jspm dl-loader --latest` causes the dialog to not work in Firefox.  The semi-hacky fix that we found was to wrap a `try/catch` around the below block of code in `aurelia-metadata.js > origin.js > Origin.get`.  The simple fact of wrapping a `try` around the code seems to allow the getter function to attach, thus not producing an error and working.

We heard you were making a move towards updating all the libraries to use the newest core-js, so hear is an issue.

aurelia-metadata.js
```
  var Origin = (function () {
    function Origin(moduleId, moduleMember) {
      _classCallCheck(this, Origin);

      this.moduleId = moduleId;
      this.moduleMember = moduleMember;
    }

    Origin.get = function get(fn) {
      var origin = originStorage.get(fn);

      if (origin === undefined) {
        _aureliaPal.PLATFORM.eachModule(function (key, value) {
          for (var _name in value) {
            // This try fixes a race condition, because it works and nothing is ever caught.
            var exp;
            try {
              exp = value[_name];
            } catch (e) {

            }

            if (exp === fn) {
              originStorage.set(fn, origin = new Origin(key, _name));
              return true;
            }
          }

          if (value === fn) {
            originStorage.set(fn, origin = new Origin(key, 'default'));
            return true;
          }
        });
      }

      return origin || unknownOrigin;
    };

    Origin.set = function set(fn, origin) {
      originStorage.set(fn, origin);
    };

    return Origin;
  })();
```
You can recreate this with the sample dialog app, just don't forget to add this to your index.html
```
<script>
  // Loads WeakMap polyfill needed by MutationObservers
  System.import('core-js').then(function() {
    // Imports MutationObserver polyfill
    return System.import('polymer/mutationobservers');
  }).then(function() {
    // Ensures start of Aurelia when all required IE9 dependencies are loaded
    System.import('aurelia-bootstrapper');
  });
</script>
```

**Comment by michaelmalonenz** [comment]
Now that the libraries have been upgraded, this is an issue for me too - it also occurs on Edge, but somewhat interestingly, *not* on IE11

**Comment by michaelmalonenz** [comment]
As of this morning another person on my team upgraded to the beta and this issue is no longer present.  So either I hadn't upgraded all of the packages that use core-js, someone else updated their dependencies or there has been a bug fix come through.  Either way, we are now able to run our site with core-js v1.2.6

**Comment by PWKad** [comment]
Cool thanks!
