### ISSUE TITLE
WrongDocumentError in IE

### ISSUE THREAD

**Issue by alexmills** [aurelia/dialog#60]
Hey guys, got the following error being displayed in IE11/10/9 and is forcing the app to completely crash.

```
Unhandled promise rejection WrongDocumentError
Error loading <app-url>/jspm_packages/github/aurelia/dialog@0.4.1/ai-dialog.html!template-registry-entry
```

The issue is not present on any other browser. Is anyone also seeing this?

**Comment by EisenbergEffect** [comment]
@PWKad Can you check this out?

**Comment by PWKad** [comment]
IE10/11 is confirmed on the latest release can you please create a repro or give steps to repro?

**Comment by alexmills** [comment]
Sorry guys, it appears to be an issue with our IIS server encoding as the code works when deployed from an Apache. You may close this bug.
