### ISSUE TITLE
Create something similar to setDefaultButton

### ISSUE THREAD

**Issue by rquast** [aurelia/dialog#62]
Not a big issue, but a little bit of code for setDefaultButton would help reduce a few lines of code. Can it be included?

Similar questions with jquery ui dialog: http://stackoverflow.com/questions/2522125/jquery-ui-dialog-make-a-button-in-the-dialog-the-default-action-enter-key

**Comment by PWKad** [comment]
@rquast This can be achieved using the `attach-focus` custom attribute.

```html
<template>
  <ai-dialog>
    <ai-dialog-header>
    </ai-dialog-header>
    <ai-dialog-body>
      <h2>Edit first name</h2>
      <input value.bind="person.firstName" />
    </ai-dialog-body>

    <ai-dialog-footer>
      <button click.trigger="controller.cancel()">Cancel</button>
      <button attach-focus="true" click.trigger="controller.ok(person)">Ok</button>
    </ai-dialog-footer>
  </ai-dialog>
</template>
```

You can see this on the `Ok` button here.  Closing for now and documenting the feature.
