### ISSUE TITLE
Destroy modal only when modalContainer ends its transition

### ISSUE THREAD

**Issue by hadrienl** [aurelia/dialog#68]
If your dialog contains any child element which transition at the same time of the dialog closing, the `transitionend` event of this child element will close prematurely the dialog. The dialog is listening to `transitionend` event on `modalContainer` element. This event bubble, so its fired when any of its children ends its transition. The closing event listener should check if target is really `modalContainer`.

A use case should be a dialog with a save button which has its own transition of 0.2sec and which close the dialog on click. The dialog has a transition of 1sec. You'll see that the dialog will disappears at 0.2sec before finishing its own transition.

**Comment by PWKad** [comment]
Closed by your PR, thanks!
