### ISSUE TITLE
Dialog doesn't close on link click / navigation away from page

### ISSUE THREAD

**Issue by Zensavona** [aurelia/dialog#69]
Using `0.4.4`

For example I have a dialog open with a link inside it, if the link is clicked and the page navigates, the dialog remains open, blocking the page.

Not sure if this is even a bug or the intended behaviour.

**Comment by EisenbergEffect** [comment]
It's not something we want to provide behavior for now, since it's possible that one may want to navigate without closing the dialog. If you want this behavior, I would recommend adding a custom router pipeline step to close any open modal dialogs after navigation.
