### ISSUE TITLE
ai-dialog-open class removed with multiple dialogs

### ISSUE THREAD

**Issue by CasiOo** [aurelia/dialog#70]
If you open more than one dialog, then closing just one of them will remove the `ai-dialog-open` css class from body.

The class should not be removed, if there's still a visible dialog.

**Comment by PWKad** [comment]
I'm not sure that opening multiple dialogs is a supported use case.  Asking for some feedback from others on this as it's generally a bad UX pattern.

**Comment by PWKad** [comment]
@jedd-ahyoung Is this fixed by the last change for multiple dialogs?

**Comment by jedd-ahyoung** [comment]
@PWKad No. Those changes only address the controller and service layers. None of my changes actually addressed any of the renderer concerns - display and rendering of the DOM elements - as I understand that there are future changes coming in. I assumed that those changes would probably fix many of the issues related to display and rendering.

**Comment by Tim-Erwin** [comment]
A pretty common use case is having a bigger dialog, e.g. in order to edit something, and then asking for confirmation when the user closes it without saving or so.
