### ISSUE TITLE
Split templating and logic in 2 modules

### ISSUE THREAD

**Issue by jods4** [aurelia/dialog#72]
UI layout and templating is full of app-driven choices.

I would like to see all the CSS, positioning logic, custom elements and templates moved into a `aurelia-dialog-templating` (or whatever) module. 
So that I don't have to take a dependency on them and I could provide my own way of laying out and displaying dialogs.

On the other hand `aurelia-dialog` should still contain all the dialogs logic, which is not easy to write (at least for now, as not everything is documented thoroughly):
It resolves viewmodels and views, provides a nice system where you can re-use a dialog controller with specific models, supports dismissable and non dismissable dialogs, performs the composition and calls all the correct lifecycle events, in a way consistent with the rest of Aurelia.

**EDIT** I would like to add that a similar effort was started for `aurelia-validation` and I think it sets a precedent for splitting logic and UI in Aurelia, so that apps can easily use their own UI frameworks as they please. There's no reason for handling dialogs differently.

**Comment by PWKad** [comment]
I'll leave this open in the 'icebox' as we probably won't be splitting this out anytime soon unless there is more requests for this.  Validation is under refactor currently due to heavy requests to be able to use the validation logic on the server side as well and was driven more by community requests, so if we get more here we can re-evaluate.

**Comment by PWKad** [comment]
Closing this for now as I don't see the value in splitting at this point, welcome any feedback in the future on why we should.

**Comment by jods4** [comment]
I'm using my own dialog package for now. The one provided is too opiniated UI-wise for us to use.

> I don't see the value in splitting at this point

I don't have anything to add to what I said in the ticket. 
On the other hand it makes me smile that you said:

> Validation is under refactor currently due to heavy requests to be able to use the validation logic on the server side as well

Correct me if I'm wrong but the validation package is totally usable on the server-side today. 
This is all about removing unneeded dependencies and/or providing more UI flexibility.

**Comment by PWKad** [comment]
Like I said id be open to this more if we had more feedback that it was beneficial to others.  If you feel strongly you can reopen but just trying to prioritize for right now.
