### ISSUE TITLE
aurelia-dialog.d.ts incorrect

### ISSUE THREAD

**Issue by searus** [aurelia/dialog#82]
It looks like aurelia-dialog.d.ts doesn't match the source.  For example, the DialogController is defined as follows:
```typescript
  export class DialogController {
    constructor(renderer: DialogRenderer, settings: any, resolve: Function, reject: Function);
    ok(result: DialogResult): any;
    cancel(result: DialogResult): any;
    error(message: any): any;
    close(ok: boolean, result: DialogResult): any;
  }
```
Here, the methods `ok`, `cancel` and `close` are all expecting the `result` to be of type `DialogResult`, but this is not the case in the source.  `result` should be type `any`.

**Comment by jedd-ahyoung** [comment]
@searus - to clarify - the `DialogResult` should only be returned by the `open` method of the `DialogService`, but not the `DialogController` methods. The source reflects this, but the typescript definition files do not. Is this correct?

@PWKad, this looks like it might need the bug tag if it's applicable.

**Comment by PWKad** [comment]
I'm not sure, I'm not an avid TypeScriptist but doesn't this eventually return `DialogResult` from the `ok` method - https://github.com/aurelia/dialog/blob/master/src/dialog-controller.js#L38 ?  The promise inside the controller's close method eventually returns a result from what I can tell.

**Comment by searus** [comment]
The `open` method of the `DialogService` should return a promise of type `DialogResult`.  The `result` in the `DialogController` methods should be of type `any`.
I'm happy to submit a pull request for the change, but I thought the .d.ts files were auto generated somehow for Aurelia.

**Comment by PWKad** [comment]
A PR would be good the  `.d.ts` is generated directly from the code so please PR in that location where those methods are defined.

**Comment by chak99** [comment]
Hi searus, wondering if you would be able to help with AureliaForSharePointApps with router and adding more pages please?

**Comment by searus** [comment]
@PWKad I'm not sure what you mean by "where those methods are defined".  Should I be updating the *.d.ts files directly, or is there a definition file that is used to generate those?

**Comment by PWKad** [comment]
@searus https://github.com/aurelia/dialog/blob/master/src/dialog-controller.js#L11

We actually have types in the code that compile the .d.ts directly.  You can update the proper types there and it will fix the .d.ts :)

**Comment by searus** [comment]
@PWKad sorry, I'm struggling here.  
The tests don't work in the cloned repository:
```
ERROR: Potentially unhandled rejection [4] Error: XHR error (404 Not Found) loading http://localhost:9876/base/jspm_packages/npm/aurelia-logging@1.0.0-beta.1.1.1.js
```

Also (sorry noob question), do I need to fork the repository, then follow the contributing guidelines?  Otherwise I don't have permission to push my new branch.

**Comment by vuorinem** [comment]
@searus I had the same issue with testing, and came up with the same fix.

As far as I know, you should fork the repo, commit all changes to your fork in a new branch, then create a pull request.

**Comment by PWKad** [comment]
Ah good catch let me update the readme.  I think we can create those as JSPM dev dependencies as well so not everyone has to do that but I'll make sure that has no adverse affects.
