### ISSUE TITLE
Problems bundling an app

### ISSUE THREAD

**Issue by ggrimbert** [aurelia/dialog#83]
Hi,

I am trying to bundle my app. I call aurelia-dialog during the bundling process and it works, but, when I load my app, there are few .html files that are called (ai-dialog.html,ai-dialog-header.html, ai-dialog-body.html, ai-dialog-footer.html) directly in the jspm_packages folder.

![image](https://cloud.githubusercontent.com/assets/15869188/12615687/73bf092e-c507-11e5-9b45-3f7549094e7f.png)

In my bundle.js I call aurelia-dialog like this : 
```
 "dist/aurelia": {
      "includes": [
         "npm:aurelia-dialog@0.5.3",
...
 ],
      options: {
        inject: true,
        minify: true
      }
}
```

**Comment by EisenbergEffect** [comment]
@ahmedshuhel We need a nice way to handle these scenarios. This is a major use case.

**Comment by ggrimbert** [comment]
I have opened an issue at aurelia-bundler issue referencing this one and another problem : https://github.com/aurelia/bundler/issues/71

**Comment by PWKad** [comment]
I think this is fine to track over there, there shouldn't be any changes for the dialog to support bundler, if there is we can address at that time.
