### ISSUE TITLE
Make active overlay configurable (color/opacity)

### ISSUE THREAD

**Issue by heruan** [aurelia/dialog#84]
It would be nice to have options to configure the overlay when active, such as `background-color` and `opacity`, to have for example a faded overlay (see image).

![screen shot 2016-02-01 at 12 08 49](https://cloud.githubusercontent.com/assets/851745/12715890/23656750-c8dd-11e5-9e32-4f3325d0bb07.png)

**Comment by jedd-ahyoung** [comment]
This is technically possible by changing the style on the element, as you already have done.

Might it be worth it to consider adding a class binding to the parent element? I've been following this pattern with the custom elements that I create; I provide a default value for the class binding, but as a bindable it's overridable by the user. This means that a developer can create a CSS class declaration and use child selectors to style the element as he or she chooses.

For the dialog itself, this would require adding a `class`  parameter on the configuration object passed to the `dialogService.open` method.

**Comment by PWKad** [comment]
I'm wondering if you would actually want to do this vs just adding CSS to do this for you.  Any feedback welcome.

**Comment by heruan** [comment]
I think that options to set some basic style such as the overlay color/opacity would be a common case and be worth to have them in the Dialog Service `open` settings, e.g.
```javascript
this.dialogService.open({
    viewModel: Prompt,
    model: "A nice overlay",
    overlayColor: 'black',
    overlayOpacity: '.25'
})
```
any other uncommon overlay styling should be done via an additional stylesheet, I agree.

**Comment by jedd-ahyoung** [comment]
@heruan Perhaps we can make this more generic. What about adding a CSS class to the overlay in the settings object? Due to the changes in the dialog, this would happen per dialog instance (even with multiple dialogs) so it could be controllable on a case-by-case basis. This should be far more powerful than individual opacity and color settings. What do you think?

**Comment by itzikHagoel** [comment]
in the README you say to simply add this to the css:
"
ai-dialog-overlay.active {
  background-color: black;
  opacity: .5;
}
"
Maybe it's just me, but I have no idea how to apply it. Can you add an example?

**Comment by PWKad** [comment]
@itzikHagoel You just create a .css file in your project and reference it from one of the pages or view-models.

**Comment by PWKad** [comment]
There hasn't been a big demand for this and it's noted on how to add this via css so closing this for now.  If we have more demand later we can open it back up or look at other alternatives.
