### ISSUE TITLE
Cancel with ESC key

### ISSUE THREAD

**Issue by heruan** [aurelia/dialog#85]
It would be very useful a configurable option to enable the `ESC` key to cancel the dialog.

**Comment by jedd-ahyoung** [comment]
@PWKad This could use the feature tag.

Of note, I believe this actually works at the moment - I'll have to verify it tomorrow in my application, but I thought I'd gotten this behavior without any external tweaks. I may be wrong, though.

**Comment by PWKad** [comment]
@heruan Does this not work?

**Comment by PWKad** [comment]
Closing this works exactly as mentioned already when lock is set to false.
