### ISSUE TITLE
Version 5.0.4 does not work in IE11

### ISSUE THREAD

**Issue by Leonidnei** [aurelia/dialog#87]
We have some application using aurelia-dialog. 

Recently we updated aurelia-dialog from 5.0.3 to 5.0.4 and now it works in Chrome but not in IE.
The dialog is opened but buttons (OK/Cancel) are not clickable and also most of html input fields are not editable.

**Comment by piwnik** [comment]
I have same issue on Chrome, Opera, Edge, seems ai-dialog-overlay is over ai-dialog-container. Higher ai-dialog-container zIndex is ignored

**Comment by PWKad** [comment]
@piwnik I'm testing right now and trying to figure out why this changed in the latest will let you know.

**Comment by PWKad** [comment]
@Leonidnei Can you test changing the `pointer-events: initial` to `pointer-events: auto` in the `dialog.css` file in your `jspm_packages` folder?  I've pushed up a fix for this just want to confirm it works for you as well.

**Comment by Leonidnei** [comment]
I tested and it worked fine, thanks.
