### ISSUE TITLE
the pointer-events has been disabled after the 0.5.3 release

### ISSUE THREAD

**Issue by abbasmhd** [aurelia/dialog#94]
the `ai-dialog-container` is set to `pointer-events: none;` which is preventing all the events on children buttons 
setting `pointer-events: auto;` fixed the problem with was preventing the dialoge from closing
can you please fix this issue

**Comment by PWKad** [comment]
Thanks @abbasmhd this should be fixed already in master and released = https://github.com/aurelia/dialog/commit/2c4cfa635e178071cd8080384cfc1592cbfbaef2

That commit should have done the same.  Can you verify?

**Comment by abbasmhd** [comment]
thanks @PWKad  
that should do it
